#!/usr/bin/env python3
"""Vague 5n — workplace / data / sales (CRM, CS, ETL, BI, RPA, procurement)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
COVERAGE = ROOT / "catalogue-saas" / "coverage-matrix.json"
TODAY = "2026-06-23"
PASS_ID = "2026-06-v5n-workplace-data-sales"


def v(
    id_: str,
    name: str,
    url: str,
    segments: list[str],
    desc: str,
    caps: list[str],
    pricing: str,
    market: str,
    source: str,
    src_type: str,
    hq: str = "US",
    fr: str = "partial",
    regions: list[str] | None = None,
    geo: str = "global",
    notes: str | None = None,
) -> dict:
    d = {
        "id": id_,
        "name": name,
        "url": url,
        "segments": segments,
        "description": desc,
        "capabilities": caps,
        "pricing_model": pricing,
        "target_market": market,
        "geography": geo,
        "hq_country": hq,
        "france_market": fr,
        "operating_regions": regions or ["US", "EU"],
        "discovery_source": src_type,
        "discovery_pass": PASS_ID,
        "source_url": source,
        "source_consulted_at": TODAY,
        "verification_status": "partial",
    }
    if notes:
        d["notes"] = notes
    return d


ADDITIONS: dict[str, list[dict]] = {
    "crm-platforms.json": [
        v(
            "microsoft-dynamics-365-sales",
            "Microsoft Dynamics 365 Sales",
            "https://www.microsoft.com/dynamics-365/products/sales",
            ["crm-platforms"],
            "CRM enterprise Microsoft ; pipeline, Copilot sales et intégration Teams/Outlook.",
            ["pipeline", "copilot", "teams_integration", "forecasting"],
            "hybrid",
            "enterprise",
            "https://www.microsoft.com/dynamics-365/products/sales",
            "g2",
        ),
        v(
            "freshsales",
            "Freshsales (Freshworks)",
            "https://www.freshworks.com/crm/sales/",
            ["crm-platforms"],
            "CRM PME Freshworks ; scoring leads, séquences email et Freddy AI.",
            ["lead_scoring", "email_sequences", "ai", "pipeline"],
            "hybrid",
            "smb",
            "https://www.freshworks.com/crm/sales/",
            "g2",
            hq="IN",
            fr="partial",
            regions=["IN", "US", "EU"],
        ),
        v(
            "close-crm",
            "Close",
            "https://www.close.com/",
            ["crm-platforms"],
            "CRM ventes outbound ; appels, SMS et email natifs dans le pipeline.",
            ["outbound", "calling", "sms", "pipeline"],
            "hybrid",
            "smb",
            "https://www.close.com/",
            "g2",
        ),
        v(
            "copper-crm",
            "Copper",
            "https://www.copper.com/",
            ["crm-platforms"],
            "CRM natif Google Workspace ; pipeline, automations et reporting ventes.",
            ["google_workspace", "pipeline", "automations", "reporting"],
            "hybrid",
            "smb",
            "https://www.copper.com/",
            "g2",
        ),
        v(
            "zendesk-sell",
            "Zendesk Sell",
            "https://www.zendesk.com/sell/",
            ["crm-platforms"],
            "CRM mobile-first ; pipeline visuel, séquences et intégration Zendesk Support.",
            ["mobile_crm", "pipeline", "sequences", "support_integration"],
            "hybrid",
            "mid_market",
            "https://www.zendesk.com/sell/",
            "g2",
        ),
        v(
            "insightly",
            "Insightly",
            "https://www.insightly.com/",
            ["crm-platforms"],
            "CRM + gestion projets ; relations clients, livraison et automations marketing.",
            ["crm", "project_management", "automations", "reporting"],
            "hybrid",
            "smb",
            "https://www.insightly.com/",
            "capterra",
        ),
    ],
    "marketing-automation.json": [
        v(
            "klaviyo",
            "Klaviyo",
            "https://www.klaviyo.com/",
            ["marketing-automation"],
            "Marketing automation e-commerce ; segmentation, flows et analytics ROI campagnes.",
            ["ecommerce", "segmentation", "flows", "analytics"],
            "hybrid",
            "mid_market",
            "https://www.klaviyo.com/",
            "g2",
        ),
        v(
            "omnisend",
            "Omnisend",
            "https://www.omnisend.com/",
            ["marketing-automation"],
            "Automation omnicanale e-commerce ; email, SMS, push et workflows visuels.",
            ["omnichannel", "sms", "workflows", "ecommerce"],
            "hybrid",
            "smb",
            "https://www.omnisend.com/",
            "g2",
        ),
        v(
            "braze",
            "Braze",
            "https://www.braze.com/",
            ["marketing-automation"],
            "Engagement client cross-canal ; journeys, personnalisation et analytics temps réel.",
            ["customer_engagement", "journeys", "personalization", "analytics"],
            "enterprise_quote",
            "enterprise",
            "https://www.braze.com/",
            "analyst_report",
        ),
        v(
            "iterable",
            "Iterable",
            "https://iterable.com/",
            ["marketing-automation"],
            "Plateforme growth marketing ; workflows, A/B tests et orchestration multi-canal.",
            ["workflows", "ab_testing", "cross_channel", "growth"],
            "hybrid",
            "mid_market",
            "https://iterable.com/",
            "g2",
        ),
        v(
            "lemlist",
            "lemlist",
            "https://www.lemlist.com/",
            ["marketing-automation"],
            "Outreach multicanal B2B ; séquences email/LinkedIn, personnalisation et warm-up.",
            ["outreach", "linkedin", "personalization", "sequences"],
            "hybrid",
            "smb",
            "https://www.lemlist.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "drip",
            "Drip",
            "https://www.drip.com/",
            ["marketing-automation"],
            "Marketing automation e-commerce ; tags comportementaux, workflows et segmentation avancée.",
            ["ecommerce", "behavioral_tags", "workflows", "segmentation"],
            "hybrid",
            "smb",
            "https://www.drip.com/",
            "capterra",
        ),
    ],
    "revenue-intelligence.json": [
        v(
            "revenue-io",
            "Revenue.io",
            "https://www.revenue.io/",
            ["revenue-intelligence"],
            "Revenue orchestration ; dialer, coaching appels et analytics pipeline temps réel.",
            ["dialer", "call_coaching", "pipeline_analytics", "orchestration"],
            "enterprise_quote",
            "enterprise",
            "https://www.revenue.io/",
            "g2",
        ),
        v(
            "scratchpad",
            "Scratchpad",
            "https://www.scratchpad.com/",
            ["revenue-intelligence"],
            "Workspace sales ops ; hygiene CRM, notes deal et workflows Salesforce natifs.",
            ["sales_ops", "crm_hygiene", "deal_notes", "salesforce"],
            "hybrid",
            "mid_market",
            "https://www.scratchpad.com/",
            "g2",
        ),
        v(
            "winn-ai",
            "Winn.ai",
            "https://www.winn.ai/",
            ["revenue-intelligence"],
            "Assistant IA appels vente ; capture CRM auto, coaching et suivi next steps.",
            ["call_assistant", "crm_capture", "coaching", "ai"],
            "hybrid",
            "mid_market",
            "https://www.winn.ai/",
            "crunchbase",
        ),
        v(
            "aviso",
            "Aviso",
            "https://www.aviso.com/",
            ["revenue-intelligence"],
            "Revenue intelligence IA ; forecasting, deal guidance et analytics équipes commerciales.",
            ["forecasting", "deal_guidance", "ai", "pipeline"],
            "enterprise_quote",
            "enterprise",
            "https://www.aviso.com/",
            "analyst_report",
        ),
        v(
            "ebsta",
            "Ebsta",
            "https://www.ebsta.com/",
            ["revenue-intelligence"],
            "Relationship intelligence Salesforce ; engagement contacts, sentiment et deal risk.",
            ["relationship_intelligence", "salesforce", "engagement", "deal_risk"],
            "hybrid",
            "mid_market",
            "https://www.ebsta.com/",
            "g2",
            hq="GB",
            fr="partial",
            regions=["GB", "EU", "US"],
        ),
        v(
            "oliv-ai",
            "Oliv AI",
            "https://www.oliv.ai/",
            ["revenue-intelligence"],
            "Copilot CRM IA ; résumés deals, prep meetings et mise à jour Salesforce automatique.",
            ["crm_copilot", "deal_summaries", "meeting_prep", "salesforce"],
            "hybrid",
            "mid_market",
            "https://www.oliv.ai/",
            "crunchbase",
        ),
    ],
    "seo-content-ai.json": [
        v(
            "semrush",
            "Semrush",
            "https://www.semrush.com/",
            ["seo-content-ai"],
            "Suite SEO/SEM ; audit technique, recherche mots-clés et content marketing IA.",
            ["seo_audit", "keyword_research", "content_marketing", "ai_writing"],
            "hybrid",
            "mid_market",
            "https://www.semrush.com/",
            "g2",
        ),
        v(
            "ahrefs",
            "Ahrefs",
            "https://ahrefs.com/",
            ["seo-content-ai"],
            "Outil SEO complet ; backlinks, audit site et recherche contenu concurrentiel.",
            ["backlinks", "site_audit", "competitive_research", "content"],
            "hybrid",
            "mid_market",
            "https://ahrefs.com/",
            "g2",
            hq="SG",
            fr="partial",
            regions=["SG", "US", "EU"],
        ),
        v(
            "frase-io",
            "Frase",
            "https://www.frase.io/",
            ["seo-content-ai"],
            "Content SEO IA ; briefs, optimisation SERP et génération outlines research-driven.",
            ["content_briefs", "serp_optimization", "ai_outlines", "research"],
            "hybrid",
            "smb",
            "https://www.frase.io/",
            "g2",
        ),
        v(
            "scalenut",
            "Scalenut",
            "https://www.scalenut.com/",
            ["seo-content-ai"],
            "Plateforme contenu SEO IA ; clustering mots-clés, rédaction et optimisation on-page.",
            ["keyword_clustering", "ai_writing", "on_page_seo", "content_planning"],
            "hybrid",
            "smb",
            "https://www.scalenut.com/",
            "g2",
            hq="IN",
            fr="partial",
            regions=["IN", "US", "EU"],
        ),
        v(
            "neuroflash",
            "Neuroflash",
            "https://neuroflash.com/",
            ["seo-content-ai"],
            "Rédaction marketing IA EU ; SEO, brand voice et génération contenu multilingue.",
            ["ai_writing", "seo", "brand_voice", "multilingual"],
            "hybrid",
            "smb",
            "https://neuroflash.com/",
            "geo_digest",
            hq="DE",
            fr="partial",
            regions=["DE", "EU"],
        ),
        v(
            "writesonic",
            "Writesonic",
            "https://writesonic.com/",
            ["seo-content-ai"],
            "Génération contenu IA ; articles SEO, landing pages et optimisation ChatGPT-style.",
            ["ai_writing", "seo_articles", "landing_pages", "content_optimization"],
            "hybrid",
            "smb",
            "https://writesonic.com/",
            "g2",
            hq="IN",
            fr="partial",
            regions=["IN", "US", "EU"],
        ),
    ],
    "customer-success.json": [
        v(
            "vitally",
            "Vitally",
            "https://www.vitally.io/",
            ["customer-success"],
            "CS platform B2B SaaS ; health scores, playbooks et analytics rétention.",
            ["health_scores", "playbooks", "retention_analytics", "b2b_saas"],
            "hybrid",
            "mid_market",
            "https://www.vitally.io/",
            "g2",
        ),
        v(
            "custify",
            "Custify",
            "https://www.custify.com/",
            ["customer-success"],
            "Customer success automation ; onboarding, health monitoring et churn prevention.",
            ["onboarding", "health_monitoring", "churn_prevention", "automation"],
            "hybrid",
            "smb",
            "https://www.custify.com/",
            "capterra",
        ),
        v(
            "rocketlane",
            "Rocketlane",
            "https://www.rocketlane.com/",
            ["customer-success"],
            "Onboarding client collaboratif ; timelines, portails et visibilité implémentation.",
            ["onboarding", "client_portals", "timelines", "implementation"],
            "hybrid",
            "mid_market",
            "https://www.rocketlane.com/",
            "g2",
        ),
        v(
            "churnkey",
            "Churnkey",
            "https://www.churnkey.co/",
            ["customer-success"],
            "Réduction churn SaaS ; offres rétention, exit surveys et analytics cancel flow.",
            ["churn_reduction", "retention_offers", "exit_surveys", "cancel_flow"],
            "hybrid",
            "smb",
            "https://www.churnkey.co/",
            "crunchbase",
        ),
        v(
            "northpass",
            "Northpass",
            "https://www.northpass.com/",
            ["customer-success"],
            "Academy client B2B ; formation produit, certifications et analytics engagement.",
            ["customer_education", "certifications", "engagement_analytics", "academy"],
            "hybrid",
            "mid_market",
            "https://www.northpass.com/",
            "g2",
        ),
        v(
            "strikedeck",
            "Strikedeck",
            "https://www.strikedeck.com/",
            ["customer-success"],
            "CS ops platform ; intégrations data warehouse, health scores et workflows success.",
            ["cs_ops", "data_warehouse", "health_scores", "workflows"],
            "enterprise_quote",
            "enterprise",
            "https://www.strikedeck.com/",
            "analyst_report",
        ),
    ],
    "helpdesk-platforms.json": [
        v(
            "zendesk-support",
            "Zendesk Support",
            "https://www.zendesk.com/service/",
            ["helpdesk-platforms"],
            "Helpdesk leader ; ticketing omnicanal, AI agents et base connaissances.",
            ["ticketing", "omnichannel", "ai_agents", "knowledge_base"],
            "hybrid",
            "mid_market",
            "https://www.zendesk.com/service/",
            "g2",
        ),
        v(
            "intercom",
            "Intercom",
            "https://www.intercom.com/",
            ["helpdesk-platforms"],
            "Support client conversationnel ; inbox, Fin AI agent et produit tours in-app.",
            ["messenger", "ai_agent", "inbox", "product_tours"],
            "hybrid",
            "mid_market",
            "https://www.intercom.com/",
            "g2",
            hq="IE",
            fr="partial",
            regions=["IE", "US", "EU"],
        ),
        v(
            "servicenow-csm",
            "ServiceNow CSM",
            "https://www.servicenow.com/products/customer-service-management.html",
            ["helpdesk-platforms"],
            "CSM enterprise ; workflows ITSM-adjacent, portails self-service et AI Now Assist.",
            ["csm", "workflows", "self_service", "ai_assist"],
            "enterprise_quote",
            "enterprise",
            "https://www.servicenow.com/products/customer-service-management.html",
            "analyst_report",
        ),
        v(
            "zoho-desk",
            "Zoho Desk",
            "https://www.zoho.com/desk/",
            ["helpdesk-platforms"],
            "Helpdesk PME ; ticketing, Zia AI et intégration écosystème Zoho CRM.",
            ["ticketing", "zia_ai", "zoho_integration", "knowledge_base"],
            "hybrid",
            "smb",
            "https://www.zoho.com/desk/",
            "capterra",
            hq="IN",
            fr="partial",
            regions=["IN", "US", "EU"],
        ),
        v(
            "deskpro",
            "Deskpro",
            "https://www.deskpro.com/",
            ["helpdesk-platforms"],
            "Helpdesk flexible ; on-premise ou cloud, multibrand et automations tickets.",
            ["multibrand", "automations", "on_premise", "ticketing"],
            "hybrid",
            "mid_market",
            "https://www.deskpro.com/",
            "g2",
            hq="GB",
            fr="partial",
            regions=["GB", "EU", "US"],
        ),
        v(
            "gorgias",
            "Gorgias",
            "https://www.gorgias.com/",
            ["helpdesk-platforms"],
            "Helpdesk e-commerce ; Shopify, automations macros et support omnicanal D2C.",
            ["ecommerce", "shopify", "macros", "omnichannel"],
            "hybrid",
            "smb",
            "https://www.gorgias.com/",
            "g2",
            hq="FR",
            fr="strong",
            geo="france",
        ),
    ],
    "e-signature.json": [
        v(
            "signaturit",
            "Signaturit",
            "https://www.signaturit.com/",
            ["e-signature"],
            "Signature électronique EU ; eIDAS, workflows KYC et API intégration CRM.",
            ["e_signature", "eidas", "kyc", "api"],
            "hybrid",
            "mid_market",
            "https://www.signaturit.com/",
            "g2",
            hq="ES",
            fr="partial",
            regions=["ES", "EU"],
            notes="Complète Yousign/DocuSign — pas de doublon.",
        ),
        v(
            "universign",
            "Universign",
            "https://www.universign.com/",
            ["e-signature"],
            "Prestataire signature FR eIDAS ; certificats qualifiés et parcours signature entreprise.",
            ["e_signature", "eidas", "qualified_certificates", "enterprise"],
            "hybrid",
            "mid_market",
            "https://www.universign.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "signable",
            "Signable",
            "https://www.signable.co.uk/",
            ["e-signature"],
            "Signature électronique PME ; templates, rappels et audit trail conformité UK/EU.",
            ["e_signature", "templates", "reminders", "audit_trail"],
            "hybrid",
            "smb",
            "https://www.signable.co.uk/",
            "capterra",
            hq="GB",
            fr="partial",
            regions=["GB", "EU"],
        ),
        v(
            "signnow",
            "SignNow (airSlate)",
            "https://www.signnow.com/",
            ["e-signature"],
            "Signature documentaire mid-market ; workflows, teams et intégrations Salesforce.",
            ["e_signature", "workflows", "teams", "salesforce"],
            "hybrid",
            "mid_market",
            "https://www.signnow.com/",
            "g2",
        ),
        v(
            "getaccept",
            "GetAccept",
            "https://www.getaccept.com/",
            ["e-signature"],
            "Digital sales room ; propositions interactives, signature et tracking engagement acheteur.",
            ["digital_sales_room", "proposals", "e_signature", "buyer_engagement"],
            "hybrid",
            "mid_market",
            "https://www.getaccept.com/",
            "g2",
            hq="SE",
            fr="partial",
            regions=["SE", "EU", "US"],
        ),
        v(
            "concord",
            "Concord",
            "https://www.concordnow.com/",
            ["e-signature"],
            "CLM + signature ; négociation contrats, versioning et e-signature intégrée.",
            ["clm", "contract_negotiation", "e_signature", "versioning"],
            "hybrid",
            "mid_market",
            "https://www.concordnow.com/",
            "g2",
            hq="FR",
            fr="strong",
            geo="france",
        ),
    ],
    "translation-localization.json": [
        v(
            "transifex",
            "Transifex",
            "https://www.transifex.com/",
            ["translation-localization"],
            "TMS cloud ; workflows traduction, CI/CD strings et QA linguistique.",
            ["tms", "ci_cd", "string_management", "linguistic_qa"],
            "hybrid",
            "mid_market",
            "https://www.transifex.com/",
            "g2",
            hq="US",
            fr="partial",
        ),
        v(
            "weglot",
            "Weglot",
            "https://www.weglot.com/",
            ["translation-localization"],
            "Localisation site web FR ; traduction automatique, SEO multilingue et workflow review.",
            ["website_translation", "seo_multilingual", "auto_translate", "review"],
            "hybrid",
            "smb",
            "https://www.weglot.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "smartcat",
            "Smartcat",
            "https://www.smartcat.com/",
            ["translation-localization"],
            "Plateforme traduction IA ; marketplace linguistes, TMS et MT post-édition.",
            ["tms", "ai_translation", "marketplace", "post_editing"],
            "hybrid",
            "mid_market",
            "https://www.smartcat.com/",
            "g2",
        ),
        v(
            "poeditor",
            "POEditor",
            "https://poeditor.com/",
            ["translation-localization"],
            "Gestion traductions logiciel ; import/export formats dev, équipes et API.",
            ["software_localization", "dev_formats", "collaboration", "api"],
            "freemium",
            "smb",
            "https://poeditor.com/",
            "capterra",
            hq="RO",
            fr="partial",
            regions=["RO", "EU", "US"],
        ),
        v(
            "gridly",
            "Gridly",
            "https://www.gridly.com/",
            ["translation-localization"],
            "CMS localisation jeux/apps ; branches contenu, workflows loc et intégrations dev.",
            ["game_localization", "content_branching", "workflows", "dev_integration"],
            "hybrid",
            "mid_market",
            "https://www.gridly.com/",
            "g2",
            hq="SE",
            fr="partial",
            regions=["SE", "EU", "US"],
        ),
        v(
            "memsource",
            "Memsource (Phrase)",
            "https://cloud.memsource.com/",
            ["translation-localization"],
            "TMS enterprise Phrase ; MT, terminologie et connecteurs CMS/ERP.",
            ["tms", "machine_translation", "terminology", "connectors"],
            "enterprise_quote",
            "enterprise",
            "https://cloud.memsource.com/",
            "analyst_report",
            hq="CZ",
            fr="partial",
            regions=["CZ", "EU", "US"],
        ),
    ],
    "data-integration-etl.json": [
        v(
            "matillion",
            "Matillion",
            "https://www.matillion.com/",
            ["data-integration-etl"],
            "ETL cloud-native ; pipelines visuels Snowflake/BigQuery/Databricks et orchestration.",
            ["etl", "cloud_warehouse", "visual_pipelines", "orchestration"],
            "hybrid",
            "mid_market",
            "https://www.matillion.com/",
            "g2",
            hq="GB",
            fr="partial",
            regions=["GB", "EU", "US"],
        ),
        v(
            "informatica-cloud",
            "Informatica Cloud",
            "https://www.informatica.com/products/cloud-data-integration.html",
            ["data-integration-etl"],
            "iPaaS enterprise ; intégration cloud/on-prem, qualité données et gouvernance.",
            ["ipaas", "data_quality", "governance", "hybrid_integration"],
            "enterprise_quote",
            "enterprise",
            "https://www.informatica.com/products/cloud-data-integration.html",
            "analyst_report",
        ),
        v(
            "talend-cloud",
            "Talend Cloud",
            "https://www.talend.com/products/cloud-data-integration/",
            ["data-integration-etl"],
            "Intégration données Qlik ; ETL/ELT, API management et data fabric.",
            ["etl", "elt", "api_management", "data_fabric"],
            "hybrid",
            "enterprise",
            "https://www.talend.com/products/cloud-data-integration/",
            "g2",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "portable-io",
            "Portable",
            "https://portable.io/",
            ["data-integration-etl"],
            "Connecteurs SaaS long-tail ; ELT vers entrepôts et sync APIs métier.",
            ["connectors", "elt", "saas_sync", "long_tail"],
            "hybrid",
            "mid_market",
            "https://portable.io/",
            "crunchbase",
        ),
        v(
            "dagster",
            "Dagster",
            "https://dagster.io/",
            ["data-integration-etl"],
            "Orchestrateur data assets ; pipelines Python, observabilité lineage et tests.",
            ["orchestration", "python_pipelines", "lineage", "data_assets"],
            "hybrid",
            "mid_market",
            "https://dagster.io/",
            "open_source",
        ),
        v(
            "census",
            "Census (Reverse ETL)",
            "https://www.getcensus.com/",
            ["data-integration-etl"],
            "Reverse ETL ; sync entrepôt vers CRM/support/marketing sans code.",
            ["reverse_etl", "warehouse_sync", "crm_sync", "no_code"],
            "hybrid",
            "mid_market",
            "https://www.getcensus.com/",
            "g2",
        ),
    ],
    "data-enrichment-b2b.json": [
        v(
            "6sense",
            "6sense",
            "https://6sense.com/",
            ["data-enrichment-b2b"],
            "ABM intent data ; identification comptes anonymes, scoring intent et orchestration.",
            ["abm", "intent_data", "account_identification", "orchestration"],
            "enterprise_quote",
            "enterprise",
            "https://6sense.com/",
            "analyst_report",
        ),
        v(
            "demandbase",
            "Demandbase",
            "https://www.demandbase.com/",
            ["data-enrichment-b2b"],
            "ABM platform ; enrichment firmographique, intent B2B et publicité ciblée.",
            ["abm", "firmographics", "intent", "advertising"],
            "enterprise_quote",
            "enterprise",
            "https://www.demandbase.com/",
            "g2",
        ),
        v(
            "cognism",
            "Cognism",
            "https://www.cognism.com/",
            ["data-enrichment-b2b"],
            "Données contacts B2B EU ; emails vérifiés, mobile numbers et compliance GDPR.",
            ["contact_data", "verified_emails", "mobile", "gdpr"],
            "hybrid",
            "mid_market",
            "https://www.cognism.com/",
            "g2",
            hq="GB",
            fr="partial",
            regions=["GB", "EU"],
        ),
        v(
            "rocketreach",
            "RocketReach",
            "https://rocketreach.co/",
            ["data-enrichment-b2b"],
            "Recherche contacts pro ; emails, téléphones et profils LinkedIn entreprises.",
            ["contact_search", "email_finder", "linkedin", "enrichment"],
            "hybrid",
            "smb",
            "https://rocketreach.co/",
            "g2",
        ),
        v(
            "leadfeeder",
            "Leadfeeder (Dealfront)",
            "https://www.leadfeeder.com/",
            ["data-enrichment-b2b"],
            "Identification visiteurs site ; entreprises anonymes, intent et sync CRM.",
            ["visitor_identification", "intent", "crm_sync", "website_analytics"],
            "hybrid",
            "smb",
            "https://www.leadfeeder.com/",
            "g2",
            hq="FI",
            fr="partial",
            regions=["FI", "EU"],
        ),
        v(
            "dealfront",
            "Dealfront",
            "https://www.dealfront.com/",
            ["data-enrichment-b2b"],
            "Suite go-to-market EU ; Leadfeeder + Echobot enrichment firmographique DACH/EU.",
            ["gtm", "firmographics", "visitor_id", "eu_data"],
            "hybrid",
            "mid_market",
            "https://www.dealfront.com/",
            "geo_digest",
            hq="FI",
            fr="partial",
            regions=["FI", "EU"],
        ),
    ],
    "bi-analytics-platforms.json": [
        v(
            "qlik-sense",
            "Qlik Sense",
            "https://www.qlik.com/us/products/qlik-sense",
            ["bi-analytics-platforms"],
            "BI associative ; dashboards, alerting et intégration Talend/Qlik data pipeline.",
            ["associative_bi", "dashboards", "alerting", "data_integration"],
            "hybrid",
            "enterprise",
            "https://www.qlik.com/us/products/qlik-sense",
            "g2",
            hq="SE",
            fr="partial",
            regions=["SE", "EU", "US"],
        ),
        v(
            "domo",
            "Domo",
            "https://www.domo.com/",
            ["bi-analytics-platforms"],
            "BI cloud ; connecteurs 1000+, dashboards exécutifs et alerting mobile.",
            ["cloud_bi", "connectors", "executive_dashboards", "mobile"],
            "enterprise_quote",
            "enterprise",
            "https://www.domo.com/",
            "g2",
        ),
        v(
            "sisense",
            "Sisense",
            "https://www.sisense.com/",
            ["bi-analytics-platforms"],
            "Analytics embarqué ; modélisation, dashboards white-label et API analytics.",
            ["embedded_analytics", "modeling", "white_label", "api"],
            "hybrid",
            "mid_market",
            "https://www.sisense.com/",
            "g2",
            hq="IL",
            fr="partial",
            regions=["IL", "US", "EU"],
        ),
        v(
            "metabase",
            "Metabase",
            "https://www.metabase.com/",
            ["bi-analytics-platforms"],
            "BI open source ; questions SQL/no-code, dashboards et embedding self-hosted.",
            ["open_source", "sql", "dashboards", "embedding"],
            "freemium",
            "smb",
            "https://www.metabase.com/",
            "open_source",
        ),
        v(
            "hex-tech",
            "Hex",
            "https://hex.tech/",
            ["bi-analytics-platforms"],
            "Notebook analytics collaboratif ; Python/SQL, apps data et partage équipes.",
            ["notebooks", "python_sql", "data_apps", "collaboration"],
            "hybrid",
            "mid_market",
            "https://hex.tech/",
            "crunchbase",
        ),
        v(
            "sigma-computing",
            "Sigma Computing",
            "https://www.sigmacomputing.com/",
            ["bi-analytics-platforms"],
            "Spreadsheet BI cloud ; exploration warehouse live, gouvernance et dashboards.",
            ["spreadsheet_bi", "warehouse_live", "governance", "dashboards"],
            "hybrid",
            "mid_market",
            "https://www.sigmacomputing.com/",
            "g2",
        ),
    ],
    "data-observability.json": [
        v(
            "bigeye",
            "Bigeye",
            "https://www.bigeye.com/",
            ["data-observability"],
            "Observabilité qualité données ; métriques auto, alerting et root cause analysis.",
            ["data_quality", "auto_metrics", "alerting", "root_cause"],
            "hybrid",
            "mid_market",
            "https://www.bigeye.com/",
            "g2",
        ),
        v(
            "elementary-data",
            "Elementary",
            "https://www.elementary-data.com/",
            ["data-observability"],
            "Observabilité dbt-native ; tests, anomalies et lineage dans le stack analytics.",
            ["dbt", "anomaly_detection", "lineage", "data_tests"],
            "freemium",
            "mid_market",
            "https://www.elementary-data.com/",
            "open_source",
            hq="IL",
            fr="partial",
            regions=["IL", "EU", "US"],
        ),
        v(
            "sifflet",
            "Sifflet",
            "https://www.siffletdata.com/",
            ["data-observability"],
            "Data observability EU ; catalog, monitoring qualité et impact analysis pipelines.",
            ["catalog", "quality_monitoring", "impact_analysis", "pipelines"],
            "hybrid",
            "mid_market",
            "https://www.siffletdata.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "datafold",
            "Datafold",
            "https://www.datafold.com/",
            ["data-observability"],
            "Data diff & CI ; comparaison prod/staging, regression tests et column-level lineage.",
            ["data_diff", "ci_cd", "regression_tests", "lineage"],
            "hybrid",
            "mid_market",
            "https://www.datafold.com/",
            "crunchbase",
        ),
        v(
            "lightup",
            "Lightup",
            "https://www.lightup.ai/",
            ["data-observability"],
            "Monitoring données temps réel ; détection anomalies, SLA et alerting incident.",
            ["real_time_monitoring", "anomaly_detection", "sla", "incident_alerting"],
            "hybrid",
            "mid_market",
            "https://www.lightup.ai/",
            "crunchbase",
        ),
        v(
            "lakefs",
            "lakeFS",
            "https://lakefs.io/",
            ["data-observability"],
            "Versioning data lake ; branches, commits et rollback datasets type Git.",
            ["data_versioning", "git_for_data", "branches", "rollback"],
            "freemium",
            "mid_market",
            "https://lakefs.io/",
            "open_source",
            hq="IL",
            fr="partial",
            regions=["IL", "US", "EU"],
        ),
    ],
    "rag-knowledge.json": [
        v(
            "onyx-enterprise",
            "Onyx (Danswer)",
            "https://www.onyx.app/",
            ["rag-knowledge"],
            "Enterprise search open source ; RAG interne, connecteurs docs et chat grounded.",
            ["enterprise_search", "rag", "connectors", "open_source"],
            "freemium",
            "mid_market",
            "https://www.onyx.app/",
            "open_source",
        ),
        v(
            "kapa-ai",
            "kapa.ai",
            "https://www.kapa.ai/",
            ["rag-knowledge"],
            "Support docs RAG ; chatbot grounded sur docs produit, analytics gaps et API.",
            ["docs_rag", "product_chatbot", "gap_analytics", "api"],
            "hybrid",
            "mid_market",
            "https://www.kapa.ai/",
            "crunchbase",
        ),
        v(
            "ragie",
            "Ragie",
            "https://www.ragie.ai/",
            ["rag-knowledge"],
            "RAG-as-a-service ; ingestion multimédia, chunking et API retrieval enterprise.",
            ["rag_api", "multimedia_ingestion", "chunking", "retrieval"],
            "hybrid",
            "mid_market",
            "https://www.ragie.ai/",
            "crunchbase",
        ),
        v(
            "guru",
            "Guru",
            "https://www.getguru.com/",
            ["rag-knowledge"],
            "Knowledge management ; wiki entreprise, vérification contenu et suggestions contextuelles.",
            ["knowledge_base", "verification", "contextual_suggestions", "wiki"],
            "hybrid",
            "mid_market",
            "https://www.getguru.com/",
            "g2",
        ),
        v(
            "bloomfire",
            "Bloomfire",
            "https://bloomfire.com/",
            ["rag-knowledge"],
            "Knowledge engagement ; recherche IA, Q&A communautaire et analytics usage contenu.",
            ["ai_search", "community_qa", "content_analytics", "engagement"],
            "hybrid",
            "mid_market",
            "https://bloomfire.com/",
            "g2",
        ),
        v(
            "elastic-enterprise-search",
            "Elastic Enterprise Search",
            "https://www.elastic.co/enterprise-search",
            ["rag-knowledge"],
            "Recherche enterprise Elastic ; connecteurs, relevance tuning et RAG via vector search.",
            ["enterprise_search", "vector_search", "connectors", "relevance"],
            "hybrid",
            "enterprise",
            "https://www.elastic.co/enterprise-search",
            "official_site",
            hq="NL",
            fr="partial",
            regions=["NL", "EU", "US"],
        ),
    ],
    "ai-productivity.json": [
        v(
            "motion-app",
            "Motion",
            "https://www.usemotion.com/",
            ["ai-productivity"],
            "Calendrier IA ; planification auto tâches, priorités et réunion scheduling intelligent.",
            ["ai_scheduling", "task_prioritization", "calendar", "automation"],
            "hybrid",
            "smb",
            "https://www.usemotion.com/",
            "g2",
        ),
        v(
            "reclaim-ai",
            "Reclaim.ai",
            "https://reclaim.ai/",
            ["ai-productivity"],
            "Optimisation calendrier ; habits, focus time et scheduling équipes Google/Outlook.",
            ["calendar_optimization", "focus_time", "habits", "team_scheduling"],
            "freemium",
            "smb",
            "https://reclaim.ai/",
            "g2",
        ),
        v(
            "tango-us",
            "Tango",
            "https://www.tango.us/",
            ["ai-productivity"],
            "Documentation processus auto ; captures écran, guides step-by-step et partage équipe.",
            ["process_docs", "screenshots", "step_by_step", "team_sharing"],
            "freemium",
            "smb",
            "https://www.tango.us/",
            "g2",
        ),
        v(
            "beautiful-ai",
            "Beautiful.ai",
            "https://www.beautiful.ai/",
            ["ai-productivity"],
            "Présentations IA ; templates smart, design auto et collaboration slides.",
            ["presentations", "smart_templates", "auto_design", "collaboration"],
            "hybrid",
            "smb",
            "https://www.beautiful.ai/",
            "g2",
        ),
        v(
            "tome-app",
            "Tome",
            "https://tome.app/",
            ["ai-productivity"],
            "Storytelling IA ; decks narratifs, génération contenu et partage interactif.",
            ["ai_decks", "storytelling", "content_generation", "sharing"],
            "hybrid",
            "smb",
            "https://tome.app/",
            "crunchbase",
        ),
        v(
            "mem-ai",
            "Mem",
            "https://mem.ai/",
            ["ai-productivity"],
            "Notes IA self-organizing ; recherche sémantique, rappels contextuels et team workspace.",
            ["ai_notes", "semantic_search", "contextual_reminders", "workspace"],
            "hybrid",
            "smb",
            "https://mem.ai/",
            "crunchbase",
        ),
    ],
    "project-work-management.json": [
        v(
            "smartsheet",
            "Smartsheet",
            "https://www.smartsheet.com/",
            ["project-work-management"],
            "Work management enterprise ; grilles, Gantt, automations et portefeuilles projets.",
            ["grids", "gantt", "automations", "portfolio"],
            "hybrid",
            "enterprise",
            "https://www.smartsheet.com/",
            "g2",
        ),
        v(
            "basecamp",
            "Basecamp",
            "https://basecamp.com/",
            ["project-work-management"],
            "Gestion projet simplifiée ; to-do, message boards et calendrier équipe tout-en-un.",
            ["todo", "message_boards", "team_calendar", "simplicity"],
            "hybrid",
            "smb",
            "https://basecamp.com/",
            "capterra",
        ),
        v(
            "height-app",
            "Height",
            "https://height.app/",
            ["project-work-management"],
            "Project tracker moderne ; vues flexibles, automations et intégrations dev/design.",
            ["flexible_views", "automations", "dev_integration", "tracking"],
            "hybrid",
            "smb",
            "https://height.app/",
            "crunchbase",
        ),
        v(
            "teamwork-com",
            "Teamwork.com",
            "https://www.teamwork.com/",
            ["project-work-management"],
            "PM agences/services ; time tracking, budgets client et collaboration projets.",
            ["time_tracking", "client_budgets", "collaboration", "agency"],
            "hybrid",
            "mid_market",
            "https://www.teamwork.com/",
            "g2",
            hq="IE",
            fr="partial",
            regions=["IE", "EU", "US"],
        ),
        v(
            "airtable",
            "Airtable",
            "https://www.airtable.com/",
            ["project-work-management"],
            "Work OS flexible ; bases relationnelles, interfaces et automations no-code.",
            ["relational_bases", "interfaces", "automations", "no_code"],
            "freemium",
            "mid_market",
            "https://www.airtable.com/",
            "g2",
        ),
        v(
            "todoist-business",
            "Todoist Business",
            "https://todoist.com/team",
            ["project-work-management"],
            "Task management équipes ; projets partagés, labels, filtres et productivité personnelle.",
            ["task_management", "shared_projects", "labels", "productivity"],
            "freemium",
            "smb",
            "https://todoist.com/team",
            "capterra",
            hq="PT",
            fr="partial",
            regions=["PT", "EU", "US"],
        ),
    ],
    "meeting-intelligence.json": [
        v(
            "tldv",
            "tl;dv",
            "https://tldv.io/",
            ["meeting-intelligence"],
            "Enregistrement réunions ; highlights, clips partageables et intégrations CRM.",
            ["recording", "highlights", "clips", "crm_integration"],
            "freemium",
            "smb",
            "https://tldv.io/",
            "g2",
            hq="DE",
            fr="partial",
            regions=["DE", "EU"],
        ),
        v(
            "sembly",
            "Sembly AI",
            "https://www.sembly.ai/",
            ["meeting-intelligence"],
            "Transcription et insights réunions ; action items, sentiment et search meetings.",
            ["transcription", "action_items", "sentiment", "meeting_search"],
            "hybrid",
            "mid_market",
            "https://www.sembly.ai/",
            "g2",
        ),
        v(
            "supernormal",
            "Supernormal",
            "https://supernormal.com/",
            ["meeting-intelligence"],
            "Notes réunion auto ; templates, sync CRM et partage équipe post-call.",
            ["auto_notes", "templates", "crm_sync", "team_sharing"],
            "hybrid",
            "smb",
            "https://supernormal.com/",
            "crunchbase",
        ),
        v(
            "meetgeek",
            "MeetGeek",
            "https://meetgeek.ai/",
            ["meeting-intelligence"],
            "Meeting assistant ; résumés IA, KPI réunions et intégrations Slack/Notion.",
            ["ai_summaries", "meeting_kpi", "slack", "notion"],
            "hybrid",
            "smb",
            "https://meetgeek.ai/",
            "g2",
        ),
        v(
            "circleback",
            "Circleback",
            "https://www.circleback.ai/",
            ["meeting-intelligence"],
            "Automatisation follow-up ; notes, emails recap et CRM updates post-réunion.",
            ["follow_up", "recap_emails", "crm_updates", "automation"],
            "hybrid",
            "smb",
            "https://www.circleback.ai/",
            "crunchbase",
        ),
        v(
            "krisp-meetings",
            "Krisp",
            "https://krisp.ai/",
            ["meeting-intelligence"],
            "Audio AI réunions ; suppression bruit, transcription et accent localization.",
            ["noise_cancellation", "transcription", "accent_localization", "audio_ai"],
            "freemium",
            "smb",
            "https://krisp.ai/",
            "g2",
        ),
    ],
    "rpa-enterprise.json": [
        v(
            "kryon-rpa",
            "Kryon (Nintex RPA)",
            "https://www.nintex.com/platform/rpa/",
            ["rpa-enterprise"],
            "RPA enterprise ; discovery processus, bots attended/unattended et analytics ROI.",
            ["process_discovery", "attended_bots", "unattended_bots", "roi_analytics"],
            "enterprise_quote",
            "enterprise",
            "https://www.nintex.com/platform/rpa/",
            "analyst_report",
            hq="IL",
            fr="partial",
            regions=["IL", "EU", "US"],
        ),
        v(
            "pegasystems",
            "Pega",
            "https://www.pega.com/products/platform",
            ["rpa-enterprise"],
            "Platform BPM + RPA ; case management, decisioning IA et automation end-to-end.",
            ["bpm", "rpa", "case_management", "ai_decisioning"],
            "enterprise_quote",
            "enterprise",
            "https://www.pega.com/products/platform",
            "analyst_report",
        ),
        v(
            "robocorp",
            "Robocorp",
            "https://robocorp.com/",
            ["rpa-enterprise"],
            "RPA developer-first ; robots Python, orchestration cloud et CI/CD bots.",
            ["python_rpa", "cloud_orchestration", "ci_cd", "developer_first"],
            "hybrid",
            "mid_market",
            "https://robocorp.com/",
            "open_source",
            hq="FI",
            fr="partial",
            regions=["FI", "EU", "US"],
        ),
        v(
            "appian-rpa",
            "Appian RPA",
            "https://appian.com/products/platform/rpa",
            ["rpa-enterprise"],
            "Low-code + RPA intégré ; workflows, IDP et orchestration processus métier.",
            ["low_code", "rpa", "idp", "process_orchestration"],
            "enterprise_quote",
            "enterprise",
            "https://appian.com/products/platform/rpa",
            "g2",
        ),
        v(
            "electroneek",
            "ElectroNeek",
            "https://electroneek.com/",
            ["rpa-enterprise"],
            "RPA MSP-friendly ; studio no-code, orchestrateur et modèle partenaires intégrateurs.",
            ["no_code_studio", "orchestrator", "msp", "integrators"],
            "hybrid",
            "smb",
            "https://electroneek.com/",
            "g2",
        ),
        v(
            "nice-rpa",
            "NICE RPA",
            "https://www.nice.com/products/automation/",
            ["rpa-enterprise"],
            "Hyperautomation NICE ; RPA, attended automation et analytics processus contact center.",
            ["rpa", "attended_automation", "contact_center", "process_analytics"],
            "enterprise_quote",
            "enterprise",
            "https://www.nice.com/products/automation/",
            "analyst_report",
            hq="IL",
            fr="partial",
            regions=["IL", "EU", "US"],
        ),
    ],
    "spend-procurement.json": [
        v(
            "sap-ariba",
            "SAP Ariba",
            "https://www.ariba.com/",
            ["spend-procurement"],
            "Procurement network enterprise ; sourcing, e-procurement et supplier management global.",
            ["sourcing", "e_procurement", "supplier_management", "network"],
            "enterprise_quote",
            "enterprise",
            "https://www.ariba.com/",
            "analyst_report",
            hq="DE",
            fr="partial",
            regions=["DE", "EU", "US"],
        ),
        v(
            "ivalua",
            "Ivalua",
            "https://www.ivalua.com/",
            ["spend-procurement"],
            "Suite source-to-pay ; achats directs/indirects, contrats et analytics spend FR/EU.",
            ["source_to_pay", "spend_analytics", "contracts", "supplier_collaboration"],
            "enterprise_quote",
            "enterprise",
            "https://www.ivalua.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "jaggaer",
            "JAGGAER",
            "https://www.jaggaer.com/",
            ["spend-procurement"],
            "Procurement verticalisé ; sourcing, e-invoicing et compliance achats secteur public/privé.",
            ["sourcing", "e_invoicing", "compliance", "vertical"],
            "enterprise_quote",
            "enterprise",
            "https://www.jaggaer.com/",
            "analyst_report",
        ),
        v(
            "proactis",
            "Proactis",
            "https://www.proactis.com/",
            ["spend-procurement"],
            "Spend management mid-market ; achats, factures fournisseurs et contrôle budgets.",
            ["spend_management", "supplier_invoices", "budget_control", "mid_market"],
            "hybrid",
            "mid_market",
            "https://www.proactis.com/",
            "g2",
            hq="GB",
            fr="partial",
            regions=["GB", "EU"],
        ),
        v(
            "gep-smart",
            "GEP SMART",
            "https://www.gep.com/software/gep-smart-procurement-software",
            ["spend-procurement"],
            "Procurement cloud unified ; sourcing, P2P, analytics spend et supplier risk.",
            ["p2p", "sourcing", "spend_analytics", "supplier_risk"],
            "enterprise_quote",
            "enterprise",
            "https://www.gep.com/software/gep-smart-procurement-software",
            "analyst_report",
            hq="US",
            fr="partial",
        ),
        v(
            "zycus",
            "Zycus",
            "https://www.zycus.com/",
            ["spend-procurement"],
            "Source-to-pay IA ; cognitive procurement, contract management et savings tracking.",
            ["source_to_pay", "cognitive_procurement", "contract_management", "savings"],
            "enterprise_quote",
            "enterprise",
            "https://www.zycus.com/",
            "g2",
            hq="US",
            fr="partial",
        ),
    ],
}

SEGMENT_PATCHES: dict[str, list[str]] = {
    "laiye": ["rpa-enterprise"],
}

COVERAGE_UPDATES: dict[str, dict[str, dict]] = {
    "crm-platforms": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 4, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
    },
    "marketing-automation": {
        "g2": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "revenue-intelligence": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "seo-content-ai": {
        "g2": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 5, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "customer-success": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 4, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "helpdesk-platforms": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 5, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "e-signature": {
        "g2": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 2, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "translation-localization": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "data-integration-etl": {
        "g2": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 3, "pass": PASS_ID},
        "open_source": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "data-enrichment-b2b": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 2, "pass": PASS_ID},
    },
    "bi-analytics-platforms": {
        "g2": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "open_source": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "data-observability": {
        "g2": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
        "open_source": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "rag-knowledge": {
        "open_source": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
        "g2": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 2, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "ai-productivity": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 2, "pass": PASS_ID},
    },
    "project-work-management": {
        "g2": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "meeting-intelligence": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 2, "pass": PASS_ID},
    },
    "rpa-enterprise": {
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 3, "pass": PASS_ID},
        "g2": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "open_source": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "spend-procurement": {
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "g2": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
    },
}


def patch_segments() -> int:
    patched = 0
    for path in VENDORS_DIR.glob("*.json"):
        data = json.loads(path.read_text(encoding="utf-8"))
        changed = False
        for vendor in data.get("vendors", []):
            extra = SEGMENT_PATCHES.get(vendor["id"])
            if not extra:
                continue
            for seg in extra:
                if seg not in vendor["segments"]:
                    vendor["segments"].append(seg)
                    changed = True
                    patched += 1
        if changed:
            data["updated_at"] = TODAY
            path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return patched


def merge() -> None:
    all_ids: set[str] = set()
    for path in VENDORS_DIR.glob("*.json"):
        for vendor in json.loads(path.read_text(encoding="utf-8")).get("vendors", []):
            all_ids.add(vendor["id"])

    total = 0
    per_file: dict[str, int] = {}
    for fname, vendors in ADDITIONS.items():
        path = VENDORS_DIR / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        count = 0
        for vendor in vendors:
            if vendor["id"] in all_ids:
                print(f"skip duplicate: {vendor['id']}")
                continue
            data["vendors"].append(vendor)
            all_ids.add(vendor["id"])
            count += 1
            total += 1
        data["updated_at"] = TODAY
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        per_file[fname] = count
        print(f"updated {fname}: +{count}")

    patched = patch_segments()
    if patched:
        print(f"segment patches: +{patched}")

    matrix = json.loads(COVERAGE.read_text(encoding="utf-8"))
    for seg_id, sources in COVERAGE_UPDATES.items():
        entry = matrix["segments"][seg_id]
        for src, upd in sources.items():
            prev = entry["sources"].get(src) or {}
            entry["sources"][src] = {
                **upd,
                "cumulative_new": prev.get("cumulative_new", prev.get("new_added", 0)) + upd["new_added"],
            }
        entry["last_pass"] = PASS_ID
        entry["vendor_count_after_pass"] = len(
            json.loads((VENDORS_DIR / f"{seg_id}.json").read_text(encoding="utf-8"))["vendors"]
        )
    matrix["updated_at"] = TODAY
    COVERAGE.write_text(json.dumps(matrix, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"done: +{total} vendors")
    for fname, n in per_file.items():
        print(f"  {fname}: +{n}")


if __name__ == "__main__":
    merge()
