#!/usr/bin/env python3
"""Vague 5t-b — L3 verticaux métiers + compliance (11→~18 vendeurs/segment)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
COVERAGE = ROOT / "catalogue-saas" / "coverage-matrix.json"
TODAY = "2026-06-23"
PASS_ID = "2026-06-v5t-verticals-l3"


def v(
    id_: str,
    name: str,
    url: str,
    segments: list[str],
    desc: str,
    caps: list[str],
    pricing: str,
    market: str,
    source: str,
    src_type: str,
    hq: str = "US",
    fr: str = "partial",
    regions: list[str] | None = None,
    geo: str = "global",
    notes: str | None = None,
) -> dict:
    d = {
        "id": id_,
        "name": name,
        "url": url,
        "segments": segments,
        "description": desc,
        "capabilities": caps,
        "pricing_model": pricing,
        "target_market": market,
        "geography": geo,
        "hq_country": hq,
        "france_market": fr,
        "operating_regions": regions or ["US", "EU"],
        "discovery_source": src_type,
        "discovery_pass": PASS_ID,
        "source_url": source,
        "source_consulted_at": TODAY,
        "verification_status": "partial",
    }
    if notes:
        d["notes"] = notes
    return d


ADDITIONS: dict[str, list[dict]] = {
    "accessibility-compliance.json": [
        v("siteimprove", "Siteimprove", "https://www.siteimprove.com/", ["accessibility-compliance"],
          "Monitoring accessibilité et qualité web ; scans WCAG, dashboards conformité et workflows remédiation.",
          ["wcag_monitoring", "accessibility_scanning", "compliance_dashboards", "remediation"], "enterprise_quote", "enterprise",
          "https://www.siteimprove.com/", "g2", hq="DK", fr="partial", regions=["US", "EU"], geo="europe"),
        v("monsido", "Monsido", "https://monsido.com/", ["accessibility-compliance"],
          "Plateforme web governance EU ; accessibilité WCAG, SEO, privacy et alertes régression multi-sites.",
          ["wcag", "web_governance", "regression_alerts", "multi_site"], "hybrid", "mid_market",
          "https://monsido.com/", "g2", hq="DK", fr="partial", regions=["US", "EU"], geo="europe"),
        v("access42", "Access 42", "https://access42.net/", ["accessibility-compliance"],
          "Expertise accessibilité FR ; audits RGAA/WCAG, formation équipes et accompagnement secteur public.",
          ["rgaa", "wcag", "audit", "training"], "hybrid", "mid_market",
          "https://access42.net/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("qualiweb", "Qualiweb", "https://www.qualiweb.net/", ["accessibility-compliance"],
          "Audit et certification accessibilité FR ; conformité RGAA, rapports et plans de mise en conformité.",
          ["rgaa", "certification", "audit_reports", "remediation_plans"], "hybrid", "mid_market",
          "https://www.qualiweb.net/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("fable", "Fable", "https://makeitfable.com/", ["accessibility-compliance"],
          "Tests utilisateurs accessibilité ; panels personnes en situation de handicap et feedback produit.",
          ["user_testing", "disability_panels", "accessibility_research", "product_feedback"], "hybrid", "mid_market",
          "https://makeitfable.com/", "g2", hq="CA", fr="partial", regions=["US", "EU"], geo="global"),
        v("equalweb", "EqualWeb", "https://www.equalweb.com/", ["accessibility-compliance"],
          "Widget accessibilité IA ; conformité WCAG/ADA, personnalisation affichage et rapports audit.",
          ["accessibility_widget", "wcag", "ai_remediation", "audit_reports"], "hybrid", "smb",
          "https://www.equalweb.com/", "g2", hq="IL", fr="partial", regions=["US", "EU"], geo="global"),
        v("access-for-all", "Access for All", "https://www.access-for-all.com/", ["accessibility-compliance"],
          "Consulting et outils accessibilité FR ; audits RGAA, sensibilisation et veille réglementaire EU.",
          ["rgaa", "consulting", "awareness", "regulatory_watch"], "hybrid", "mid_market",
          "https://www.access-for-all.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
    ],
    "construction-proptech.json": [
        v("archilogic", "Archilogic", "https://archilogic.com/", ["construction-proptech"],
          "Plans 3D interactifs ; digital twin bâtiments, visites virtuelles et intégration BIM léger.",
          ["3d_plans", "digital_twin", "virtual_tours", "bim_light"], "hybrid", "mid_market",
          "https://archilogic.com/", "crunchbase", hq="CH", fr="partial", regions=["US", "EU"], geo="europe"),
        v("bimtrack", "BIM Track", "https://bimtrack.co/", ["construction-proptech"],
          "Coordination BIM cloud ; issues BCF, suivi clashes et collaboration maîtrise d'œuvre/chantier.",
          ["bim_coordination", "bcf", "clash_tracking", "cloud_collaboration"], "hybrid", "mid_market",
          "https://bimtrack.co/", "g2", hq="CA", fr="partial", regions=["US", "EU"], geo="global"),
        v("ibat", "iBAT", "https://www.ibat.com/", ["construction-proptech"],
          "Achats BTP FR ; marketplace matériaux, devis chantier et pilotage dépenses sous-traitants.",
          ["construction_procurement", "marketplace", "quotes", "spend_control"], "hybrid", "mid_market",
          "https://www.ibat.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("helyx", "Helyx", "https://www.helyx.io/", ["construction-proptech"],
          "Gestion chantier mobile FR ; suivi avancement, photos terrain et rapports maîtrise d'ouvrage.",
          ["field_management", "progress_tracking", "photo_reports", "mobile"], "hybrid", "mid_market",
          "https://www.helyx.io/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("planbim", "Plan BIM", "https://www.plan-bim.fr/", ["construction-proptech"],
          "Accompagnement BIM FR ; formation, maquettes numériques et conformité référentiels construction.",
          ["bim_training", "digital_models", "compliance", "consulting"], "hybrid", "mid_market",
          "https://www.plan-bim.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("trimble-connect", "Trimble Connect", "https://connect.trimble.com/", ["construction-proptech"],
          "Collaboration BIM Trimble ; modèles 3D, workflows construction et intégration écosystème Trimble.",
          ["bim_collaboration", "3d_models", "construction_workflows", "trimble_ecosystem"], "hybrid", "enterprise",
          "https://connect.trimble.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("inovva", "Inovva", "https://www.inovva.fr/", ["construction-proptech"],
          "Plateforme données chantier FR ; jumeau numérique, capteurs IoT et analytics performance BTP.",
          ["digital_twin", "iot_sensors", "construction_analytics", "performance"], "hybrid", "mid_market",
          "https://www.inovva.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
    ],
    "insurance-insurtech.json": [
        v("zelros", "Zelros", "https://www.zelros.com/", ["insurance-insurtech"],
          "IA recommandation assurance FR ; cross-sell, personnalisation produits et analytics portefeuille.",
          ["ai_recommendations", "cross_sell", "product_personalization", "portfolio_analytics"], "enterprise_quote", "enterprise",
          "https://www.zelros.com/", "crunchbase", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("descartes-underwriting", "Descartes Underwriting", "https://www.descartesunderwriting.com/", ["insurance-insurtech"],
          "Assurance paramétrique climat FR ; couverture risques naturels, agriculture et analytics météo.",
          ["parametric_insurance", "climate_risk", "agriculture", "weather_analytics"], "enterprise_quote", "enterprise",
          "https://www.descartesunderwriting.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="global"),
        v("insly", "Insly", "https://insly.com/", ["insurance-insurtech"],
          "Plateforme insurance software EU ; policy admin, billing et distribution white-label MGA/brokers.",
          ["policy_admin", "billing", "white_label", "mga"], "hybrid", "mid_market",
          "https://insly.com/", "g2", hq="EE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("insify", "Insify", "https://insify.com/", ["insurance-insurtech"],
          "Assurance PME digital EU ; souscription en ligne, couvertures modularisées et gestion sinistres.",
          ["sme_insurance", "online_underwriting", "modular_coverage", "claims"], "hybrid", "smb",
          "https://insify.com/", "crunchbase", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("iptiq", "iptiQ (Swiss Re)", "https://www.iptiq.com/", ["insurance-insurtech"],
          "Assurance white-label EU ; produits embarqués, APIs distribution et gestion risques digital.",
          ["white_label", "embedded_insurance", "api_distribution", "digital_risk"], "enterprise_quote", "enterprise",
          "https://www.iptiq.com/", "analyst_report", hq="CH", fr="partial", regions=["US", "EU"], geo="europe"),
        v("neodigital", "Neodigital", "https://www.neodigital.fr/", ["insurance-insurtech"],
          "Courtage assurance digital FR ; comparaison, souscription en ligne et gestion contrats PME/particuliers.",
          ["digital_broker", "comparison", "online_subscription", "contract_management"], "hybrid", "smb",
          "https://www.neodigital.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("assurup", "Assurup", "https://www.assurup.com/", ["insurance-insurtech"],
          "Distribution assurance embarquée FR ; APIs produits, parcours souscription et gestion partenaires.",
          ["embedded_insurance", "api", "partner_management", "subscription"], "hybrid", "mid_market",
          "https://www.assurup.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("inspeer", "Inspeer", "https://www.inspeer.fr/", ["insurance-insurtech"],
          "Assurance collaborative FR ; mutuelles digitales, gestion adhérents et produits sur-mesure collectifs.",
          ["collaborative_insurance", "digital_mutual", "member_management", "custom_products"], "hybrid", "mid_market",
          "https://www.inspeer.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
    ],
    "retail-ecommerce-ai.json": [
        v("iadvize", "iAdvize", "https://www.iadvize.com/", ["retail-ecommerce-ai"],
          "Conversational commerce FR ; chatbot IA, copilot agents et personnalisation parcours e-commerce.",
          ["conversational_commerce", "ai_chatbot", "agent_copilot", "personalization"], "hybrid", "mid_market",
          "https://www.iadvize.com/", "crunchbase", hq="FR", fr="strong", regions=["FR", "EU"], geo="global"),
        v("shoppingfeed", "Shoppingfeed", "https://www.shoppingfeed.com/", ["retail-ecommerce-ai"],
          "Feed management IA FR ; diffusion marketplaces, optimisation titres/prix et analytics multicanal.",
          ["feed_management", "marketplaces", "ai_optimization", "multichannel"], "hybrid", "mid_market",
          "https://www.shoppingfeed.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("wishibam", "Wishibam", "https://www.wishibam.com/", ["retail-ecommerce-ai"],
          "Phygital retail FR ; showroom digital, prise RDV magasin et parcours omnicanal marques.",
          ["phygital", "digital_showroom", "store_appointments", "omnichannel"], "hybrid", "mid_market",
          "https://www.wishibam.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("octopia", "Octopia (Cdiscount)", "https://www.octopia.com/", ["retail-ecommerce-ai"],
          "Marketplace tech FR ; onboarding sellers, catalogues, fulfillment et analytics marketplace.",
          ["marketplace_tech", "seller_onboarding", "fulfillment", "marketplace_analytics"], "enterprise_quote", "enterprise",
          "https://www.octopia.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("ravelin", "Ravelin", "https://www.ravelin.com/", ["retail-ecommerce-ai"],
          "Fraude e-commerce ML ; scoring transactions, chargebacks et analytics risque paiement retail.",
          ["fraud_detection", "ml_scoring", "chargebacks", "payment_risk"], "hybrid", "mid_market",
          "https://www.ravelin.com/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="global"),
        v("akeneo", "Akeneo", "https://www.akeneo.com/", ["retail-ecommerce-ai"],
          "PIM open source FR ; gestion catalogues produits, enrichissement IA et syndication multicanal.",
          ["pim", "product_catalog", "ai_enrichment", "syndication"], "hybrid", "mid_market",
          "https://www.akeneo.com/", "g2", hq="FR", fr="strong", regions=["FR", "EU"], geo="global"),
        v("wizville", "Wizville", "https://www.wizville.com/", ["retail-ecommerce-ai"],
          "Voice of customer FR ; avis clients, NPS et analytics satisfaction omnicanal retail.",
          ["customer_reviews", "nps", "voice_of_customer", "retail_analytics"], "hybrid", "mid_market",
          "https://www.wizville.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("syte", "Syte", "https://www.syte.ai/", ["retail-ecommerce-ai"],
          "Visual AI discovery ; recherche visuelle, recommandations produits et tagging automatique catalogues.",
          ["visual_search", "product_recommendations", "auto_tagging", "discovery"], "enterprise_quote", "enterprise",
          "https://www.syte.ai/", "g2", hq="IL", fr="partial", regions=["US", "EU"], geo="global"),
    ],
    "energy-cleantech.json": [
        v("dreev", "Dreev (TotalEnergies)", "https://dreev.com/", ["energy-cleantech"],
          "Smart charging EV FR ; V2G, optimisation charge flottes et services utilities/intégrateurs.",
          ["smart_charging", "v2g", "fleet_optimization", "utilities"], "enterprise_quote", "enterprise",
          "https://dreev.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("watteco", "Watteco", "https://www.watteco.com/", ["energy-cleantech"],
          "Capteurs IoT énergie FR ; monitoring conso, protocoles LoRa/SmartGrid et intégration BMS.",
          ["iot_sensors", "energy_monitoring", "lorawan", "bms_integration"], "hybrid", "mid_market",
          "https://www.watteco.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("beem-energy", "Beem Energy", "https://www.beemenergy.fr/", ["energy-cleantech"],
          "Kits solaires plug-and-play FR ; autoconsommation résidentielle, app monitoring et installation simplifiée.",
          ["residential_solar", "plug_and_play", "self_consumption", "monitoring_app"], "hybrid", "smb",
          "https://www.beemenergy.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("tado", "tado°", "https://www.tado.com/", ["energy-cleantech"],
          "Smart thermostat EU ; pilotage chauffage/clim, géofencing et économies énergie résidentiel.",
          ["smart_thermostat", "heating_control", "geofencing", "energy_savings"], "hybrid", "smb",
          "https://www.tado.com/", "g2", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("isometric", "Isometric", "https://isometric.com/", ["energy-cleantech", "esg-csrd"],
          "Registre crédits carbone ; MRV, certification removals et marketplace crédits haute intégrité.",
          ["carbon_credits", "mrv", "carbon_removals", "marketplace"], "enterprise_quote", "enterprise",
          "https://isometric.com/", "crunchbase", hq="GB", fr="partial", regions=["US", "EU"], geo="global"),
        v("sunology", "Sunology", "https://www.sunology.eu/", ["energy-cleantech"],
          "Panneaux solaires EU ; kits résidentiels, monitoring production et optimisation autoconsommation.",
          ["solar_panels", "residential", "production_monitoring", "self_consumption"], "hybrid", "smb",
          "https://www.sunology.eu/", "g2", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("ekodev", "Ekodev", "https://www.ekodev.fr/", ["energy-cleantech"],
          "Performance énergétique tertiaire FR ; audits, CPE et pilotage décret tertiaire/RE2020.",
          ["energy_performance", "tertiary", "decret_tertiaire", "re2020"], "hybrid", "mid_market",
          "https://www.ekodev.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
    ],
    "esg-csrd.json": [
        v("apiday", "Apiday", "https://www.apiday.com/", ["esg-csrd"],
          "Collecte ESG PME FR ; questionnaires investisseurs, KPIs CSRD et reporting extra-financier simplifié.",
          ["esg_data_collection", "investor_questionnaires", "csrd", "sme_reporting"], "hybrid", "mid_market",
          "https://www.apiday.com/", "crunchbase", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("climate-partner", "ClimatePartner", "https://www.climatepartner.com/", ["esg-csrd"],
          "Neutralité carbone EU ; calcul empreinte, compensation certifiée et labels ClimatePartner.",
          ["carbon_footprint", "offsetting", "certification", "climate_labels"], "hybrid", "mid_market",
          "https://www.climatepartner.com/", "g2", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("emitwise", "Emitwise", "https://www.emitwise.com/", ["esg-csrd"],
          "Carbon accounting scope 1-3 ; collecte données supply chain, trajectoires SBTi et reporting CSRD.",
          ["carbon_accounting", "scope_3", "sbti", "csrd_reporting"], "enterprise_quote", "mid_market",
          "https://www.emitwise.com/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="europe"),
        v("klim", "Klim", "https://www.klim.eco/", ["esg-csrd"],
          "Crédits carbone agricoles FR ; pratiques régénératives, MRV sols et marketplace agriculteurs.",
          ["agricarbon", "regenerative_ag", "soil_mrv", "farmer_marketplace"], "hybrid", "mid_market",
          "https://www.klim.eco/", "geo_digest", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("metrio", "Metrio (EcoAct)", "https://www.metrio.com/", ["esg-csrd"],
          "Plateforme ESG EU ; collecte KPIs, reporting CSRD/ESRS et analytics performance durable.",
          ["esg_platform", "csrd", "esrs", "sustainability_analytics"], "enterprise_quote", "enterprise",
          "https://www.metrio.com/", "g2", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("position-green", "Position Green", "https://www.positiongreen.com/", ["esg-csrd"],
          "ESG software nordique ; double matérialité, CSRD disclosures et gestion données extra-financières.",
          ["double_materiality", "csrd_disclosures", "esg_data", "reporting"], "enterprise_quote", "mid_market",
          "https://www.positiongreen.com/", "g2", hq="SE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("altruistiq", "Altruistiq", "https://www.altruistiq.com/", ["esg-csrd"],
          "Carbon management enterprise ; mesure scope 3, plans réduction et reporting investisseurs CSRD.",
          ["scope_3", "carbon_management", "reduction_plans", "investor_reporting"], "enterprise_quote", "enterprise",
          "https://www.altruistiq.com/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="europe"),
        v("minimum", "Minimum", "https://www.minimum.com/", ["esg-csrd"],
          "Carbon API enterprise ; calcul empreinte produits, intégration ERP et labels carbone automatisés.",
          ["carbon_api", "product_footprint", "erp_integration", "carbon_labels"], "hybrid", "mid_market",
          "https://www.minimum.com/", "crunchbase", hq="GB", fr="partial", regions=["US", "EU"], geo="global"),
    ],
    "pharma-regulatory.json": [
        v("montrium", "Montrium", "https://www.montrium.com/", ["pharma-regulatory"],
          "Regulatory cloud EU ; dossiers eCTD, soumissions EMA/FDA et collaboration regulatory affairs.",
          ["ectd", "regulatory_submissions", "ema_fda", "collaboration"], "enterprise_quote", "enterprise",
          "https://www.montrium.com/", "g2", hq="NL", fr="partial", regions=["US", "EU"], geo="europe"),
        v("arisglobal", "ArisGlobal", "https://www.arisglobal.com/", ["pharma-regulatory"],
          "Life sciences platform ; pharmacovigilance, regulatory information et quality management GxP.",
          ["pharmacovigilance", "regulatory_information", "gxp", "quality_management"], "enterprise_quote", "enterprise",
          "https://www.arisglobal.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("valgenesis", "ValGenesis", "https://www.valgenesis.com/", ["pharma-regulatory"],
          "Validation lifecycle management ; CSV, GxP validation et dossiers audit-ready pharma.",
          ["csv", "gxp_validation", "lifecycle_management", "audit_ready"], "enterprise_quote", "enterprise",
          "https://www.valgenesis.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("softway-medical", "Softway Medical", "https://www.softwaymedical.fr/", ["pharma-regulatory", "healthcare-clinical-ai"],
          "SIH cloud FR ; DPI, prescriptions, traçabilité médicaments et conformité HAS/HDS.",
          ["ehr", "prescriptions", "medication_traceability", "hds"], "enterprise_quote", "enterprise",
          "https://www.softwaymedical.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("pharmagest", "Pharmagest", "https://www.pharmagest.com/", ["pharma-regulatory"],
          "Solutions officine FR ; gestion pharmacie, traçabilité médicaments et conformité réglementaire ANSM.",
          ["pharmacy_management", "medication_traceability", "ansm_compliance", "dispensing"], "enterprise_quote", "mid_market",
          "https://www.pharmagest.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("idbs", "IDBS", "https://www.idbs.com/", ["pharma-regulatory"],
          "R&D data platform ; ELN, workflows labo et regulatory data management biopharma.",
          ["eln", "lab_workflows", "rd_data", "regulatory_data"], "enterprise_quote", "enterprise",
          "https://www.idbs.com/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="global"),
        v("sparta-systems", "Sparta Systems (TrackWise)", "https://www.spartasystems.com/", ["pharma-regulatory"],
          "Quality management pharma ; déviations, CAPA, audits et conformité FDA/EMA GxP.",
          ["quality_management", "capa", "deviations", "fda_ema_gxp"], "enterprise_quote", "enterprise",
          "https://www.spartasystems.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
    ],
    "privacy-consent.json": [
        v("commanders-act", "Commanders Act (TrustCommander)", "https://www.commandersact.com/", ["privacy-consent"],
          "Tag management et CMP FR ; consentement cookies, gouvernance data marketing et conformité CNIL.",
          ["cmp", "tag_management", "cnil", "marketing_governance"], "hybrid", "mid_market",
          "https://www.commandersact.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("cookie-information", "Cookie Information", "https://cookieinformation.com/", ["privacy-consent"],
          "CMP EU ; scan cookies, bannières conformes ePrivacy et logs consentement GDPR.",
          ["cmp", "cookie_scan", "eprivacy", "consent_logs"], "hybrid", "smb",
          "https://cookieinformation.com/", "g2", hq="DK", fr="partial", regions=["US", "EU"], geo="europe"),
        v("consentmanager", "consentmanager", "https://www.consentmanager.net/", ["privacy-consent"],
          "CMP enterprise EU ; TCF IAB, multi-langues et gestion consentement multi-domaines.",
          ["cmp", "tcf", "multi_language", "multi_domain"], "hybrid", "mid_market",
          "https://www.consentmanager.net/", "g2", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("complianz", "Complianz", "https://complianz.io/", ["privacy-consent"],
          "CMP WordPress EU ; bannières cookies, privacy policy generator et conformité GDPR/CCPA.",
          ["cmp", "wordpress", "privacy_policy", "gdpr_ccpa"], "freemium", "smb",
          "https://complianz.io/", "g2", hq="NL", fr="partial", regions=["US", "EU"], geo="europe"),
        v("pandectes", "Pandectes", "https://pandectes.io/", ["privacy-consent"],
          "CMP Shopify/GDPR ; gestion consentement e-commerce, scan apps et conformité multi-régions.",
          ["cmp", "shopify", "ecommerce", "multi_region"], "hybrid", "smb",
          "https://pandectes.io/", "g2", hq="GR", fr="partial", regions=["US", "EU"], geo="global"),
        v("privacybee", "PrivacyBee", "https://privacybee.com/", ["privacy-consent"],
          "Privacy management EU ; registres traitements, DSAR et assessments GDPR pour PME.",
          ["processing_register", "dsar", "gdpr_assessments", "sme"], "hybrid", "smb",
          "https://privacybee.com/", "g2", hq="BE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("quantcast-choice", "Quantcast Choice", "https://www.quantcast.com/products/consent-management/", ["privacy-consent"],
          "CMP TCF IAB ; consentement audience, intégration programmatic et conformité GDPR/CCPA.",
          ["cmp", "tcf", "programmatic", "gdpr_ccpa"], "freemium", "mid_market",
          "https://www.quantcast.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
    ],
    "regulatory-reporting-eu.json": [
        v("generix", "Generix Group", "https://www.generixgroup.com/", ["regulatory-reporting-eu"],
          "Supply chain & e-invoicing FR ; EDI, facturation électronique réforme 2026 et conformité TVA EU.",
          ["edi", "e_invoicing", "vat_compliance", "supply_chain"], "enterprise_quote", "enterprise",
          "https://www.generixgroup.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("taxually", "Taxually", "https://www.taxually.com/", ["regulatory-reporting-eu"],
          "VAT automation EU ; déclarations TVA multi-pays, e-invoicing et conformité fiscale cross-border.",
          ["vat_automation", "multi_country", "e_invoicing", "tax_compliance"], "hybrid", "mid_market",
          "https://www.taxually.com/", "g2", hq="HU", fr="partial", regions=["US", "EU"], geo="europe"),
        v("fonoa", "Fonoa", "https://www.fonoa.com/", ["regulatory-reporting-eu"],
          "Tax compliance API ; TVA, e-invoicing et reporting fiscal automatisé pour plateformes/marketplaces.",
          ["tax_api", "vat", "e_invoicing", "marketplace_compliance"], "hybrid", "mid_market",
          "https://www.fonoa.com/", "crunchbase", hq="IE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("vertex-inc", "Vertex Inc.", "https://www.vertexinc.com/", ["regulatory-reporting-eu"],
          "Indirect tax enterprise ; moteur TVA global, e-invoicing et conformité fiscale multi-juridictions.",
          ["indirect_tax", "vat_engine", "e_invoicing", "multi_jurisdiction"], "enterprise_quote", "enterprise",
          "https://www.vertexinc.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("ecosio", "ecosio", "https://ecosio.com/", ["regulatory-reporting-eu"],
          "E-invoicing Peppol EU ; réseau facturation électronique, routage B2B/B2G et conformité EN16931.",
          ["peppol", "e_invoicing", "b2b_b2g", "en16931"], "hybrid", "mid_market",
          "https://ecosio.com/", "g2", hq="AT", fr="partial", regions=["US", "EU"], geo="europe"),
        v("flowie", "Flowie", "https://www.flowie.fr/", ["regulatory-reporting-eu"],
          "E-invoicing PME FR ; facturation électronique réforme 2026, archivage légal et intégration compta.",
          ["e_invoicing", "france_reform_2026", "legal_archive", "accounting_integration"], "hybrid", "smb",
          "https://www.flowie.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("fintechos", "FintechOS", "https://www.fintechos.com/", ["regulatory-reporting-eu"],
          "Platform banking/regulatory EU ; produits financiers no-code, reporting et conformité multi-pays.",
          ["banking_platform", "no_code", "regulatory_reporting", "multi_country"], "enterprise_quote", "enterprise",
          "https://www.fintechos.com/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="europe"),
        v("comarch-vat", "Comarch VAT & e-Invoicing", "https://www.comarch.com/finance/", ["regulatory-reporting-eu"],
          "Suite fiscal EU ; TVA temps réel, SAF-T et facturation électronique intégrée ERP.",
          ["vat", "saf_t", "e_invoicing", "erp_integration"], "enterprise_quote", "enterprise",
          "https://www.comarch.com/", "g2", hq="PL", fr="partial", regions=["US", "EU"], geo="europe"),
    ],
    "healthcare-clinical-ai.json": [
        v("cardiologs", "Cardiologs", "https://www.cardiologs.com/", ["healthcare-clinical-ai"],
          "IA ECG FR ; analyse automatique ECG, détection arythmies et intégration workflows cardiologie.",
          ["ecg_ai", "arrhythmia_detection", "cardiology", "clinical_workflows"], "enterprise_quote", "enterprise",
          "https://www.cardiologs.com/", "crunchbase", hq="FR", fr="strong", regions=["FR", "EU"], geo="global"),
        v("incepto", "Incepto", "https://www.incepto-medical.com/", ["healthcare-clinical-ai"],
          "Marketplace IA radiologie FR ; distribution algorithmes diagnostiques, déploiement hôpitaux et MDR.",
          ["radiology_ai", "algorithm_marketplace", "hospital_deployment", "mdr"], "enterprise_quote", "enterprise",
          "https://www.incepto-medical.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("deepc", "deepc", "https://www.deepc.ai/", ["healthcare-clinical-ai"],
          "Orchestration IA imagerie EU ; routing algorithmes, gouvernance MDR et intégration PACS/RIS.",
          ["imaging_ai", "algorithm_orchestration", "mdr_governance", "pacs_integration"], "enterprise_quote", "enterprise",
          "https://www.deepc.ai/", "crunchbase", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("therapixel", "Therapixel", "https://www.therapixel.com/", ["healthcare-clinical-ai"],
          "IA mammographie FR ; détection lésions, priorisation examens et aide diagnostic radiologues.",
          ["mammography_ai", "lesion_detection", "prioritization", "diagnostic_aid"], "enterprise_quote", "enterprise",
          "https://www.therapixel.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("mediktor", "Mediktor", "https://www.mediktor.com/", ["healthcare-clinical-ai"],
          "Triage symptômes IA ; API triage patient, orientation soins et intégration parcours e-santé.",
          ["symptom_triage", "patient_routing", "api", "ehealth"], "hybrid", "mid_market",
          "https://www.mediktor.com/", "g2", hq="ES", fr="partial", regions=["US", "EU"], geo="europe"),
        v("withings-health", "Withings Health Solutions", "https://www.withings.com/health-solutions", ["healthcare-clinical-ai"],
          "Remote patient monitoring FR ; devices connectés, programmes RPM et intégration EHR hôpitaux.",
          ["rpm", "connected_devices", "patient_monitoring", "ehr_integration"], "enterprise_quote", "enterprise",
          "https://www.withings.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="global"),
        v("binah-ai", "Binah.ai", "https://www.binah.ai/", ["healthcare-clinical-ai"],
          "Vitals AI vidéo ; mesure signes vitaux via smartphone, triage et télésurveillance.",
          ["video_vitals", "smartphone", "triage", "telemonitoring"], "enterprise_quote", "mid_market",
          "https://www.binah.ai/", "g2", hq="IL", fr="partial", regions=["US", "EU"], geo="global"),
        v("medecom", "Medecom", "https://www.medecom.fr/", ["healthcare-clinical-ai"],
          "Télémédecine et IA clinique FR ; téléconsultation spécialisée, dossiers patients et HDS.",
          ["telemedicine", "specialist_consultation", "patient_records", "hds"], "hybrid", "mid_market",
          "https://www.medecom.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
    ],
    "health-data-analytics.json": [
        v("adimed", "Adimed", "https://www.adimed.fr/", ["health-data-analytics"],
          "Data santé territoriale FR ; indicateurs population, analytics épidémiologie et tableaux ARS/communes.",
          ["territorial_health", "epidemiology", "population_indicators", "public_health"], "enterprise_quote", "enterprise",
          "https://www.adimed.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("phare-data", "Phare Data", "https://www.pharedata.com/", ["health-data-analytics"],
          "Real-world evidence FR ; analytics données médico-administratives, études pharmaco-épidémiologie.",
          ["rwe", "medico_administrative", "pharmaco_epidemiology", "studies"], "enterprise_quote", "enterprise",
          "https://www.pharedata.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("omny-health", "Omny Health", "https://www.omnyhealth.com/", ["health-data-analytics"],
          "Health data platform ; agrégation EHR/claims, analytics population health et cohortes recherche.",
          ["ehr_aggregation", "claims", "population_health", "research_cohorts"], "enterprise_quote", "enterprise",
          "https://www.omnyhealth.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("iqvia-rwe", "IQVIA Real-World Solutions", "https://www.iqvia.com/solutions/real-world-evidence", ["health-data-analytics"],
          "RWE enterprise ; données santé globales, analytics outcomes et études réglementaires/post-market.",
          ["rwe", "global_health_data", "outcomes_analytics", "regulatory_studies"], "enterprise_quote", "enterprise",
          "https://www.iqvia.com/", "analyst_report", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("medtrail", "MedTrail", "https://www.medtrail.io/", ["health-data-analytics"],
          "Patient journey analytics EU ; parcours de soins, adherence et analytics pharma/market access.",
          ["patient_journey", "adherence", "pharma_analytics", "market_access"], "enterprise_quote", "enterprise",
          "https://www.medtrail.io/", "crunchbase", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("holihealth", "HoliHealth", "https://www.holihealth.io/", ["health-data-analytics"],
          "Analytics prévention FR ; scoring risque santé, programmes prévention entreprise/assureurs.",
          ["prevention_analytics", "risk_scoring", "corporate_wellness", "insurer_programs"], "hybrid", "mid_market",
          "https://www.holihealth.io/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("syntegra", "Syntegra", "https://www.syntegra.io/", ["health-data-analytics"],
          "Synthetic health data ; génération datasets synthétiques privacy-preserving pour recherche IA.",
          ["synthetic_data", "privacy_preserving", "research", "health_ai"], "enterprise_quote", "enterprise",
          "https://www.syntegra.io/", "crunchbase", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
    ],
    "legal-contract-ai.json": [
        v("legalstart", "Legalstart", "https://www.legalstart.fr/", ["legal-contract-ai"],
          "Legaltech PME FR ; création société, contrats types et formalités juridiques en ligne.",
          ["company_creation", "contract_templates", "legal_formalities", "sme"], "hybrid", "smb",
          "https://www.legalstart.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("legalplace", "LegalPlace", "https://www.legalplace.fr/", ["legal-contract-ai"],
          "Services juridiques online FR ; statuts, contrats commerciaux et veille obligations légales PME.",
          ["legal_services", "statutes", "commercial_contracts", "compliance_alerts"], "hybrid", "smb",
          "https://www.legalplace.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("kleo", "Kleo", "https://www.kleo.fr/", ["legal-contract-ai"],
          "Practice management avocats FR ; dossiers, facturation, agenda et automatisation actes juridiques.",
          ["practice_management", "billing", "case_management", "legal_automation"], "hybrid", "mid_market",
          "https://www.kleo.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("dili", "Dili", "https://www.dili.fr/", ["legal-contract-ai"],
          "Analyse contrats IA FR ; revue clauses, scoring risques et recommandations négociation.",
          ["contract_analysis", "clause_review", "risk_scoring", "negotiation"], "hybrid", "mid_market",
          "https://www.dili.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("lawgeex", "LawGeex", "https://www.lawgeex.com/", ["legal-contract-ai"],
          "Contract review AI ; analyse automatique contrats, playbooks et approbation workflows legal ops.",
          ["contract_review", "playbooks", "approval_workflows", "legal_ops"], "enterprise_quote", "enterprise",
          "https://www.lawgeex.com/", "g2", hq="IL", fr="partial", regions=["US", "EU"], geo="global"),
        v("kira-systems", "Kira Systems (Litera)", "https://kirasystems.com/", ["legal-contract-ai"],
          "Due diligence IA ; extraction clauses, analyse M&A et revue portefeuilles contrats enterprise.",
          ["due_diligence", "clause_extraction", "m_and_a", "contract_portfolio"], "enterprise_quote", "enterprise",
          "https://kirasystems.com/", "g2", hq="CA", fr="partial", regions=["US", "EU"], geo="global"),
        v("genie-ai-legal", "Genie AI", "https://www.genieai.co/", ["legal-contract-ai"],
          "Legal drafting AI ; génération contrats, templates intelligents et collaboration legal/business.",
          ["contract_drafting", "smart_templates", "collaboration", "legal_ai"], "hybrid", "mid_market",
          "https://www.genieai.co/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="global"),
    ],
    "payroll-hris.json": [
        v("people-doc", "PeopleDoc (UKG)", "https://www.ukg.com/", ["payroll-hris"],
          "HR service delivery FR ; dossiers employés digitaux, workflows RH et conformité sociale.",
          ["employee_files", "hr_workflows", "service_delivery", "social_compliance"], "enterprise_quote", "enterprise",
          "https://www.ukg.com/", "g2", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("talentia", "Talentia Software", "https://www.talentia.com/", ["payroll-hris"],
          "SIRH/paie mid-market FR ; core HR, paie multi-conventions et reporting social.",
          ["hris", "payroll", "multi_convention", "social_reporting"], "enterprise_quote", "mid_market",
          "https://www.talentia.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("hr-path", "HR Path", "https://www.hr-path.com/", ["payroll-hris"],
          "Consulting et solutions HRIS FR ; déploiement SIRH, paie et transformation RH digital.",
          ["hris_implementation", "payroll", "hr_transformation", "consulting"], "enterprise_quote", "enterprise",
          "https://www.hr-path.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="global"),
        v("kelio", "Kelio (Bodet)", "https://www.kelio.com/", ["payroll-hris"],
          "Gestion temps/paie FR ; pointage, planning, absences et interface paie expert-comptable.",
          ["time_tracking", "scheduling", "absences", "payroll_interface"], "hybrid", "mid_market",
          "https://www.kelio.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("hibob", "HiBob", "https://www.hibob.com/", ["payroll-hris"],
          "HRIS moderne EU ; core HR, onboarding, performance et analytics people mid-market.",
          ["hris", "onboarding", "performance", "people_analytics"], "hybrid", "mid_market",
          "https://www.hibob.com/", "g2", hq="IL", fr="partial", regions=["US", "EU"], geo="global"),
        v("papaya-global", "Papaya Global", "https://www.papaya-global.com/", ["payroll-hris"],
          "Global payroll platform ; EOR, paiements multi-pays et conformité fiscale/sociale internationale.",
          ["global_payroll", "eor", "multi_country", "tax_compliance"], "hybrid", "mid_market",
          "https://www.papaya-global.com/", "g2", hq="IL", fr="partial", regions=["US", "EU"], geo="global"),
        v("sympa", "Sympa HR", "https://www.sympa.com/", ["payroll-hris"],
          "HRIS cloud EU ; core HR, workflows personnalisés et analytics RH PME/mid-market.",
          ["hris", "custom_workflows", "hr_analytics", "cloud"], "hybrid", "mid_market",
          "https://www.sympa.com/", "g2", hq="FI", fr="partial", regions=["US", "EU"], geo="europe"),
    ],
    "learning-lxp.json": [
        v("edflex", "Edflex", "https://www.edflex.com/", ["learning-lxp"],
          "LXP curation FR ; agrégation contenus formation, parcours upskilling et analytics compétences.",
          ["content_curation", "upskilling", "skills_analytics", "lxp"], "hybrid", "mid_market",
          "https://www.edflex.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("domoscio", "Domoscio", "https://www.domoscio.com/", ["learning-lxp"],
          "Adaptive learning FR ; IA spaced repetition, parcours personnalisés et analytics mémorisation.",
          ["adaptive_learning", "spaced_repetition", "personalization", "memory_analytics"], "hybrid", "mid_market",
          "https://www.domoscio.com/", "crunchbase", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("tentee", "Tentee", "https://www.tentee.co/", ["learning-lxp"],
          "Microlearning mobile FR ; capsules formation, gamification et suivi compétences équipes terrain.",
          ["microlearning", "mobile", "gamification", "field_teams"], "hybrid", "smb",
          "https://www.tentee.co/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("learnosity", "Learnosity", "https://www.learnosity.com/", ["learning-lxp"],
          "Assessment engine ; évaluations interactives, analytics apprentissage et intégration LMS/LXP.",
          ["assessments", "interactive", "learning_analytics", "lms_integration"], "enterprise_quote", "enterprise",
          "https://www.learnosity.com/", "g2", hq="AU", fr="partial", regions=["US", "EU"], geo="global"),
        v("eloomi", "Eloomi", "https://www.eloomi.com/", ["learning-lxp"],
          "LXP/LMS EU ; parcours formation, performance management et analytics compétences.",
          ["lxp", "lms", "performance", "skills_analytics"], "hybrid", "mid_market",
          "https://www.eloomi.com/", "g2", hq="DK", fr="partial", regions=["US", "EU"], geo="europe"),
        v("talentsoft", "Talentsoft (Cegid)", "https://www.talentsoft.com/", ["learning-lxp"],
          "LMS/SIRH formation FR ; catalogues, parcours blended et lien GPEC/compétences.",
          ["lms", "blended_learning", "gpec", "skills"], "enterprise_quote", "enterprise",
          "https://www.talentsoft.com/", "g2", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("neobrain", "Neobrain", "https://www.neobrain.io/", ["learning-lxp"],
          "Skills intelligence FR ; cartographie compétences, recommandations formation IA et mobilité interne.",
          ["skills_intelligence", "competency_mapping", "ai_recommendations", "internal_mobility"], "hybrid", "mid_market",
          "https://www.neobrain.io/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
    ],
    "treasury-fpa.json": [
        v("planful", "Planful", "https://planful.com/", ["treasury-fpa"],
          "FP&A cloud ; budgeting, forecasting rolling et reporting financier consolidé mid-market/enterprise.",
          ["fp_and_a", "budgeting", "rolling_forecast", "consolidated_reporting"], "hybrid", "mid_market",
          "https://planful.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("onestream", "OneStream", "https://www.onestream.com/", ["treasury-fpa"],
          "CPE platform ; consolidation, reporting et analytics financiers unifiés enterprise.",
          ["cpe", "consolidation", "financial_reporting", "analytics"], "enterprise_quote", "enterprise",
          "https://www.onestream.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("jedox", "Jedox", "https://www.jedox.com/", ["treasury-fpa"],
          "FP&A EU ; planning intégré Excel-like, scenarios et reporting EPM mid-market.",
          ["fp_and_a", "integrated_planning", "scenarios", "epm"], "hybrid", "mid_market",
          "https://www.jedox.com/", "g2", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("board-intl", "Board", "https://www.board.com/", ["treasury-fpa"],
          "Intelligent planning EU ; FP&A, supply chain planning et analytics décisionnels unifiés.",
          ["intelligent_planning", "fp_and_a", "supply_chain_planning", "decision_analytics"], "enterprise_quote", "enterprise",
          "https://www.board.com/", "g2", hq="CH", fr="partial", regions=["US", "EU"], geo="europe"),
        v("fintecture", "Fintecture", "https://www.fintecture.com/", ["treasury-fpa"],
          "Open banking paiements FR ; virements instantanés, réconciliation et cash management PME.",
          ["open_banking", "instant_payments", "reconciliation", "cash_management"], "hybrid", "smb",
          "https://www.fintecture.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("float-cash", "Float", "https://www.float.com/", ["treasury-fpa"],
          "Cash management PME ; prévisions trésorerie, scenarios et intégration comptabilité bancaire.",
          ["cash_management", "cash_forecasting", "scenarios", "banking_integration"], "hybrid", "smb",
          "https://www.float.com/", "g2", hq="CA", fr="partial", regions=["US", "EU"], geo="global"),
        v("cashanalytics", "CashAnalytics", "https://www.cashanalytics.com/", ["treasury-fpa"],
          "Cash forecasting EU ; ML prévisions flux, rapprochement bancaire et dashboards trésorerie.",
          ["cash_forecasting", "ml", "bank_reconciliation", "treasury_dashboards"], "hybrid", "mid_market",
          "https://www.cashanalytics.com/", "g2", hq="IE", fr="partial", regions=["US", "EU"], geo="europe"),
    ],
    "finance-accounting-ai.json": [
        v("expensya", "Expensya", "https://www.expensya.com/", ["finance-accounting-ai"],
          "Notes de frais IA FR ; OCR reçus, validation workflows et export comptable/paie.",
          ["expense_management", "ocr", "approval_workflows", "accounting_export"], "hybrid", "mid_market",
          "https://www.expensya.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("sellsy", "Sellsy", "https://www.sellsy.com/", ["finance-accounting-ai"],
          "CRM/compta PME FR ; facturation, trésorerie, CRM et automatisation cycle vente-compta.",
          ["crm", "invoicing", "cashflow", "sales_automation"], "hybrid", "smb",
          "https://www.sellsy.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("tiime", "Tiime", "https://www.tiime.fr/", ["finance-accounting-ai"],
          "Comptabilité PME FR ; saisie assistée IA, TVA, liasse fiscale et collaboration expert-comptable.",
          ["accounting", "ai_assisted_entry", "vat", "tax_filing"], "hybrid", "smb",
          "https://www.tiime.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("dougs", "Dougs", "https://www.dougs.fr/", ["finance-accounting-ai"],
          "Expert-comptable online FR ; compta TPE, conseil fiscal et automatisation obligations légales.",
          ["online_accountant", "sme_accounting", "tax_advice", "compliance_automation"], "hybrid", "smb",
          "https://www.dougs.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("sevdesk", "sevDesk", "https://sevdesk.com/", ["finance-accounting-ai"],
          "Compta cloud PME EU ; facturation, banque, TVA et automatisation comptable allemande/EU.",
          ["cloud_accounting", "invoicing", "vat", "banking"], "hybrid", "smb",
          "https://sevdesk.com/", "g2", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
        v("freebe", "Freebe", "https://www.freebe.me/", ["finance-accounting-ai"],
          "Compta freelances FR ; facturation, URSSAF, TVA et prévisionnel activité indépendants.",
          ["freelance_accounting", "invoicing", "urssaf", "vat"], "hybrid", "smb",
          "https://www.freebe.me/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("datev", "DATEV", "https://www.datev.de/", ["finance-accounting-ai"],
          "Suite comptable/fiscale EU ; production comptable cabinets, paie adjacente et conformité fiscale DE/EU.",
          ["accounting_suite", "tax_compliance", "accountant_tools", "payroll_adjacent"], "enterprise_quote", "mid_market",
          "https://www.datev.de/", "g2", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
    ],
    "supply-chain-logistics.json": [
        v("flowlity", "Flowlity", "https://www.flowlity.com/", ["supply-chain-logistics"],
          "Demand forecasting IA FR ; prévisions ML, inventory optimization et S&OP industrie/retail.",
          ["demand_forecasting", "ml", "inventory_optimization", "s_and_op"], "hybrid", "mid_market",
          "https://www.flowlity.com/", "crunchbase", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("stockly", "Stockly", "https://www.stockly.ai/", ["supply-chain-logistics"],
          "Inventory sharing retail FR ; mutualisation stocks e-commerce, fulfillment et réduction ruptures.",
          ["inventory_sharing", "ecommerce", "fulfillment", "stock_optimization"], "hybrid", "mid_market",
          "https://www.stockly.ai/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("bigblue", "Bigblue", "https://www.bigblue.co/", ["supply-chain-logistics"],
          "Fulfillment e-commerce FR ; entrepôts, préparation commandes et livraison D2C Europe.",
          ["fulfillment", "warehousing", "d2c", "ecommerce_logistics"], "hybrid", "mid_market",
          "https://www.bigblue.co/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="europe"),
        v("everstream-analytics", "Everstream Analytics", "https://www.everstream.ai/", ["supply-chain-logistics"],
          "Supply chain risk AI ; alertes risques, prédictions disruptions et analytics fournisseurs/logistique.",
          ["supply_chain_risk", "disruption_prediction", "supplier_analytics", "alerts"], "enterprise_quote", "enterprise",
          "https://www.everstream.ai/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("stowga", "Stowga", "https://www.stowga.com/", ["supply-chain-logistics"],
          "Marketplace entrepôts EU ; stockage flexible, fulfillment on-demand et optimisation coûts logistiques.",
          ["warehouse_marketplace", "flex_storage", "on_demand_fulfillment", "cost_optimization"], "hybrid", "mid_market",
          "https://www.stowga.com/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="europe"),
        v("oware", "Oware", "https://www.oware.fr/", ["supply-chain-logistics"],
          "WMS cloud FR ; gestion entrepôt, préparation commandes et intégration e-commerce/ERP.",
          ["wms", "warehouse_management", "order_picking", "erp_integration"], "hybrid", "mid_market",
          "https://www.oware.fr/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="france"),
        v("seven-send", "Seven Senders", "https://www.sevensenders.com/", ["supply-chain-logistics"],
          "Delivery platform EU ; orchestration transporteurs last-mile, tracking et analytics livraison e-commerce.",
          ["last_mile", "carrier_orchestration", "tracking", "delivery_analytics"], "hybrid", "mid_market",
          "https://www.sevensenders.com/", "g2", hq="DE", fr="partial", regions=["US", "EU"], geo="europe"),
    ],
    "translation-localization.json": [
        v("textmaster", "TextMaster", "https://www.textmaster.com/", ["translation-localization"],
          "Traduction professionnelle FR ; API/localisation contenu, réseau traducteurs et workflows enterprise.",
          ["professional_translation", "api", "translator_network", "enterprise_workflows"], "hybrid", "mid_market",
          "https://www.textmaster.com/", "geo_digest", hq="FR", fr="strong", regions=["FR", "EU"], geo="global"),
        v("unbabel", "Unbabel", "https://unbabel.com/", ["translation-localization"],
          "Traduction IA + humain ; customer service multilingue, QA linguistique et intégration helpdesk.",
          ["ai_human_translation", "customer_service", "linguistic_qa", "helpdesk_integration"], "enterprise_quote", "enterprise",
          "https://unbabel.com/", "g2", hq="PT", fr="partial", regions=["US", "EU"], geo="global"),
        v("locize", "locize", "https://locize.com/", ["translation-localization"],
          "TMS/i18n cloud EU ; gestion clés traduction, CI/CD localisation et workflows développeurs.",
          ["tms", "i18n", "ci_cd", "developer_workflows"], "hybrid", "mid_market",
          "https://locize.com/", "g2", hq="CH", fr="partial", regions=["US", "EU"], geo="europe"),
        v("localizejs", "Localize", "https://localizejs.com/", ["translation-localization"],
          "Website localization ; traduction automatique/humaine, gestion strings et déploiement multilingue.",
          ["website_localization", "auto_translation", "string_management", "multilingual_deploy"], "hybrid", "mid_market",
          "https://localizejs.com/", "g2", hq="US", fr="partial", regions=["US", "EU"], geo="global"),
        v("rws-trados", "RWS Trados", "https://www.rws.com/localization/trados/", ["translation-localization"],
          "TMS enterprise ; mémoires traduction, workflows linguistiques et QA localisation globale.",
          ["tms", "translation_memory", "linguistic_workflows", "localization_qa"], "enterprise_quote", "enterprise",
          "https://www.rws.com/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="global"),
        v("xtm-cloud", "XTM Cloud", "https://xtm.cloud/", ["translation-localization"],
          "TMS cloud ; gestion projets traduction, MT post-editing et analytics productivité linguistique.",
          ["tms", "project_management", "mt_post_editing", "productivity_analytics"], "hybrid", "mid_market",
          "https://xtm.cloud/", "g2", hq="GB", fr="partial", regions=["US", "EU"], geo="global"),
        v("lingohub", "LingoHub", "https://lingohub.com/", ["translation-localization"],
          "Localization platform ; workflows i18n, intégration Git et collaboration traducteurs/développeurs.",
          ["i18n", "git_integration", "translator_collaboration", "workflows"], "hybrid", "mid_market",
          "https://lingohub.com/", "g2", hq="AT", fr="partial", regions=["US", "EU"], geo="europe"),
    ],
}

SEGMENT_PATCHES: dict[str, list[str]] = {
    "doctolib": ["healthcare-clinical-ai"],
    "procore": ["construction-proptech"],
    "metron": ["energy-cleantech"],
    "yooz": ["regulatory-reporting-eu"],
    "spendesk": ["finance-accounting-ai"],
    "agicap": ["treasury-fpa"],
}

COVERAGE_UPDATES: dict[str, dict[str, dict]] = {
    "accessibility-compliance": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
    },
    "construction-proptech": {
        "g2": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 1, "pass": PASS_ID},
    },
    "insurance-insurtech": {
        "g2": {"consulted_at": TODAY, "candidates_found": 22, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 2, "pass": PASS_ID},
    },
    "retail-ecommerce-ai": {
        "g2": {"consulted_at": TODAY, "candidates_found": 24, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 1, "pass": PASS_ID},
    },
    "energy-cleantech": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
    },
    "esg-csrd": {
        "g2": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 2, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
    },
    "pharma-regulatory": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
    },
    "privacy-consent": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
        "capterra": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "regulatory-reporting-eu": {
        "g2": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
    },
    "healthcare-clinical-ai": {
        "g2": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 1, "pass": PASS_ID},
    },
    "health-data-analytics": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
    },
    "legal-contract-ai": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "payroll-hris": {
        "g2": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "learning-lxp": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "treasury-fpa": {
        "g2": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "finance-accounting-ai": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
    },
    "supply-chain-logistics": {
        "g2": {"consulted_at": TODAY, "candidates_found": 22, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 3, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 1, "pass": PASS_ID},
    },
    "translation-localization": {
        "g2": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "alternatives": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
}

TARGET_LEVELS = {seg: "L3" for seg in COVERAGE_UPDATES}


def patch_segments() -> int:
    patched = 0
    for path in VENDORS_DIR.glob("*.json"):
        data = json.loads(path.read_text(encoding="utf-8"))
        changed = False
        for vendor in data.get("vendors", []):
            extra = SEGMENT_PATCHES.get(vendor["id"])
            if not extra:
                continue
            for seg in extra:
                if seg not in vendor["segments"]:
                    vendor["segments"].append(seg)
                    changed = True
                    patched += 1
        if changed:
            data["updated_at"] = TODAY
            path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return patched


def merge() -> None:
    all_ids: set[str] = set()
    for path in VENDORS_DIR.glob("*.json"):
        for vendor in json.loads(path.read_text(encoding="utf-8")).get("vendors", []):
            all_ids.add(vendor["id"])

    total = 0
    per_file: dict[str, int] = {}
    for fname, vendors in ADDITIONS.items():
        path = VENDORS_DIR / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        count = 0
        for vendor in vendors:
            if vendor["id"] in all_ids:
                print(f"skip duplicate: {vendor['id']}")
                continue
            data["vendors"].append(vendor)
            all_ids.add(vendor["id"])
            count += 1
            total += 1
        data["updated_at"] = TODAY
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        per_file[fname] = count
        print(f"updated {fname}: +{count}")

    patched = patch_segments()
    if patched:
        print(f"segment patches: +{patched}")

    matrix = json.loads(COVERAGE.read_text(encoding="utf-8"))
    for seg_id, sources in COVERAGE_UPDATES.items():
        entry = matrix["segments"][seg_id]
        for src, upd in sources.items():
            prev = entry["sources"].get(src) or {}
            entry["sources"][src] = {
                **upd,
                "cumulative_new": prev.get("cumulative_new", prev.get("new_added", 0)) + upd["new_added"],
            }
        entry["last_pass"] = PASS_ID
        entry["target_level"] = TARGET_LEVELS.get(seg_id, entry.get("target_level", "L2"))
        entry["vendor_count_after_pass"] = len(
            json.loads((VENDORS_DIR / f"{seg_id}.json").read_text(encoding="utf-8"))["vendors"]
        )
    matrix["updated_at"] = TODAY
    COVERAGE.write_text(json.dumps(matrix, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"done: +{total} vendors")
    for fname, n in per_file.items():
        print(f"  {fname}: +{n}")


if __name__ == "__main__":
    merge()
