#!/usr/bin/env python3
"""Vague 5k — moisson territoire idées 0025–0028 (copro, énergie, géo, marchés, RH)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
COVERAGE = ROOT / "catalogue-saas" / "coverage-matrix.json"
TODAY = "2026-06-23"
PASS_ID = "2026-06-v5k-territoire-idees"


def v(
    id_: str,
    name: str,
    url: str,
    segments: list[str],
    desc: str,
    caps: list[str],
    pricing: str,
    market: str,
    source: str,
    src_type: str,
    hq: str = "FR",
    fr: str = "strong",
    regions: list[str] | None = None,
    geo: str = "france",
    notes: str | None = None,
) -> dict:
    d = {
        "id": id_,
        "name": name,
        "url": url,
        "segments": segments,
        "description": desc,
        "capabilities": caps,
        "pricing_model": pricing,
        "target_market": market,
        "geography": geo,
        "hq_country": hq,
        "france_market": fr,
        "operating_regions": regions or ["FR", "EU"],
        "discovery_source": src_type,
        "discovery_pass": PASS_ID,
        "source_url": source,
        "source_consulted_at": TODAY,
        "verification_status": "partial",
    }
    if notes:
        d["notes"] = notes
    return d


ADDITIONS: dict[str, list[dict]] = {
    "real-estate-proptech.json": [
        v(
            "scanreno",
            "ScanReno",
            "https://www.scanreno.fr/",
            ["real-estate-proptech", "energy-buildings-fr"],
            "SaaS syndics pros : PPT 10 ans, DPE collectif, aides ANAH et pilotage rénovation copropriétés.",
            ["syndic", "dpe_collectif", "ppt", "renovation", "copropriete"],
            "hybrid",
            "smb",
            "https://www.scanreno.fr/",
            "geo_digest",
            notes="Concurrent cité idée 0025.",
        ),
        v(
            "powimo",
            "Powimo",
            "https://www.powimo.com/",
            ["real-estate-proptech"],
            "ERP syndic et gestion locative ; comptabilité copropriété, AG digitale et portail copropriétaires.",
            ["syndic", "copropriete", "gestion_locative", "erp"],
            "enterprise_quote",
            "mid_market",
            "https://www.powimo.com/",
            "geo_digest",
        ),
        v(
            "egide-copro",
            "EGIDE Copro",
            "https://www.egide-copro.fr/",
            ["real-estate-proptech"],
            "Logiciel syndic français ; gestion copropriétés, budgets, AG et communication copropriétaires.",
            ["syndic", "copropriete", "budget", "ag_digitale"],
            "enterprise_quote",
            "mid_market",
            "https://www.egide-copro.fr/",
            "geo_digest",
        ),
        v(
            "copro-solutions",
            "CoproSolutions",
            "https://www.copro-solutions.fr/",
            ["real-estate-proptech", "energy-buildings-fr"],
            "Plateforme syndics : pilotage copropriétés, DPE et plan pluriannuel travaux rénovation.",
            ["syndic", "dpe", "ppt", "copropriete"],
            "hybrid",
            "smb",
            "https://www.copro-solutions.fr/",
            "geo_digest",
            notes="Concurrent cité idée 0025.",
        ),
        v(
            "bdnb",
            "BDNB (CSTB)",
            "https://www.bdnb.io/",
            ["real-estate-proptech", "energy-buildings-fr", "geospatial-gis-fr"],
            "Base nationale open data bâtiments ; géolocalisation, DPE, matériaux et métriques rénovation.",
            ["bdnb", "dpe", "open_data", "batiments", "api"],
            "freemium",
            "mid_market",
            "https://www.bdnb.io/",
            "official_site",
        ),
        v(
            "kel-foncier",
            "Kel Foncier",
            "https://www.kelfoncier.com/",
            ["real-estate-proptech", "geospatial-gis-fr"],
            "Veille foncière et cartographie parcelles ; alertes opportunités pour aménageurs et promoteurs.",
            ["veille_fonciere", "parcelles", "alertes", "cartographie"],
            "hybrid",
            "mid_market",
            "https://www.kelfoncier.com/",
            "geo_digest",
            notes="Concurrent citée idée 0021/0026.",
        ),
        v(
            "deepki",
            "Deepki",
            "https://www.deepki.com/fr/",
            ["real-estate-proptech", "energy-buildings-fr", "environmental-data-fr"],
            "Plateforme ESG immobilier ; conso énergie, DPE portefeuille, résilience climatique et reporting CSRD.",
            ["esg", "dpe", "energy_analytics", "climate_resilience", "portfolio"],
            "enterprise_quote",
            "enterprise",
            "https://www.deepki.com/fr/",
            "analyst_report",
            notes="Concurrent cité idées 0024/0025.",
        ),
        v(
            "cityscan",
            "CityScan",
            "https://www.cityscan.fr/",
            ["real-estate-proptech"],
            "Diagnostic immobilier digital ; collecte DPE, photos et rapports pour pros de l'immobilier.",
            ["diagnostic", "dpe", "rapports", "immobilier"],
            "hybrid",
            "smb",
            "https://www.cityscan.fr/",
            "geo_digest",
        ),
        v(
            "immopen",
            "ImmOpen",
            "https://www.immopen.fr/",
            ["real-estate-proptech"],
            "Gestion locative et syndic digital ; loyers, quittances et portail locataires/copropriétaires.",
            ["gestion_locative", "syndic", "quittances", "portail"],
            "hybrid",
            "smb",
            "https://www.immopen.fr/",
            "geo_digest",
        ),
        v(
            "foncia-digital",
            "Foncia Digital",
            "https://fr.foncia.com/",
            ["real-estate-proptech"],
            "Suite digitale grand syndic FR ; gestion copropriétés, locatif et services résidents à l'échelle nationale.",
            ["syndic", "property_management", "copropriete", "locatif"],
            "enterprise_quote",
            "enterprise",
            "https://fr.foncia.com/",
            "official_site",
        ),
    ],
    "energy-buildings-fr.json": [
        v(
            "hellowatt",
            "Hello Watt",
            "https://www.hellowatt.com/",
            ["energy-buildings-fr"],
            "Accompagnement rénovation énergétique B2B/B2C ; DPE, devis travaux et suivi performance bâtiments.",
            ["renovation", "dpe", "devis_travaux", "b2b"],
            "hybrid",
            "smb",
            "https://www.hellowatt.com/",
            "geo_digest",
        ),
        v(
            "enoptea",
            "Enoptea",
            "https://www.enoptea.com/",
            ["energy-buildings-fr"],
            "Gestion énergie tertiaire ; monitoring conso, alertes dérives et reporting décret tertiaire.",
            ["energy_management", "tertiary", "monitoring", "decarbonation"],
            "enterprise_quote",
            "mid_market",
            "https://www.enoptea.com/",
            "crunchbase",
        ),
        v(
            "cantine-energetique",
            "Cantine Énergétique",
            "https://www.cantine-energetique.com/",
            ["energy-buildings-fr"],
            "SaaS efficacité énergétique bâtiments ; audits, plans d'actions et suivi rénovation pour pros.",
            ["energy_audit", "renovation", "b2b", "reporting"],
            "hybrid",
            "mid_market",
            "https://www.cantine-energetique.com/",
            "geo_digest",
        ),
        v(
            "welii",
            "Welii",
            "https://www.welii.fr/",
            ["energy-buildings-fr"],
            "Plateforme performance énergétique immobilier ; stratégie décarbonation et suivi KPI bâtiments.",
            ["decarbonation", "energy_performance", "real_estate", "kpi"],
            "enterprise_quote",
            "enterprise",
            "https://www.welii.fr/",
            "geo_digest",
        ),
        v(
            "homeys",
            "Homeys",
            "https://www.homeys.io/",
            ["energy-buildings-fr"],
            "Collecte et analyse données énergie bâtiments ; API compteurs, DPE et pilotage conso.",
            ["energy_data", "api", "meters", "dpe"],
            "hybrid",
            "mid_market",
            "https://www.homeys.io/",
            "crunchbase",
        ),
        v(
            "metron",
            "Metron",
            "https://www.metron.io/",
            ["energy-buildings-fr"],
            "Optimisation énergétique industrie et tertiaire ; EMS, analytics conso et réduction factures.",
            ["ems", "energy_optimization", "analytics", "tertiary"],
            "enterprise_quote",
            "enterprise",
            "https://www.metron.io/",
            "crunchbase",
        ),
        v(
            "izybat",
            "IzyBat",
            "https://www.izybat.com/",
            ["energy-buildings-fr"],
            "Logiciel rénovation énergétique ; chiffrage travaux, DPE et suivi chantiers pour artisans et pros.",
            ["renovation", "dpe", "chiffrage", "artisans"],
            "hybrid",
            "smb",
            "https://www.izybat.com/",
            "geo_digest",
        ),
        v(
            "go-renove-pro",
            "Go Rénove PRO (BDNB)",
            "https://www.bdnb.io/services/gorenove/",
            ["energy-buildings-fr", "real-estate-proptech"],
            "Service public CSTB : analyse parc bâtiments, tableaux de bord rénovation pour bailleurs et collectivités.",
            ["renovation", "bdnb", "parc_batiments", "public_service"],
            "freemium",
            "mid_market",
            "https://www.bdnb.io/services/gorenove/",
            "official_site",
            notes="Concurrent cité idée 0025.",
        ),
        v(
            "streem-energy",
            "Streem",
            "https://www.streem.eu/",
            ["energy-buildings-fr"],
            "Audit énergétique digital ; modélisation 3D bâtiments, scénarios travaux et reporting DPE.",
            ["energy_audit", "3d_modeling", "dpe", "renovation_scenarios"],
            "enterprise_quote",
            "mid_market",
            "https://www.streem.eu/",
            "geo_digest",
        ),
    ],
    "territorial-analytics.json": [
        v(
            "smappen",
            "Smappen",
            "https://www.smappen.com/",
            ["territorial-analytics"],
            "Géomarketing SaaS ; isochrones, zones de chalandise, démographie INSEE et études implantation.",
            ["geomarketing", "isochrones", "catchment", "insee"],
            "hybrid",
            "smb",
            "https://www.smappen.com/",
            "geo_digest",
            notes="Concurrent cité idées 0006/0028.",
        ),
        v(
            "geomarket",
            "Geomarket",
            "https://www.geomarket.one/",
            ["territorial-analytics"],
            "Études d'implantation commerciale ; concurrence SIRENE, pouvoir d'achat et zones ELM franchise.",
            ["implantation", "sirene", "elm", "franchise"],
            "hybrid",
            "smb",
            "https://www.geomarket.one/",
            "geo_digest",
            notes="Concurrent cité idée 0006.",
        ),
        v(
            "data-b",
            "Data-B",
            "https://www.data-b.fr/",
            ["territorial-analytics"],
            "Intelligence territoriale B2B ; flux piéton, concurrence locale et scoring emplacement commercial.",
            ["footfall", "local_competition", "scoring", "b2b"],
            "enterprise_quote",
            "mid_market",
            "https://www.data-b.fr/",
            "geo_digest",
            notes="Concurrent cité idées 0006/0028.",
        ),
        v(
            "vigicite",
            "VigiCité",
            "https://www.vigicite.fr/",
            ["territorial-analytics"],
            "Observatoire territorial collectivités ; indicateurs locaux, tableaux de bord et benchmarking inter-villes.",
            ["observatoire", "collectivites", "benchmark", "dashboards"],
            "enterprise_quote",
            "mid_market",
            "https://www.vigicite.fr/",
            "geo_digest",
        ),
        v(
            "localnova",
            "LocalNova",
            "https://www.localnova-finance-publique.fr/",
            ["territorial-analytics"],
            "Analytics finances locales ; budgets, dette et indicateurs EPCI/collectivités pour décideurs publics.",
            ["finances_locales", "budget", "epci", "benchmark"],
            "enterprise_quote",
            "mid_market",
            "https://www.localnova-finance-publique.fr/",
            "geo_digest",
        ),
        v(
            "galigeo",
            "Galigeo",
            "https://www.galigeo.com/",
            ["territorial-analytics"],
            "Géomarketing et études territoriales ; cartographie concurrence, flux et potentiel commercial.",
            ["geomarketing", "cartography", "commercial_potential", "studies"],
            "enterprise_quote",
            "mid_market",
            "https://www.galigeo.com/",
            "geo_digest",
        ),
        v(
            "insee-portrait-commune",
            "INSEE — Portrait de commune",
            "https://www.insee.fr/fr/statistiques/2017499",
            ["territorial-analytics"],
            "Statistiques communales officielles ; démographie, emploi, logement et revenus par territoire.",
            ["official_statistics", "commune", "demography", "open_data"],
            "freemium",
            "self_serve",
            "https://www.insee.fr/fr/statistiques/2017499",
            "official_site",
        ),
        v(
            "place-statistiques-locales",
            "Place des statistiques locales",
            "https://www.insee.fr/fr/outil-interactif/7134178",
            ["territorial-analytics"],
            "Outil interactif INSEE ; comparaison indicateurs territoriaux entre communes et EPCI.",
            ["insee", "comparative_stats", "local", "interactive"],
            "freemium",
            "self_serve",
            "https://www.insee.fr/fr/outil-interactif/7134178",
            "official_site",
        ),
        v(
            "france-travail-emploi-territoire",
            "France Travail — Emploi par territoire",
            "https://www.francetravail.org/statistiques-analyses/",
            ["territorial-analytics", "hr-talent-ai"],
            "Statistiques marché du travail ; demandeurs d'emploi, offres et tension par métier/commune.",
            ["labour_market", "employment_stats", "territory", "open_data"],
            "freemium",
            "mid_market",
            "https://www.francetravail.org/statistiques-analyses/",
            "official_site",
            notes="Source citée idée 0028.",
        ),
        v(
            "dares-emploi",
            "DARES — Données emploi",
            "https://dares.travail-emploi.gouv.fr/",
            ["territorial-analytics", "hr-talent-ai"],
            "Statistiques emploi ministère Travail ; séries territoriales, métiers en tension et analyses sectorielles.",
            ["employment_data", "territorial", "labour_tension", "official"],
            "freemium",
            "mid_market",
            "https://dares.travail-emploi.gouv.fr/",
            "official_site",
            notes="Source citée idée 0028.",
        ),
    ],
    "public-procurement-intel.json": [
        v(
            "decp-info",
            "decp.info",
            "https://decp.info/",
            ["public-procurement-intel", "territorial-analytics"],
            "Interface exploration DECP ; recherche marchés par titulaire, acheteur, CPV et export tabulaire.",
            ["decp", "exploration", "titulaire", "acheteur", "open_data"],
            "freemium",
            "self_serve",
            "https://decp.info/",
            "official_site",
            notes="Réutilisation data.gouv citée idées 0025/0027.",
        ),
        v(
            "data-economie-gouv",
            "data.economie.gouv.fr",
            "https://data.economie.gouv.fr/",
            ["public-procurement-intel"],
            "Portail open data Économie ; jeux DECP, subventions et entreprises pour transparence marchés publics.",
            ["decp", "subventions", "open_data", "portal"],
            "freemium",
            "mid_market",
            "https://data.economie.gouv.fr/",
            "official_site",
            notes="Source citée idée 0027.",
        ),
        v(
            "openbar",
            "OpenBar (Regards Citoyens)",
            "https://openbar.fr/",
            ["public-procurement-intel"],
            "Exploration subventions publiques ; bénéficiaires, montants et croisements RNA pour transparence.",
            ["subventions", "beneficiaires", "transparency", "rna"],
            "freemium",
            "self_serve",
            "https://openbar.fr/",
            "official_site",
            notes="Concurrent cité idée 0027.",
        ),
        v(
            "nextend-ai",
            "Nextend.ai",
            "https://nextend.ai/",
            ["public-procurement-intel"],
            "Veille marchés publics IA ; alertes BOAMP/DECP, analyse cahiers des charges et matching opportunités.",
            ["ao_monitoring", "decp", "ai_analysis", "alerts"],
            "hybrid",
            "smb",
            "https://nextend.ai/",
            "geo_digest",
            notes="Concurrent cité idée 0001.",
        ),
        v(
            "doubletrade",
            "DoubleTrade",
            "https://www.doubletrade.com/",
            ["public-procurement-intel"],
            "Intelligence marchés publics FR ; veille AO, historique attributions et analytics acheteurs/titulaires.",
            ["ao_veille", "decp", "analytics", "france"],
            "enterprise_quote",
            "mid_market",
            "https://www.doubletrade.com/",
            "geo_digest",
        ),
        v(
            "scdl-portail",
            "SCDL — Subventions de collectivités locales",
            "https://www.data.gouv.fr/datasets/subventions-de-collectivites-locales-aux-associations-et-entreprises",
            ["public-procurement-intel", "territorial-analytics"],
            "Jeu national subventions collectivités ; croisement potentiel avec DECP par SIRET bénéficiaire.",
            ["scdl", "subventions", "collectivites", "open_data"],
            "freemium",
            "mid_market",
            "https://www.data.gouv.fr/datasets/subventions-de-collectivites-locales-aux-associations-et-entreprises",
            "official_site",
            notes="Source citée idée 0027.",
        ),
        v(
            "weproc",
            "Weproc",
            "https://www.weproc.com/",
            ["public-procurement-intel", "spend-procurement"],
            "SRM achats publics ; sourcing fournisseurs, conformité et veille marchés pour collectivités.",
            ["srm", "public_buyers", "sourcing", "compliance"],
            "enterprise_quote",
            "enterprise",
            "https://www.weproc.com/",
            "geo_digest",
        ),
    ],
    "hr-talent-ai.json": [
        v(
            "talentsoft",
            "Talentsoft (Cegid)",
            "https://www.talentsoft.com/fr/",
            ["hr-talent-ai"],
            "Suite RH cloud FR ; ATS, talent management, LMS et analytics emploi pour ETI/grands comptes.",
            ["ats", "talent_management", "lms", "hr_analytics"],
            "enterprise_quote",
            "enterprise",
            "https://www.talentsoft.com/fr/",
            "g2",
        ),
        v(
            "lucca",
            "Lucca",
            "https://www.lucca.fr/",
            ["hr-talent-ai"],
            "Suite RH modulaire FR ; recrutement, absences, paie adjacente et workflows RH pour PME/ETI.",
            ["hris", "recruitment", "absences", "workflows"],
            "hybrid",
            "mid_market",
            "https://www.lucca.fr/",
            "g2",
        ),
        v(
            "jobteaser",
            "JobTeaser",
            "https://www.jobteaser.com/",
            ["hr-talent-ai"],
            "Plateforme recrutement jeunes talents ; ATS campus, marque employeur et diffusion offres écoles.",
            ["campus_recruiting", "employer_branding", "ats", "young_talent"],
            "hybrid",
            "mid_market",
            "https://www.jobteaser.com/",
            "crunchbase",
        ),
        v(
            "beetween",
            "Beetween",
            "https://www.beetween.com/",
            ["hr-talent-ai"],
            "ATS français ; multiposting, CRM candidats, scoring et workflows recrutement PME.",
            ["ats", "multiposting", "crm_candidates", "scoring"],
            "hybrid",
            "smb",
            "https://www.beetween.com/",
            "geo_digest",
        ),
        v(
            "flatchr",
            "Flatchr",
            "https://www.flatchr.io/",
            ["hr-talent-ai"],
            "ATS PME français ; diffusion offres, pipeline candidats et cooptation digitale.",
            ["ats", "job_boards", "referral", "pipeline"],
            "hybrid",
            "smb",
            "https://www.flatchr.io/",
            "geo_digest",
        ),
        v(
            "welcom-hr",
            "Welcome to the Jungle (ATS)",
            "https://www.welcometothejungle.com/fr/solutions/ats",
            ["hr-talent-ai"],
            "ATS et marque employeur ; pages entreprise, diffusion offres et analytics recrutement.",
            ["ats", "employer_branding", "job_distribution", "analytics"],
            "hybrid",
            "mid_market",
            "https://www.welcometothejungle.com/fr/solutions/ats",
            "geo_digest",
        ),
        v(
            "people-spheres",
            "PeopleSpheres",
            "https://www.peoplespheres.com/",
            ["hr-talent-ai"],
            "Portail RH unifié ; ATS, onboarding et SIRH connectés pour mid-market français.",
            ["hr_portal", "ats", "onboarding", "sirh"],
            "enterprise_quote",
            "mid_market",
            "https://www.peoplespheres.com/",
            "geo_digest",
        ),
        v(
            "lightcast",
            "Lightcast (Emsi Burning Glass)",
            "https://lightcast.io/",
            ["hr-talent-ai", "territorial-analytics"],
            "Intelligence marché du travail ; compétences, offres/demande par territoire et workforce planning.",
            ["labour_market_intel", "skills", "workforce_planning", "analytics"],
            "enterprise_quote",
            "enterprise",
            "https://lightcast.io/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
            regions=["US", "EU"],
            notes="Référence labour market intel citée idée 0028.",
        ),
        v(
            "figures-hr",
            "Figures",
            "https://figures.hr/",
            ["hr-talent-ai"],
            "Benchmark rémunération tech/RH ; données salaires marché et analytics compensation France/EU.",
            ["compensation", "salary_benchmark", "analytics", "tech"],
            "hybrid",
            "mid_market",
            "https://figures.hr/",
            "crunchbase",
        ),
    ],
    "geospatial-gis-fr.json": [
        v(
            "geoperso",
            "GÉOPERSO",
            "https://www.geoperso.fr/",
            ["geospatial-gis-fr", "environmental-data-fr"],
            "SIG foncier agricole ; RPG, AOC, zones humides, PLU et contraintes environnementales par parcelle.",
            ["rpg", "foncier_agricole", "plu", "environmental_constraints"],
            "enterprise_quote",
            "mid_market",
            "https://www.geoperso.fr/",
            "geo_digest",
            notes="Concurrent cité idée 0026.",
        ),
        v(
            "makina-corpus",
            "Makina Corpus",
            "https://makina-corpus.com/",
            ["geospatial-gis-fr"],
            "Intégrateur SIG web ; applications Terravisu RPG×ICPE×Hub'Eau pour coopératives agricoles.",
            ["sig", "webmapping", "rpg", "custom_apps"],
            "enterprise_quote",
            "mid_market",
            "https://makina-corpus.com/",
            "geo_digest",
            notes="Concurrent cité idée 0026 (Terravisu).",
        ),
        v(
            "geoportail-urbanisme",
            "Géoportail de l'urbanisme (GPU)",
            "https://www.geoportail-urbanisme.gouv.fr/",
            ["geospatial-gis-fr"],
            "Plateforme nationales PLU/SCOT ; WFS/WMS documents urbanisme et servitudes d'utilité publique.",
            ["plu", "scot", "wfs", "urbanisme", "open_data"],
            "freemium",
            "mid_market",
            "https://www.geoportail-urbanisme.gouv.fr/",
            "official_site",
            notes="Source citée idée 0026.",
        ),
        v(
            "geofolia",
            "Geofolia (Isagri)",
            "https://www.isagri.fr/geofolia/",
            ["geospatial-gis-fr"],
            "Gestion parcellaire agricole ; cartographie assolements, IFT et alertes réglementaires phyto.",
            ["parcellaire", "agriculture", "ift", "regulatory_alerts"],
            "hybrid",
            "smb",
            "https://www.isagri.fr/geofolia/",
            "geo_digest",
            notes="Adjacent idée 0026.",
        ),
        v(
            "agreste-rpg",
            "Agreste — RPG open data",
            "https://www.data.gouv.fr/datasets/registre-parcellaire-graphique-agricole",
            ["geospatial-gis-fr"],
            "Registre parcellaire graphique ; cultures, îlots et surfaces agricoles métropole en open data.",
            ["rpg", "agriculture", "parcelles", "open_data"],
            "freemium",
            "mid_market",
            "https://www.data.gouv.fr/datasets/registre-parcellaire-graphique-agricole",
            "official_site",
            notes="Source citée idée 0026.",
        ),
        v(
            "magellium",
            "Magellium",
            "https://www.magellium.com/",
            ["geospatial-gis-fr"],
            "ESN géomatique FR ; traitement images satellitaires, SIG et portails géographiques territoriaux.",
            ["geomatique", "satellite", "sig", "territorial"],
            "enterprise_quote",
            "enterprise",
            "https://www.magellium.com/",
            "geo_digest",
        ),
        v(
            "cadastre-etalab",
            "Cadastre Etalab",
            "https://cadastre.data.gouv.fr/",
            ["geospatial-gis-fr"],
            "Parcelles cadastrales vectorielles France ; jointures PCI/RPG et fonds cartographique open data.",
            ["cadastre", "parcelles", "pci", "open_data"],
            "freemium",
            "mid_market",
            "https://cadastre.data.gouv.fr/",
            "official_site",
            notes="Source citée idées 0021/0026.",
        ),
    ],
    "environmental-data-fr.json": [
        v(
            "sandre",
            "Sandre",
            "https://www.sandre.eaufrance.fr/",
            ["environmental-data-fr"],
            "Référentiel national eau ; nomenclatures, dictionnaires et services d'échange données hydrologiques.",
            ["water", "referentiel", "nomenclatures", "api"],
            "freemium",
            "mid_market",
            "https://www.sandre.eaufrance.fr/",
            "official_site",
        ),
        v(
            "drias-climat",
            "DRIAS — Futurs climatiques",
            "https://www.drias-climat.fr/",
            ["environmental-data-fr"],
            "Portail projections climatiques France ; scénarios aléas (précipitations, températures) pour adaptation.",
            ["climate_projections", "scenarios", "adaptation", "open_data"],
            "freemium",
            "mid_market",
            "https://www.drias-climat.fr/",
            "official_site",
            notes="Source citée idée 0024.",
        ),
        v(
            "basol",
            "BASOL — Sites et sols pollués",
            "https://www.georisques.gouv.fr/donnees/basol",
            ["environmental-data-fr"],
            "Base sites et sols pollués ; anciens sites industriels et contamination pour due diligence foncière.",
            ["polluted_sites", "soil", "industrial", "open_data"],
            "freemium",
            "mid_market",
            "https://www.georisques.gouv.fr/donnees/basol",
            "official_site",
        ),
        v(
            "gaspar",
            "GASPAR — Risques majeurs",
            "https://www.georisques.gouv.fr/donnees/gaspar",
            ["environmental-data-fr"],
            "Informations administratives risques majeurs ; PPRN, communes exposées et documents réglementaires.",
            ["natural_risks", "pprn", "communes", "regulatory"],
            "freemium",
            "mid_market",
            "https://www.georisques.gouv.fr/donnees/gaspar",
            "official_site",
        ),
        v(
            "prevair",
            "PREV'AIR",
            "https://www.prevair.org/",
            ["environmental-data-fr"],
            "Prévision qualité air France ; modélisation polluants, cartes prévisionnelles et indices AQI.",
            ["air_quality", "forecast", "modeling", "aqi"],
            "freemium",
            "mid_market",
            "https://www.prevair.org/",
            "official_site",
        ),
        v(
            "atlas-risques-naturels",
            "Atlas national des risques naturels",
            "https://www.georisques.gouv.fr/risques/risques-naturels",
            ["environmental-data-fr"],
            "Cartographie nationale aléas naturels ; inondations, séismes, mouvements terrain et retrait-gonflement argiles.",
            ["natural_hazards", "flood", "seismic", "rga", "mapping"],
            "freemium",
            "mid_market",
            "https://www.georisques.gouv.fr/risques/risques-naturels",
            "official_site",
        ),
        v(
            "eau-france",
            "EauFrance",
            "https://www.eaufrance.fr/",
            ["environmental-data-fr"],
            "Portail information eau ; état ressources, nappes, rivières et indicateurs qualité par bassin.",
            ["water_resources", "groundwater", "rivers", "quality_indicators"],
            "freemium",
            "mid_market",
            "https://www.eaufrance.fr/",
            "official_site",
        ),
    ],
}

COVERAGE_UPDATES: dict[str, dict[str, dict]] = {
    "real-estate-proptech": {
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 8, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "energy-buildings-fr": {
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 6, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "territorial-analytics": {
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 20, "new_added": 6, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 4, "pass": PASS_ID},
    },
    "public-procurement-intel": {
        "official_site": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 3, "pass": PASS_ID},
    },
    "hr-talent-ai": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 5, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "geospatial-gis-fr": {
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 4, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 3, "pass": PASS_ID},
    },
    "environmental-data-fr": {
        "official_site": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 7, "pass": PASS_ID},
    },
}


def merge() -> None:
    all_ids: set[str] = set()
    for path in VENDORS_DIR.glob("*.json"):
        for vendor in json.loads(path.read_text(encoding="utf-8")).get("vendors", []):
            all_ids.add(vendor["id"])

    total = 0
    per_file: dict[str, int] = {}
    for fname, vendors in ADDITIONS.items():
        path = VENDORS_DIR / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        count = 0
        for vendor in vendors:
            if vendor["id"] in all_ids:
                print(f"skip duplicate: {vendor['id']}")
                continue
            data["vendors"].append(vendor)
            all_ids.add(vendor["id"])
            count += 1
            total += 1
        data["updated_at"] = TODAY
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        per_file[fname] = count
        print(f"updated {fname}: +{count}")

    matrix = json.loads(COVERAGE.read_text(encoding="utf-8"))
    for seg_id, sources in COVERAGE_UPDATES.items():
        entry = matrix["segments"][seg_id]
        for src, upd in sources.items():
            prev = entry["sources"].get(src) or {}
            entry["sources"][src] = {
                **upd,
                "cumulative_new": prev.get("cumulative_new", prev.get("new_added", 0)) + upd["new_added"],
            }
        entry["last_pass"] = PASS_ID
        entry["vendor_count_after_pass"] = len(
            json.loads((VENDORS_DIR / f"{seg_id}.json").read_text(encoding="utf-8"))["vendors"]
        )
    matrix["updated_at"] = TODAY
    COVERAGE.write_text(json.dumps(matrix, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"done: +{total} vendors")
    for fname, n in per_file.items():
        print(f"  {fname}: +{n}")


if __name__ == "__main__":
    merge()
