#!/usr/bin/env python3
"""Vague 5t-c — L3 workplace / sales / data / infra (11→~18 par segment)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
COVERAGE = ROOT / "catalogue-saas" / "coverage-matrix.json"
TODAY = "2026-06-23"
PASS_ID = "2026-06-v5t-workplace-l3"


def v(
    id_: str,
    name: str,
    url: str,
    segments: list[str],
    desc: str,
    caps: list[str],
    pricing: str,
    market: str,
    source: str,
    src_type: str,
    hq: str = "US",
    fr: str = "partial",
    regions: list[str] | None = None,
    geo: str = "global",
    notes: str | None = None,
) -> dict:
    d = {
        "id": id_,
        "name": name,
        "url": url,
        "segments": segments,
        "description": desc,
        "capabilities": caps,
        "pricing_model": pricing,
        "target_market": market,
        "geography": geo,
        "hq_country": hq,
        "france_market": fr,
        "operating_regions": regions or ["US", "EU"],
        "discovery_source": src_type,
        "discovery_pass": PASS_ID,
        "source_url": source,
        "source_consulted_at": TODAY,
        "verification_status": "partial",
    }
    if notes:
        d["notes"] = notes
    return d


ADDITIONS: dict[str, list[dict]] = {
    "agent-frameworks-platforms.json": [
        v(
            "mastra",
            "Mastra",
            "https://mastra.ai/",
            ["agent-frameworks-platforms"],
            "Framework TypeScript agents ; workflows, mémoire, evals et déploiement serverless.",
            ["typescript", "workflows", "memory", "evals"],
            "open_source",
            "mid_market",
            "https://mastra.ai/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "letta",
            "Letta (MemGPT)",
            "https://www.letta.com/",
            ["agent-frameworks-platforms"],
            "Plateforme agents stateful ; mémoire long terme, tool use et déploiement multi-agents.",
            ["stateful_agents", "memory", "tool_use", "multi_agent"],
            "hybrid",
            "mid_market",
            "https://www.letta.com/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "vellum",
            "Vellum",
            "https://www.vellum.ai/",
            ["agent-frameworks-platforms"],
            "Plateforme dev agents LLM ; prompt engineering, evals, déploiement et observabilité.",
            ["prompt_engineering", "evals", "deployment", "observability"],
            "hybrid",
            "mid_market",
            "https://www.vellum.ai/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "rivet-ai",
            "Rivet",
            "https://rivet.ironcladapp.com/",
            ["agent-frameworks-platforms"],
            "IDE visuel agents LLM ; graphes, debugging et intégration Ironclad workflows.",
            ["visual_ide", "agent_graphs", "debugging", "workflows"],
            "hybrid",
            "mid_market",
            "https://rivet.ironcladapp.com/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "beam-ai",
            "Beam AI",
            "https://beam.ai/",
            ["agent-frameworks-platforms"],
            "Plateforme agents enterprise ; orchestration, human-in-the-loop et intégrations SaaS.",
            ["enterprise_agents", "orchestration", "hitl", "integrations"],
            "enterprise_quote",
            "enterprise",
            "https://beam.ai/",
            "g2",
            hq="DE",
            fr="partial",
            geo="europe",
        ),
        v(
            "wordware",
            "Wordware",
            "https://www.wordware.ai/",
            ["agent-frameworks-platforms"],
            "IDE langage naturel pour agents ; déploiement API, triggers et collaboration équipe.",
            ["natural_language_ide", "api_deploy", "triggers", "collaboration"],
            "hybrid",
            "mid_market",
            "https://www.wordware.ai/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "composio",
            "Composio",
            "https://composio.dev/",
            ["agent-frameworks-platforms"],
            "Connecteurs tools agents ; 100+ intégrations SaaS, auth et actions typées pour LLM.",
            ["tool_connectors", "integrations", "auth", "typed_actions"],
            "hybrid",
            "mid_market",
            "https://composio.dev/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "botpress",
            "Botpress",
            "https://botpress.com/",
            ["agent-frameworks-platforms"],
            "Plateforme agents conversationnels ; LLM, workflows visuels et déploiement omnicanal.",
            ["conversational_agents", "visual_workflows", "llm", "omnichannel"],
            "hybrid",
            "mid_market",
            "https://botpress.com/",
            "g2",
            hq="CA",
            fr="partial",
            geo="global",
        ),
    ],
    "ai-evals-testing.json": [
        v(
            "langfuse",
            "Langfuse",
            "https://langfuse.com/",
            ["ai-evals-testing"],
            "Observabilité et evals LLM ; traces, scores, datasets et playground prompts.",
            ["tracing", "evals", "datasets", "prompt_playground"],
            "hybrid",
            "mid_market",
            "https://langfuse.com/",
            "open_source",
            hq="DE",
            fr="partial",
            geo="europe",
        ),
        v(
            "langwatch",
            "LangWatch",
            "https://langwatch.ai/",
            ["ai-evals-testing"],
            "Monitoring qualité LLM ; evals automatisés, alertes régression et analytics production.",
            ["llm_monitoring", "automated_evals", "alerts", "analytics"],
            "hybrid",
            "mid_market",
            "https://langwatch.ai/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "openlayer",
            "OpenLayer",
            "https://www.openlayer.com/",
            ["ai-evals-testing"],
            "Evals et tests ML/LLM ; scénarios, métriques custom et CI/CD intégration.",
            ["ml_evals", "llm_evals", "custom_metrics", "ci_cd"],
            "hybrid",
            "mid_market",
            "https://www.openlayer.com/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "humanloop",
            "Humanloop",
            "https://humanloop.com/",
            ["ai-evals-testing"],
            "Plateforme evals prompts ; A/B testing, feedback humain et optimisation LLM.",
            ["prompt_evals", "ab_testing", "human_feedback", "optimization"],
            "hybrid",
            "mid_market",
            "https://humanloop.com/",
            "g2",
            hq="GB",
            fr="partial",
            geo="global",
        ),
        v(
            "freeplay",
            "Freeplay",
            "https://freeplay.ai/",
            ["ai-evals-testing"],
            "Evals et observabilité GenAI ; test sets, comparaison modèles et monitoring production.",
            ["genai_evals", "test_sets", "model_comparison", "monitoring"],
            "hybrid",
            "mid_market",
            "https://freeplay.ai/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "trulens",
            "TruLens",
            "https://www.trulens.org/",
            ["ai-evals-testing"],
            "Framework evals RAG/agents open-source ; feedback functions et tracing LangChain.",
            ["rag_evals", "feedback_functions", "tracing", "open_source"],
            "open_source",
            "self_serve",
            "https://www.trulens.org/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "comet-opik",
            "Comet Opik",
            "https://www.comet.com/site/products/opik/",
            ["ai-evals-testing"],
            "Evals et traces LLM ; expériences, métriques hallucination et comparaison modèles.",
            ["llm_traces", "hallucination_metrics", "experiments", "model_comparison"],
            "hybrid",
            "mid_market",
            "https://www.comet.com/site/products/opik/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "ai-productivity.json": [
        v(
            "reflect-app",
            "Reflect",
            "https://reflect.app/",
            ["ai-productivity"],
            "Notes IA networked ; backlinks, GPT intégré et sync chiffré cross-device.",
            ["networked_notes", "gpt", "encrypted_sync", "backlinks"],
            "hybrid",
            "self_serve",
            "https://reflect.app/",
            "alternatives",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "craft-do",
            "Craft",
            "https://www.craft.do/",
            ["ai-productivity"],
            "Docs et notes IA ; rédaction assistée, templates et collaboration équipe.",
            ["ai_writing", "docs", "templates", "collaboration"],
            "hybrid",
            "smb",
            "https://www.craft.do/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "granola",
            "Granola",
            "https://www.granola.ai/",
            ["ai-productivity"],
            "Notes réunion IA ; transcription locale, synthèse action items sans bot visible.",
            ["meeting_notes", "local_transcription", "summaries", "action_items"],
            "hybrid",
            "mid_market",
            "https://www.granola.ai/",
            "crunchbase",
            hq="GB",
            fr="partial",
            geo="global",
        ),
        v(
            "tactiq",
            "Tactiq",
            "https://tactiq.io/",
            ["ai-productivity"],
            "Transcription Meet/Zoom IA ; résumés, highlights et export Notion/Docs.",
            ["meet_transcription", "summaries", "highlights", "export"],
            "freemium",
            "smb",
            "https://tactiq.io/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "superhuman",
            "Superhuman",
            "https://superhuman.com/",
            ["ai-productivity"],
            "Email IA premium ; tri intelligent, raccourcis et rédaction assistée GPT.",
            ["ai_email", "smart_triage", "shortcuts", "ai_compose"],
            "hybrid",
            "mid_market",
            "https://superhuman.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "descript",
            "Descript",
            "https://www.descript.com/",
            ["ai-productivity"],
            "Édition audio/vidéo IA ; transcription, overdub voix et montage text-based.",
            ["transcription", "overdub", "text_editing", "video_ai"],
            "hybrid",
            "smb",
            "https://www.descript.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "lex-writing",
            "Lex",
            "https://lex.page/",
            ["ai-productivity"],
            "Éditeur rédaction IA ; co-écriture, brainstorming et export long-form.",
            ["ai_writing", "co_authoring", "brainstorming", "long_form"],
            "freemium",
            "self_serve",
            "https://lex.page/",
            "alternatives",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "bi-analytics-platforms.json": [
        v(
            "microstrategy",
            "MicroStrategy",
            "https://www.microstrategy.com/",
            ["bi-analytics-platforms"],
            "BI enterprise ; dashboards, embedded analytics et IA conversational.",
            ["enterprise_bi", "dashboards", "embedded", "conversational_ai"],
            "enterprise_quote",
            "enterprise",
            "https://www.microstrategy.com/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "yellowfin-bi",
            "Yellowfin BI",
            "https://www.yellowfinbi.com/",
            ["bi-analytics-platforms"],
            "BI collaborative ; storytelling data, alertes et embedded analytics.",
            ["collaborative_bi", "storytelling", "alerts", "embedded"],
            "hybrid",
            "mid_market",
            "https://www.yellowfinbi.com/",
            "g2",
            hq="AU",
            fr="partial",
            geo="global",
        ),
        v(
            "gooddata",
            "GoodData",
            "https://www.gooddata.com/",
            ["bi-analytics-platforms"],
            "Analytics embedded ; headless BI, métriques-as-code et multi-tenant.",
            ["embedded_analytics", "headless_bi", "metrics_as_code", "multi_tenant"],
            "hybrid",
            "mid_market",
            "https://www.gooddata.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "lightdash",
            "Lightdash",
            "https://www.lightdash.com/",
            ["bi-analytics-platforms"],
            "BI open-source dbt ; métriques dbt, dashboards self-serve et dbt Cloud sync.",
            ["dbt_bi", "open_source", "self_serve", "metrics"],
            "hybrid",
            "mid_market",
            "https://www.lightdash.com/",
            "open_source",
            hq="GB",
            fr="partial",
            geo="global",
        ),
        v(
            "evidence-dev",
            "Evidence",
            "https://evidence.dev/",
            ["bi-analytics-platforms"],
            "BI as code ; rapports Markdown/SQL, dashboards statiques et dbt intégration.",
            ["bi_as_code", "markdown", "sql", "dbt"],
            "open_source",
            "mid_market",
            "https://evidence.dev/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "holistics",
            "Holistics",
            "https://www.holistics.io/",
            ["bi-analytics-platforms"],
            "Semantic layer BI ; modèles métier, self-serve et embedded analytics.",
            ["semantic_layer", "self_serve", "embedded", "modeling"],
            "hybrid",
            "mid_market",
            "https://www.holistics.io/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "preset-io",
            "Preset (Apache Superset)",
            "https://preset.io/",
            ["bi-analytics-platforms"],
            "Superset managé ; dashboards, SQL Lab et alerting cloud-hosted.",
            ["superset", "dashboards", "sql_lab", "managed"],
            "hybrid",
            "mid_market",
            "https://preset.io/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "crm-platforms.json": [
        v(
            "sugarcrm",
            "SugarCRM",
            "https://www.sugarcrm.com/",
            ["crm-platforms"],
            "CRM enterprise open-core ; ventes, marketing et service client unifiés.",
            ["sales", "marketing", "service", "open_core"],
            "hybrid",
            "mid_market",
            "https://www.sugarcrm.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "nimble-crm",
            "Nimble",
            "https://www.nimble.com/",
            ["crm-platforms"],
            "CRM social ; enrichissement contacts, inbox unifiée et intégrations réseaux.",
            ["social_crm", "contact_enrichment", "unified_inbox", "integrations"],
            "hybrid",
            "smb",
            "https://www.nimble.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "folk-crm",
            "folk",
            "https://www.folk.app/",
            ["crm-platforms"],
            "CRM moderne PME ; pipelines visuels, enrichissement auto et collaboration équipe.",
            ["visual_pipeline", "auto_enrichment", "collaboration", "modern_ui"],
            "hybrid",
            "smb",
            "https://www.folk.app/",
            "crunchbase",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — CRM léger adoption startups EU.",
        ),
        v(
            "twenty-crm",
            "Twenty",
            "https://twenty.com/",
            ["crm-platforms"],
            "CRM open-source ; alternative Salesforce, custom objects et self-hosted.",
            ["open_source", "custom_objects", "self_hosted", "modern_crm"],
            "open_source",
            "mid_market",
            "https://twenty.com/",
            "open_source",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — CRM OSS avec forte communauté EU.",
        ),
        v(
            "nocrm",
            "noCRM.io",
            "https://www.nocrm.io/",
            ["crm-platforms"],
            "CRM ventes simplifié ; pipeline leads, relances et mobile-first PME.",
            ["lead_pipeline", "follow_ups", "mobile", "simple_crm"],
            "hybrid",
            "smb",
            "https://www.nocrm.io/",
            "g2",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "capsule-crm",
            "Capsule CRM",
            "https://capsulecrm.com/",
            ["crm-platforms"],
            "CRM PME ; contacts, pipelines, automatisations légères et intégrations.",
            ["contacts", "pipelines", "light_automation", "integrations"],
            "hybrid",
            "smb",
            "https://capsulecrm.com/",
            "g2",
            hq="GB",
            fr="partial",
            geo="global",
        ),
        v(
            "less-annoying-crm",
            "Less Annoying CRM",
            "https://www.lessannoyingcrm.com/",
            ["crm-platforms"],
            "CRM ultra-simple PME ; calendrier, tâches et pipeline sans complexité.",
            ["simple_crm", "calendar", "tasks", "pipeline"],
            "hybrid",
            "smb",
            "https://www.lessannoyingcrm.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "teamleader",
            "Teamleader",
            "https://www.teamleader.eu/",
            ["crm-platforms"],
            "CRM + facturation EU ; pipeline, devis et projet pour PME Benelux/EU.",
            ["crm", "invoicing", "quotes", "project"],
            "hybrid",
            "smb",
            "https://www.teamleader.eu/",
            "g2",
            hq="BE",
            fr="partial",
            geo="europe",
            notes="Acteur EU — CRM PME Benelux.",
        ),
    ],
    "customer-success.json": [
        v(
            "skilljar",
            "Skilljar",
            "https://www.skilljar.com/",
            ["customer-success"],
            "LMS customer education ; onboarding clients, certifications et analytics.",
            ["customer_education", "onboarding", "certifications", "analytics"],
            "hybrid",
            "mid_market",
            "https://www.skilljar.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "workramp",
            "WorkRamp",
            "https://www.workramp.com/",
            ["customer-success"],
            "Plateforme enablement ; formation clients, partenaires et employés unifiée.",
            ["customer_training", "partner_enablement", "employee_lms", "analytics"],
            "hybrid",
            "mid_market",
            "https://www.workramp.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "stonly",
            "Stonly",
            "https://stonly.com/",
            ["customer-success"],
            "Guides interactifs CS ; walkthroughs in-app, KB et résolution self-service.",
            ["interactive_guides", "in_app", "knowledge_base", "self_service"],
            "hybrid",
            "mid_market",
            "https://stonly.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "userpilot",
            "Userpilot",
            "https://userpilot.com/",
            ["customer-success"],
            "Product adoption CS ; onboarding in-app, NPS et feature announcements.",
            ["in_app_onboarding", "nps", "feature_announcements", "adoption"],
            "hybrid",
            "mid_market",
            "https://userpilot.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "pendo",
            "Pendo",
            "https://www.pendo.io/",
            ["customer-success"],
            "Product analytics + CS ; guides in-app, feedback et health scoring.",
            ["product_analytics", "in_app_guides", "feedback", "health_scoring"],
            "hybrid",
            "mid_market",
            "https://www.pendo.io/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "client-success",
            "ClientSuccess",
            "https://clientsuccess.com/",
            ["customer-success"],
            "Plateforme CS B2B ; health scores, playbooks et renouvellements.",
            ["health_scores", "playbooks", "renewals", "b2b_cs"],
            "hybrid",
            "mid_market",
            "https://clientsuccess.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "gainsight-nxt",
            "Gainsight PX",
            "https://www.gainsight.com/product-experience/",
            ["customer-success"],
            "Product experience CS ; analytics in-app, guides et NPS intégré Gainsight.",
            ["product_experience", "in_app_analytics", "guides", "nps"],
            "enterprise_quote",
            "enterprise",
            "https://www.gainsight.com/product-experience/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "northpass-lms",
            "Northpass (groupe Gainsight)",
            "https://www.northpass.com/",
            ["customer-success"],
            "LMS customer success ; parcours formation clients et certifications.",
            ["customer_lms", "learning_paths", "certifications", "integrations"],
            "hybrid",
            "mid_market",
            "https://www.northpass.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "data-enrichment-b2b.json": [
        v(
            "kaspr",
            "Kaspr",
            "https://www.kaspr.io/",
            ["data-enrichment-b2b"],
            "Enrichissement LinkedIn B2B ; emails/téléphones prospects et extension Chrome.",
            ["linkedin_enrichment", "emails", "phones", "chrome_extension"],
            "hybrid",
            "smb",
            "https://www.kaspr.io/",
            "g2",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — enrichissement LinkedIn PME.",
        ),
        v(
            "dropcontact",
            "Dropcontact",
            "https://www.dropcontact.com/",
            ["data-enrichment-b2b"],
            "Enrichissement CRM RGPD ; emails pro vérifiés sans base stale, sync CRM.",
            ["gdpr_enrichment", "verified_emails", "crm_sync", "no_database"],
            "hybrid",
            "smb",
            "https://www.dropcontact.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — enrichissement conforme RGPD.",
        ),
        v(
            "fullcontact",
            "FullContact",
            "https://www.fullcontact.com/",
            ["data-enrichment-b2b"],
            "Identity resolution B2B ; profils person/enrichment API et consent management.",
            ["identity_resolution", "enrichment_api", "profiles", "consent"],
            "hybrid",
            "mid_market",
            "https://www.fullcontact.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "peopledatalabs",
            "People Data Labs",
            "https://www.peopledatalabs.com/",
            ["data-enrichment-b2b"],
            "API données personnes/entreprises ; enrichissement bulk et firmographics.",
            ["people_api", "company_api", "bulk_enrichment", "firmographics"],
            "hybrid",
            "mid_market",
            "https://www.peopledatalabs.com/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "datagma",
            "Datagma",
            "https://datagma.com/",
            ["data-enrichment-b2b"],
            "Enrichissement B2B EU ; emails, technographics et signaux intent PME.",
            ["b2b_enrichment", "technographics", "intent", "eu_data"],
            "hybrid",
            "smb",
            "https://datagma.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "reverse-contact",
            "Reverse Contact",
            "https://www.reversecontact.com/",
            ["data-enrichment-b2b"],
            "Reverse lookup email ; identification personne/entreprise depuis adresse email.",
            ["reverse_lookup", "email_identification", "company_match", "api"],
            "hybrid",
            "smb",
            "https://www.reversecontact.com/",
            "alternatives",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "adapt-io",
            "Adapt.io",
            "https://www.adapt.io/",
            ["data-enrichment-b2b"],
            "Prospecting B2B ; base contacts vérifiés, technographics et séquences.",
            ["prospecting", "verified_contacts", "technographics", "sequences"],
            "hybrid",
            "mid_market",
            "https://www.adapt.io/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "hunter-io",
            "Hunter.io",
            "https://hunter.io/",
            ["data-enrichment-b2b"],
            "Recherche emails domaine ; vérification, bulk et API enrichissement.",
            ["email_finder", "verification", "bulk", "api"],
            "freemium",
            "smb",
            "https://hunter.io/",
            "g2",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — email finder adoption EU.",
        ),
    ],
    "data-integration-etl.json": [
        v(
            "meltano",
            "Meltano",
            "https://meltano.com/",
            ["data-integration-etl"],
            "ELT open-source ; Singer taps, dbt et orchestration data ops self-hosted.",
            ["elt", "singer", "dbt", "self_hosted"],
            "open_source",
            "mid_market",
            "https://meltano.com/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "rivery",
            "Rivery",
            "https://rivery.io/",
            ["data-integration-etl"],
            "ELT cloud ; pipelines no-code, reverse ETL et gouvernance data.",
            ["elt", "no_code", "reverse_etl", "governance"],
            "hybrid",
            "mid_market",
            "https://rivery.io/",
            "g2",
            hq="IL",
            fr="partial",
            geo="global",
        ),
        v(
            "integrate-io",
            "Integrate.io",
            "https://www.integrate.io/",
            ["data-integration-etl"],
            "ETL/ELT low-code ; pipelines, API management et data warehouse sync.",
            ["etl", "low_code", "api_management", "warehouse_sync"],
            "hybrid",
            "mid_market",
            "https://www.integrate.io/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "polytomic",
            "Polytomic",
            "https://www.polytomic.com/",
            ["data-integration-etl"],
            "Sync données no-code ; ETL bidirectionnel CRM/warehouse et monitoring.",
            ["no_code_sync", "bidirectional", "crm_warehouse", "monitoring"],
            "hybrid",
            "mid_market",
            "https://www.polytomic.com/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "nexla",
            "Nexla",
            "https://www.nexla.com/",
            ["data-integration-etl"],
            "Data operations ; ingestion, transformation et gouvernance unified platform.",
            ["data_ops", "ingestion", "transformation", "governance"],
            "hybrid",
            "mid_market",
            "https://www.nexla.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "estuary",
            "Estuary",
            "https://estuary.dev/",
            ["data-integration-etl"],
            "CDC streaming ETL ; sync temps réel sources→destinations open-core.",
            ["cdc", "streaming", "real_time", "open_core"],
            "hybrid",
            "mid_market",
            "https://estuary.dev/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "hightouch",
            "Hightouch",
            "https://hightouch.com/",
            ["data-integration-etl"],
            "Reverse ETL ; sync warehouse→SaaS, audiences et composable CDP.",
            ["reverse_etl", "warehouse_sync", "audiences", "composable_cdp"],
            "hybrid",
            "mid_market",
            "https://hightouch.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "data-observability.json": [
        v(
            "metaplane",
            "Metaplane",
            "https://www.metaplane.dev/",
            ["data-observability"],
            "Observabilité data warehouse ; monitors, lineage et alertes anomalies.",
            ["warehouse_monitoring", "lineage", "anomaly_alerts", "dbt"],
            "hybrid",
            "mid_market",
            "https://www.metaplane.dev/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "datahub-project",
            "DataHub (Acryl)",
            "https://datahub.com/",
            ["data-observability"],
            "Catalogue metadata open-source ; lineage, discovery et gouvernance data.",
            ["metadata_catalog", "lineage", "discovery", "governance"],
            "hybrid",
            "mid_market",
            "https://datahub.com/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "validio",
            "Validio",
            "https://validio.io/",
            ["data-observability"],
            "Validation data automatisée ; règles ML, drift et alertes pipeline.",
            ["automated_validation", "ml_rules", "drift", "pipeline_alerts"],
            "hybrid",
            "mid_market",
            "https://validio.io/",
            "crunchbase",
            hq="SE",
            fr="partial",
            geo="europe",
        ),
        v(
            "selectstar",
            "Select Star",
            "https://www.selectstar.com/",
            ["data-observability"],
            "Data discovery ; lineage auto, documentation et search sémantique catalogue.",
            ["data_discovery", "auto_lineage", "documentation", "semantic_search"],
            "hybrid",
            "mid_market",
            "https://www.selectstar.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "observe-dqm",
            "Observe (Data Quality)",
            "https://www.observeinc.com/",
            ["data-observability"],
            "Observabilité data lake ; monitoring pipelines, coûts et qualité unifiée.",
            ["data_lake_obs", "pipeline_monitoring", "cost_tracking", "quality"],
            "hybrid",
            "mid_market",
            "https://www.observeinc.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "databand",
            "Databand (IBM)",
            "https://www.ibm.com/products/databand",
            ["data-observability"],
            "Observabilité pipelines data ; alertes SLA, lineage jobs et coûts cloud.",
            ["pipeline_obs", "sla_alerts", "job_lineage", "cloud_costs"],
            "hybrid",
            "mid_market",
            "https://www.ibm.com/products/databand",
            "analyst_report",
        ),
        v(
            "anecdotes",
            "Anecdotes",
            "https://www.anecdotes.ai/",
            ["data-observability"],
            "GRC data observability ; collecte preuves compliance, contrôles automatisés et audit.",
            ["compliance_evidence", "automated_controls", "audit", "grc"],
            "hybrid",
            "mid_market",
            "https://www.anecdotes.ai/",
            "crunchbase",
            hq="IL",
            fr="partial",
            geo="global",
        ),
    ],
    "e-signature.json": [
        v(
            "signrequest",
            "SignRequest",
            "https://signrequest.com/",
            ["e-signature"],
            "E-signature EU ; workflows simples, API et conformité eIDAS.",
            ["eidas", "workflows", "api", "simple_signing"],
            "hybrid",
            "smb",
            "https://signrequest.com/",
            "g2",
            hq="NL",
            fr="partial",
            geo="europe",
        ),
        v(
            "signwell",
            "SignWell",
            "https://www.signwell.com/",
            ["e-signature"],
            "E-signature PME ; templates, bulk send et audit trail.",
            ["templates", "bulk_send", "audit_trail", "smb"],
            "hybrid",
            "smb",
            "https://www.signwell.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "boldsign",
            "BoldSign",
            "https://boldsign.com/",
            ["e-signature"],
            "E-signature API-first ; embedded signing, webhooks et SDK.",
            ["api_first", "embedded_signing", "webhooks", "sdk"],
            "hybrid",
            "mid_market",
            "https://boldsign.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "certigna",
            "Certigna",
            "https://www.certigna.fr/",
            ["e-signature"],
            "Signature électronique qualifiée FR ; eIDAS, archivage probatoire et secteur public.",
            ["qualified_signature", "eidas", "archiving", "public_sector"],
            "hybrid",
            "mid_market",
            "https://www.certigna.fr/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — signature qualifiée eIDAS.",
        ),
        v(
            "luxtrust",
            "LuxTrust",
            "https://www.luxtrust.com/",
            ["e-signature"],
            "Identité et signature EU ; certificats qualifiés, eIDAS et secteur bancaire.",
            ["qualified_certs", "eidas", "identity", "banking"],
            "enterprise_quote",
            "enterprise",
            "https://www.luxtrust.com/",
            "official_site",
            hq="LU",
            fr="partial",
            geo="europe",
            notes="Acteur EU — trust services eIDAS.",
        ),
        v(
            "firma-eu",
            "Firma",
            "https://firma.dev/",
            ["e-signature"],
            "E-signature developer-first ; API REST, webhooks et templates JSON.",
            ["developer_api", "webhooks", "templates", "rest"],
            "hybrid",
            "mid_market",
            "https://firma.dev/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "legalesign",
            "Legalesign",
            "https://legalesign.com/",
            ["e-signature"],
            "E-signature UK/EU ; workflows, templates et conformité légale.",
            ["uk_eu_signing", "workflows", "templates", "legal_compliance"],
            "hybrid",
            "mid_market",
            "https://legalesign.com/",
            "g2",
            hq="GB",
            fr="partial",
            geo="global",
        ),
    ],
    "helpdesk-platforms.json": [
        v(
            "aircall",
            "Aircall",
            "https://aircall.io/",
            ["helpdesk-platforms"],
            "Téléphonie cloud helpdesk ; VoIP, CRM sync et analytics équipe support.",
            ["cloud_phone", "voip", "crm_sync", "support_analytics"],
            "hybrid",
            "mid_market",
            "https://aircall.io/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — téléphonie cloud PME/ETI.",
        ),
        v(
            "ringover",
            "Ringover",
            "https://www.ringover.com/",
            ["helpdesk-platforms"],
            "Centre d'appels cloud FR ; VoIP, power dialer et intégrations CRM.",
            ["cloud_contact_center", "power_dialer", "voip", "crm"],
            "hybrid",
            "mid_market",
            "https://www.ringover.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — centre d'appels cloud.",
        ),
        v(
            "diabolocom",
            "Diabolocom",
            "https://www.diabolocom.com/",
            ["helpdesk-platforms"],
            "CCaaS FR ; routage intelligent, WFM et intégration CRM omnicanal.",
            ["ccaas", "intelligent_routing", "wfm", "omnichannel"],
            "enterprise_quote",
            "enterprise",
            "https://www.diabolocom.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — CCaaS enterprise.",
        ),
        v(
            "reamaze",
            "Re:amaze",
            "https://www.reamaze.com/",
            ["helpdesk-platforms"],
            "Helpdesk e-commerce ; chat, FAQ, order management et Shopify native.",
            ["ecommerce_helpdesk", "chat", "faq", "shopify"],
            "hybrid",
            "smb",
            "https://www.reamaze.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "happyfox",
            "HappyFox",
            "https://www.happyfox.com/",
            ["helpdesk-platforms"],
            "Helpdesk IT/ops ; ticketing, knowledge base et automatisations SLA.",
            ["ticketing", "knowledge_base", "sla", "automation"],
            "hybrid",
            "mid_market",
            "https://www.happyfox.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "liveagent",
            "LiveAgent",
            "https://www.liveagent.com/",
            ["helpdesk-platforms"],
            "Helpdesk omnicanal ; chat, email, call center et social intégrés.",
            ["omnichannel", "chat", "call_center", "social"],
            "hybrid",
            "smb",
            "https://www.liveagent.com/",
            "g2",
            hq="SK",
            fr="partial",
            geo="europe",
        ),
    ],
    "llm-api-providers.json": [
        v(
            "openrouter",
            "OpenRouter",
            "https://openrouter.ai/",
            ["llm-api-providers"],
            "Agrégateur API LLM ; routing multi-modèles, fallback et billing unifié.",
            ["model_routing", "multi_model", "fallback", "unified_billing"],
            "per_usage",
            "mid_market",
            "https://openrouter.ai/",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "xai-grok-api",
            "xAI Grok API",
            "https://x.ai/api",
            ["llm-api-providers"],
            "API Grok xAI ; modèles reasoning, vision et contexte long.",
            ["grok_models", "reasoning", "vision", "long_context"],
            "per_usage",
            "mid_market",
            "https://x.ai/api",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "reka-ai",
            "Reka AI",
            "https://reka.ai/",
            ["llm-api-providers"],
            "Modèles multimodaux API ; vision, vidéo et agents enterprise.",
            ["multimodal", "vision", "video", "agents"],
            "per_usage",
            "mid_market",
            "https://reka.ai/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "openchat",
            "OpenChat",
            "https://openchat.ai/",
            ["llm-api-providers"],
            "API chat open-weight ; modèles OSS hébergés et fine-tuning.",
            ["open_weight", "hosted_models", "fine_tuning", "chat_api"],
            "per_usage",
            "mid_market",
            "https://openchat.ai/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "nvidia-nim",
            "NVIDIA NIM",
            "https://www.nvidia.com/en-us/ai/",
            ["llm-api-providers"],
            "Inference microservices NVIDIA ; modèles optimisés GPU et déploiement enterprise.",
            ["gpu_inference", "microservices", "optimized_models", "enterprise"],
            "per_usage",
            "enterprise",
            "https://www.nvidia.com/en-us/ai/",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "amazon-nova",
            "Amazon Nova",
            "https://aws.amazon.com/ai/generative-ai/nova/",
            ["llm-api-providers"],
            "Modèles Nova AWS Bedrock ; texte, image et agents via API managée.",
            ["bedrock", "text", "image", "agents"],
            "per_usage",
            "enterprise",
            "https://aws.amazon.com/ai/generative-ai/nova/",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "google-vertex-ai",
            "Google Vertex AI",
            "https://cloud.google.com/vertex-ai",
            ["llm-api-providers"],
            "Plateforme ML/LLM Google ; Gemini, fine-tuning et MLOps unifié.",
            ["gemini", "fine_tuning", "mlops", "enterprise"],
            "per_usage",
            "enterprise",
            "https://cloud.google.com/vertex-ai",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "marketing-automation.json": [
        v(
            "hubspot-marketing",
            "HubSpot Marketing Hub",
            "https://www.hubspot.com/products/marketing",
            ["marketing-automation"],
            "Marketing automation inbound ; workflows, lead scoring et analytics.",
            ["inbound", "workflows", "lead_scoring", "analytics"],
            "hybrid",
            "mid_market",
            "https://www.hubspot.com/products/marketing",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "pardot",
            "Salesforce Pardot",
            "https://www.salesforce.com/products/marketing-cloud/account-engagement/",
            ["marketing-automation"],
            "B2B marketing automation Salesforce ; nurturing, scoring et ROI.",
            ["b2b_nurturing", "scoring", "roi", "salesforce"],
            "enterprise_quote",
            "enterprise",
            "https://www.salesforce.com/products/marketing-cloud/account-engagement/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "eloqua",
            "Oracle Eloqua",
            "https://www.oracle.com/cx/marketing/automation/",
            ["marketing-automation"],
            "Marketing automation enterprise Oracle ; campagnes complexes et ABM.",
            ["enterprise_campaigns", "abm", "complex_workflows", "oracle"],
            "enterprise_quote",
            "enterprise",
            "https://www.oracle.com/cx/marketing/automation/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "sarbacane",
            "Sarbacane",
            "https://www.sarbacane.com/",
            ["marketing-automation"],
            "Marketing automation FR ; email, SMS, landing pages et RGPD natif.",
            ["email", "sms", "landing_pages", "rgpd"],
            "hybrid",
            "smb",
            "https://www.sarbacane.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — emailing PME conforme RGPD.",
        ),
        v(
            "actito",
            "Actito",
            "https://www.actito.com/",
            ["marketing-automation"],
            "CDP marketing EU ; parcours omnicanal, consent et personnalisation.",
            ["cdp", "omnichannel", "consent", "personalization"],
            "hybrid",
            "mid_market",
            "https://www.actito.com/",
            "geo_digest",
            hq="BE",
            fr="partial",
            geo="europe",
            notes="Acteur EU — marketing automation Benelux.",
        ),
        v(
            "splio",
            "Splio",
            "https://www.splio.com/",
            ["marketing-automation"],
            "CRM marketing FR ; fidélité, campagnes et data unifiée retail.",
            ["crm_marketing", "loyalty", "campaigns", "retail"],
            "hybrid",
            "mid_market",
            "https://www.splio.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — CRM marketing retail.",
        ),
        v(
            "mailjet",
            "Mailjet (Sinch)",
            "https://www.mailjet.com/",
            ["marketing-automation"],
            "Email API FR ; campagnes, transactional et deliverability EU.",
            ["email_api", "transactional", "campaigns", "deliverability"],
            "hybrid",
            "mid_market",
            "https://www.mailjet.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Acteur FR — email API Sinch.",
        ),
    ],
    "meeting-intelligence.json": [
        v(
            "fellow-app",
            "Fellow.app",
            "https://fellow.app/",
            ["meeting-intelligence"],
            "Gestion réunions ; agendas, notes action items et intégrations calendrier.",
            ["meeting_agendas", "action_items", "calendar", "1on1"],
            "hybrid",
            "mid_market",
            "https://fellow.app/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "hypercontext",
            "Hypercontext",
            "https://hypercontext.com/",
            ["meeting-intelligence"],
            "1:1 et réunions équipe ; agendas structurés, feedback et goals.",
            ["one_on_one", "team_meetings", "feedback", "goals"],
            "hybrid",
            "mid_market",
            "https://hypercontext.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "range-co",
            "Range",
            "https://www.range.co/",
            ["meeting-intelligence"],
            "Standups async ; check-ins équipe, intégrations Slack et focus time.",
            ["async_standups", "check_ins", "slack", "focus_time"],
            "hybrid",
            "mid_market",
            "https://www.range.co/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "jamie-ai",
            "Jamie (AI)",
            "https://www.meetjamie.ai/",
            ["meeting-intelligence"],
            "Assistant réunion IA EU ; notes privées, résumés et action items locaux.",
            ["ai_meeting_notes", "private", "summaries", "action_items"],
            "hybrid",
            "mid_market",
            "https://www.meetjamie.ai/",
            "geo_digest",
            hq="DE",
            fr="partial",
            geo="europe",
        ),
        v(
            "clari-copilot",
            "Clari Copilot",
            "https://www.clari.com/products/copilot/",
            ["meeting-intelligence"],
            "Meeting intelligence revenue ; coaching appels, deal insights et CRM sync.",
            ["call_coaching", "deal_insights", "crm_sync", "revenue"],
            "enterprise_quote",
            "enterprise",
            "https://www.clari.com/products/copilot/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "salesloft-conversations",
            "Salesloft Conversations",
            "https://salesloft.com/platform/conversations",
            ["meeting-intelligence"],
            "Conversation intelligence ; enregistrement, coaching et analytics ventes.",
            ["conversation_intel", "recording", "coaching", "sales_analytics"],
            "hybrid",
            "mid_market",
            "https://salesloft.com/platform/conversations",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "outreach-kaia",
            "Outreach Kaia",
            "https://www.outreach.io/product/kaia",
            ["meeting-intelligence"],
            "Meeting intelligence ventes ; transcription live, battlecards et CRM.",
            ["live_transcription", "battlecards", "crm", "sales"],
            "hybrid",
            "mid_market",
            "https://www.outreach.io/product/kaia",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "model-inference-hosting.json": [
        v(
            "coreweave",
            "CoreWeave",
            "https://coreweave.com/",
            ["model-inference-hosting"],
            "GPU cloud inference ; clusters NVIDIA, autoscaling et ML workloads.",
            ["gpu_cloud", "nvidia", "autoscaling", "ml_workloads"],
            "per_usage",
            "mid_market",
            "https://coreweave.com/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "lambda-labs",
            "Lambda Labs",
            "https://lambdalabs.com/",
            ["model-inference-hosting"],
            "GPU cloud ; instances A100/H100, inference API et fine-tuning.",
            ["gpu_instances", "inference_api", "fine_tuning", "h100"],
            "per_usage",
            "mid_market",
            "https://lambdalabs.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "cerebras",
            "Cerebras",
            "https://cerebras.ai/",
            ["model-inference-hosting"],
            "Inference wafer-scale ; modèles LLM ultra-rapides via API Cerebras.",
            ["wafer_scale", "fast_inference", "llm_api", "enterprise"],
            "per_usage",
            "enterprise",
            "https://cerebras.ai/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "sambanova",
            "SambaNova",
            "https://sambanova.ai/",
            ["model-inference-hosting"],
            "Inference enterprise ; RDU chips, modèles propriétaires et on-prem.",
            ["rdu", "enterprise_inference", "on_prem", "custom_models"],
            "enterprise_quote",
            "enterprise",
            "https://sambanova.ai/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "nebius",
            "Nebius",
            "https://nebius.com/",
            ["model-inference-hosting"],
            "Cloud GPU EU ; inference LLM, fine-tuning et souveraineté data europe.",
            ["eu_gpu", "llm_inference", "fine_tuning", "data_sovereignty"],
            "per_usage",
            "mid_market",
            "https://nebius.com/",
            "geo_digest",
            hq="NL",
            fr="partial",
            geo="europe",
            notes="Acteur EU — cloud GPU souveraineté.",
        ),
        v(
            "cloudflare-workers-ai",
            "Cloudflare Workers AI",
            "https://developers.cloudflare.com/workers-ai/",
            ["model-inference-hosting"],
            "Inference edge ; modèles serverless, low latency et Workers intégration.",
            ["edge_inference", "serverless", "low_latency", "workers"],
            "per_usage",
            "mid_market",
            "https://developers.cloudflare.com/workers-ai/",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "google-vertex-inference",
            "Google Vertex AI (Inference)",
            "https://cloud.google.com/vertex-ai/docs/predictions/overview",
            ["model-inference-hosting"],
            "Endpoint inference managé ; autoscaling, monitoring et multi-framework.",
            ["managed_endpoints", "autoscaling", "monitoring", "multi_framework"],
            "per_usage",
            "enterprise",
            "https://cloud.google.com/vertex-ai/docs/predictions/overview",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "project-work-management.json": [
        v(
            "jira-atlassian",
            "Jira",
            "https://www.atlassian.com/software/jira",
            ["project-work-management"],
            "Gestion projet agile ; sprints, backlogs, roadmaps et intégrations dev.",
            ["agile", "sprints", "backlogs", "roadmaps"],
            "hybrid",
            "mid_market",
            "https://www.atlassian.com/software/jira",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "trello",
            "Trello",
            "https://trello.com/",
            ["project-work-management"],
            "Kanban visuel ; boards, automatisations Butler et Power-Ups.",
            ["kanban", "boards", "butler_automation", "power_ups"],
            "freemium",
            "smb",
            "https://trello.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "shortcut",
            "Shortcut (ex-Clubhouse)",
            "https://shortcut.com/",
            ["project-work-management"],
            "Gestion projet dev ; stories, sprints et roadmap produit unifiée.",
            ["dev_project", "stories", "sprints", "roadmap"],
            "hybrid",
            "mid_market",
            "https://shortcut.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "productboard",
            "Productboard",
            "https://www.productboard.com/",
            ["project-work-management"],
            "Gestion produit ; roadmaps, prioritisation feedback et discovery.",
            ["product_roadmaps", "prioritization", "feedback", "discovery"],
            "hybrid",
            "mid_market",
            "https://www.productboard.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "hive-app",
            "Hive",
            "https://hive.com/",
            ["project-work-management"],
            "Work management ; projets, time tracking et proofing créatif.",
            ["projects", "time_tracking", "proofing", "collaboration"],
            "hybrid",
            "mid_market",
            "https://hive.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "zoho-projects",
            "Zoho Projects",
            "https://www.zoho.com/projects/",
            ["project-work-management"],
            "Gestion projet PME ; tâches, Gantt, timesheets et intégrations Zoho.",
            ["tasks", "gantt", "timesheets", "zoho_suite"],
            "hybrid",
            "smb",
            "https://www.zoho.com/projects/",
            "g2",
            hq="IN",
            fr="partial",
            geo="global",
        ),
        v(
            "notion-projects",
            "Notion Projects",
            "https://www.notion.so/product/projects",
            ["project-work-management"],
            "Projets dans Notion ; vues timeline, sprints et bases de données liées.",
            ["notion_projects", "timeline", "sprints", "linked_db"],
            "hybrid",
            "mid_market",
            "https://www.notion.so/product/projects",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "revenue-intelligence.json": [
        v(
            "revenue-grid",
            "Revenue Grid",
            "https://revenuegrid.com/",
            ["revenue-intelligence"],
            "Revenue orchestration ; guided selling, CRM automation et forecasting.",
            ["guided_selling", "crm_automation", "forecasting", "orchestration"],
            "hybrid",
            "mid_market",
            "https://revenuegrid.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "wingman",
            "Wingman (Clari)",
            "https://www.clari.com/",
            ["revenue-intelligence"],
            "Conversation intelligence ; coaching live, deal risk et playbook ventes.",
            ["conversation_intel", "live_coaching", "deal_risk", "playbooks"],
            "hybrid",
            "mid_market",
            "https://www.clari.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "common-room",
            "Common Room",
            "https://www.commonroom.io/",
            ["revenue-intelligence"],
            "Revenue intelligence community ; signaux product-led et scoring accounts.",
            ["community_signals", "product_led", "account_scoring", "intent"],
            "hybrid",
            "mid_market",
            "https://www.commonroom.io/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "revenue-base",
            "RevenueBase",
            "https://www.revenuebase.ai/",
            ["revenue-intelligence"],
            "Pipeline intelligence IA ; deal inspection, risk alerts et CRM enrichi.",
            ["pipeline_intel", "deal_inspection", "risk_alerts", "crm_enrichment"],
            "hybrid",
            "mid_market",
            "https://www.revenuebase.ai/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "mindtickle",
            "Mindtickle",
            "https://www.mindtickle.com/",
            ["revenue-intelligence"],
            "Sales readiness ; enablement, coaching et revenue intelligence intégré.",
            ["sales_readiness", "enablement", "coaching", "revenue_intel"],
            "hybrid",
            "mid_market",
            "https://www.mindtickle.com/",
            "g2",
            hq="IN",
            fr="partial",
            geo="global",
        ),
        v(
            "salesloft",
            "Salesloft",
            "https://salesloft.com/",
            ["revenue-intelligence"],
            "Sales engagement + intelligence ; séquences, dialer et conversation analytics.",
            ["sales_engagement", "sequences", "dialer", "analytics"],
            "hybrid",
            "mid_market",
            "https://salesloft.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "outreach",
            "Outreach",
            "https://www.outreach.io/",
            ["revenue-intelligence"],
            "Sales execution platform ; sequences, meeting intel Kaia et forecasting.",
            ["sequences", "meeting_intel", "forecasting", "execution"],
            "hybrid",
            "mid_market",
            "https://www.outreach.io/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "rpa-enterprise.json": [
        v(
            "sap-build-rpa",
            "SAP Build Process Automation",
            "https://www.sap.com/products/technology-platform/process-automation.html",
            ["rpa-enterprise"],
            "RPA SAP ; workflows low-code, bots et intégration S/4HANA.",
            ["sap_rpa", "low_code", "bots", "s4hana"],
            "enterprise_quote",
            "enterprise",
            "https://www.sap.com/products/technology-platform/process-automation.html",
            "analyst_report",
            hq="DE",
            fr="partial",
            geo="europe",
        ),
        v(
            "ibm-rpa",
            "IBM Robotic Process Automation",
            "https://www.ibm.com/products/robotic-process-automation",
            ["rpa-enterprise"],
            "RPA IBM ; bots unattended, orchestration et Watson intégration.",
            ["unattended_bots", "orchestration", "watson", "enterprise"],
            "enterprise_quote",
            "enterprise",
            "https://www.ibm.com/products/robotic-process-automation",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "workato-rpa",
            "Workato",
            "https://www.workato.com/",
            ["rpa-enterprise"],
            "Automation enterprise ; iPaaS, RPA léger et recipes pré-construites.",
            ["ipaas", "light_rpa", "recipes", "enterprise"],
            "hybrid",
            "mid_market",
            "https://www.workato.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "hyland-rpa",
            "Hyland RPA",
            "https://www.hyland.com/",
            ["rpa-enterprise"],
            "RPA document-centric ; extraction, workflows et content services.",
            ["document_rpa", "extraction", "workflows", "content_services"],
            "enterprise_quote",
            "enterprise",
            "https://www.hyland.com/",
            "analyst_report",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "automation-edge",
            "Automation Edge",
            "https://automationedge.com/",
            ["rpa-enterprise"],
            "RPA + AI enterprise ; bots, IDP et hyperautomation mid-market.",
            ["rpa", "idp", "hyperautomation", "mid_market"],
            "hybrid",
            "mid_market",
            "https://automationedge.com/",
            "g2",
            hq="IN",
            fr="partial",
            geo="global",
        ),
        v(
            "softomotive",
            "Softomotive (Microsoft)",
            "https://www.microsoft.com/en-us/power-platform/products/power-automate",
            ["rpa-enterprise"],
            "WinAutomation RPA desktop ; scripts UI et intégration Power Platform.",
            ["desktop_rpa", "ui_automation", "power_platform", "scripts"],
            "hybrid",
            "mid_market",
            "https://www.microsoft.com/en-us/power-platform/products/power-automate",
            "official_site",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "rocketbot",
            "Rocketbot",
            "https://rocketbot.com/",
            ["rpa-enterprise"],
            "RPA open-source LATAM/EU ; studio visuel, orchestrateur et low-cost.",
            ["open_source_rpa", "visual_studio", "orchestrator", "low_cost"],
            "hybrid",
            "smb",
            "https://rocketbot.com/",
            "open_source",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "seo-content-ai.json": [
        v(
            "content-at-scale",
            "Content at Scale",
            "https://contentatscale.ai/",
            ["seo-content-ai"],
            "Génération articles SEO long-form ; research, structure et optimisation.",
            ["long_form", "seo_research", "structure", "optimization"],
            "hybrid",
            "smb",
            "https://contentatscale.ai/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "originality-ai",
            "Originality.ai",
            "https://originality.ai/",
            ["seo-content-ai"],
            "Détection contenu IA + SEO ; plagiarism, fact-check et scoring.",
            ["ai_detection", "plagiarism", "fact_check", "scoring"],
            "hybrid",
            "smb",
            "https://originality.ai/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "surgegraph",
            "SurgeGraph",
            "https://surgegraph.io/",
            ["seo-content-ai"],
            "SEO content IA ; topical maps, clustering et rédaction optimisée.",
            ["topical_maps", "clustering", "ai_writing", "seo"],
            "hybrid",
            "smb",
            "https://surgegraph.io/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "byword-ai",
            "Byword",
            "https://byword.ai/",
            ["seo-content-ai"],
            "Articles SEO programmatiques ; bulk generation et intégrations CMS.",
            ["programmatic_seo", "bulk_generation", "cms", "articles"],
            "hybrid",
            "smb",
            "https://byword.ai/",
            "alternatives",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "growthbar",
            "GrowthBar",
            "https://www.growthbarseo.com/",
            ["seo-content-ai"],
            "SEO toolkit IA ; keyword research, outline et rédaction Chrome.",
            ["keyword_research", "outline", "ai_writing", "chrome"],
            "hybrid",
            "smb",
            "https://www.growthbarseo.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "inkforall",
            "INK For All",
            "https://inkforall.com/",
            ["seo-content-ai"],
            "SEO writing IA ; score optimisation, clustering et content planner.",
            ["seo_score", "clustering", "content_planner", "ai_writing"],
            "hybrid",
            "smb",
            "https://inkforall.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "copymatic",
            "Copymatic",
            "https://copymatic.ai/",
            ["seo-content-ai"],
            "Génération contenu SEO ; templates, bulk et intégrations WordPress.",
            ["content_generation", "templates", "bulk", "wordpress"],
            "freemium",
            "smb",
            "https://copymatic.ai/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
    "spend-procurement.json": [
        v(
            "pleo",
            "Pleo",
            "https://www.pleo.io/",
            ["spend-procurement"],
            "Cartes dépenses EU ; contrôle spend, receipts et comptabilité intégrée.",
            ["expense_cards", "spend_control", "receipts", "accounting"],
            "hybrid",
            "mid_market",
            "https://www.pleo.io/",
            "geo_digest",
            hq="DK",
            fr="partial",
            geo="europe",
            notes="Acteur EU — spend management PME.",
        ),
        v(
            "payhawk",
            "Payhawk",
            "https://payhawk.com/",
            ["spend-procurement"],
            "Spend management EU ; cartes corporate, approvals et ERP sync.",
            ["corporate_cards", "approvals", "erp_sync", "spend_management"],
            "hybrid",
            "mid_market",
            "https://payhawk.com/",
            "geo_digest",
            hq="BG",
            fr="partial",
            geo="europe",
            notes="Acteur EU — spend management scale-up.",
        ),
        v(
            "soldo",
            "Soldo",
            "https://www.soldo.com/",
            ["spend-procurement"],
            "Cartes dépenses UK/EU ; multi-utilisateur, budgets et export compta.",
            ["multi_user_cards", "budgets", "accounting_export", "eu"],
            "hybrid",
            "mid_market",
            "https://www.soldo.com/",
            "g2",
            hq="GB",
            fr="partial",
            geo="europe",
        ),
        v(
            "mesh-payments",
            "Mesh Payments",
            "https://www.meshpayments.com/",
            ["spend-procurement"],
            "Spend management startup ; cartes virtuelles, budgets et SaaS tracking.",
            ["virtual_cards", "budgets", "saas_tracking", "startup"],
            "hybrid",
            "mid_market",
            "https://www.meshpayments.com/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "tropic",
            "Tropic",
            "https://www.tropicapp.io/",
            ["spend-procurement"],
            "SaaS procurement ; négociation contrats, renewals et spend analytics.",
            ["saas_procurement", "negotiation", "renewals", "spend_analytics"],
            "hybrid",
            "mid_market",
            "https://www.tropicapp.io/",
            "crunchbase",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "precoro",
            "Precoro",
            "https://precoro.com/",
            ["spend-procurement"],
            "Procurement PME ; PO, approvals, budgets et three-way matching.",
            ["purchase_orders", "approvals", "budgets", "three_way_match"],
            "hybrid",
            "mid_market",
            "https://precoro.com/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
        v(
            "order-co",
            "Order.co",
            "https://order.co/",
            ["spend-procurement"],
            "Procurement unifié ; catalogues, approvals et paiements centralisés.",
            ["unified_procurement", "catalogs", "approvals", "payments"],
            "hybrid",
            "mid_market",
            "https://order.co/",
            "g2",
            hq="US",
            fr="partial",
            geo="global",
        ),
    ],
}

SEGMENT_PATCHES: dict[str, list[str]] = {
    "atlan": ["data-observability"],
    "automation-hero": ["rpa-enterprise"],
    "chorus-ai": ["meeting-intelligence"],
    "dixa": ["helpdesk-platforms"],
    "fiddler-ai": ["ai-evals-testing"],
    "gladly": ["helpdesk-platforms"],
    "gong": ["meeting-intelligence"],
    "laiye": ["rpa-enterprise"],
    "microsoft-power-automate": ["rpa-enterprise"],
    "otter-ai": ["meeting-intelligence"],
    "pigment": ["bi-analytics-platforms"],
    "prefect": ["data-integration-etl"],
    "stack-ai": ["agent-frameworks-platforms"],
    "toucan-toco": ["bi-analytics-platforms"],
    "whylabs": ["ai-evals-testing"],
}

COVERAGE_UPDATES: dict[str, dict[str, dict]] = {
    "agent-frameworks-platforms": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 42,
            "new_added": 4,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 21,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "ai-evals-testing": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "ai-productivity": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "bi-analytics-platforms": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "crm-platforms": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 42,
            "new_added": 4,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 21,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "customer-success": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 42,
            "new_added": 4,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 21,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "data-enrichment-b2b": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 42,
            "new_added": 4,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 21,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 16,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "data-integration-etl": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "data-observability": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 30,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 10,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 13,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "e-signature": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "helpdesk-platforms": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 34,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 17,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 12,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "llm-api-providers": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "marketing-automation": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "meeting-intelligence": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "model-inference-hosting": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "project-work-management": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "revenue-intelligence": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "rpa-enterprise": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "seo-content-ai": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
    "spend-procurement": {
        "g2": {
            "consulted_at": "2026-06-23",
            "candidates_found": 38,
            "new_added": 3,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "geo_digest": {
            "consulted_at": "2026-06-23",
            "candidates_found": 19,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "crunchbase": {
            "consulted_at": "2026-06-23",
            "candidates_found": 14,
            "new_added": 2,
            "pass": "2026-06-v5t-workplace-l3",
        },
        "analyst_report": {
            "consulted_at": "2026-06-23",
            "candidates_found": 15,
            "new_added": 1,
            "pass": "2026-06-v5t-workplace-l3",
        },
    },
}

TARGET_LEVELS = {
    "agent-frameworks-platforms": "L3",
    "ai-evals-testing": "L3",
    "ai-productivity": "L3",
    "bi-analytics-platforms": "L3",
    "crm-platforms": "L3",
    "customer-success": "L3",
    "data-enrichment-b2b": "L3",
    "data-integration-etl": "L3",
    "data-observability": "L3",
    "e-signature": "L3",
    "helpdesk-platforms": "L3",
    "llm-api-providers": "L3",
    "marketing-automation": "L3",
    "meeting-intelligence": "L3",
    "model-inference-hosting": "L3",
    "project-work-management": "L3",
    "revenue-intelligence": "L3",
    "rpa-enterprise": "L3",
    "seo-content-ai": "L3",
    "spend-procurement": "L3",
}


def patch_segments() -> int:
    patched = 0
    for path in VENDORS_DIR.glob("*.json"):
        data = json.loads(path.read_text(encoding="utf-8"))
        changed = False
        for vendor in data.get("vendors", []):
            extra = SEGMENT_PATCHES.get(vendor["id"])
            if not extra:
                continue
            for seg in extra:
                if seg not in vendor["segments"]:
                    vendor["segments"].append(seg)
                    changed = True
                    patched += 1
        if changed:
            data["updated_at"] = TODAY
            path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return patched


def merge() -> None:
    all_ids: set[str] = set()
    for path in VENDORS_DIR.glob("*.json"):
        for vendor in json.loads(path.read_text(encoding="utf-8")).get("vendors", []):
            all_ids.add(vendor["id"])

    total = 0
    per_file: dict[str, int] = {}
    for fname, vendors in ADDITIONS.items():
        path = VENDORS_DIR / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        count = 0
        for vendor in vendors:
            if vendor["id"] in all_ids:
                print(f"skip duplicate: {vendor['id']}")
                continue
            data["vendors"].append(vendor)
            all_ids.add(vendor["id"])
            count += 1
            total += 1
        data["updated_at"] = TODAY
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        per_file[fname] = count
        print(f"updated {fname}: +{count}")

    patched = patch_segments()
    if patched:
        print(f"segment patches: +{patched}")

    matrix = json.loads(COVERAGE.read_text(encoding="utf-8"))
    for seg_id, sources in COVERAGE_UPDATES.items():
        entry = matrix["segments"][seg_id]
        for src, upd in sources.items():
            prev = entry["sources"].get(src) or {}
            entry["sources"][src] = {
                **upd,
                "cumulative_new": prev.get("cumulative_new", prev.get("new_added", 0)) + upd["new_added"],
            }
        entry["last_pass"] = PASS_ID
        entry["target_level"] = TARGET_LEVELS.get(seg_id, entry.get("target_level", "L2"))
        entry["vendor_count_after_pass"] = len(
            json.loads((VENDORS_DIR / f"{seg_id}.json").read_text(encoding="utf-8"))["vendors"]
        )
    matrix["updated_at"] = TODAY
    COVERAGE.write_text(json.dumps(matrix, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"done: +{total} vendors")
    for fname, n in per_file.items():
        print(f"  {fname}: +{n}")


if __name__ == "__main__":
    merge()

