#!/usr/bin/env python3
"""Vague 5d — équivalents internationaux segments france-public et france-open-data."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
COVERAGE = ROOT / "catalogue-saas" / "coverage-matrix.json"
TODAY = "2026-06-22"
PASS_ID = "2026-06-v5d-france-intl"


def v(
    id_: str,
    name: str,
    url: str,
    segments: list[str],
    desc: str,
    caps: list[str],
    pricing: str,
    market: str,
    source: str,
    src_type: str,
    hq: str,
    fr: str = "absent",
    regions: list[str] | None = None,
    geo: str = "global",
    status: str = "partial",
    notes: str | None = None,
) -> dict:
    d = {
        "id": id_,
        "name": name,
        "url": url,
        "segments": segments,
        "description": desc,
        "capabilities": caps,
        "pricing_model": pricing,
        "target_market": market,
        "geography": geo,
        "hq_country": hq,
        "france_market": fr,
        "operating_regions": regions or ["US", "EU"],
        "discovery_source": src_type,
        "discovery_pass": PASS_ID,
        "source_url": source,
        "source_consulted_at": TODAY,
        "verification_status": status,
    }
    if notes:
        d["notes"] = notes
    return d


BENCH = "Équivalent international pour benchmark — hors marché FR principal."

ADDITIONS: dict[str, list[dict]] = {
    "public-procurement-intel.json": [
        v(
            "tussell",
            "Tussell",
            "https://www.tussell.com/",
            ["public-procurement-intel"],
            "Intelligence marchés publics UK ; veille contrats gov, attributaires et tendances sectorielles.",
            ["uk_procurement", "contract_alerts", "spend_analysis", "suppliers"],
            "enterprise_quote",
            "enterprise",
            "https://www.tussell.com/",
            "geo_digest",
            "GB",
            notes=BENCH,
        ),
        v(
            "spend-network",
            "Spend Network",
            "https://spendnetwork.com/",
            ["public-procurement-intel"],
            "Données marchés publics globaux ; API contrats et analytics achats publics multi-pays.",
            ["public_contracts_api", "global_coverage", "spend_data"],
            "enterprise_quote",
            "enterprise",
            "https://spendnetwork.com/",
            "crunchbase",
            "GB",
            notes=BENCH,
        ),
        v(
            "govwin-deltek",
            "GovWin (Deltek)",
            "https://www.deltek.com/en/govwin",
            ["public-procurement-intel"],
            "Veille opportunités marchés publics US fédéraux et locaux ; forecasting et intelligence.",
            ["federal_contracts", "forecasting", "pipeline", "us_public_sector"],
            "enterprise_quote",
            "enterprise",
            "https://www.deltek.com/en/govwin",
            "g2",
            "US",
            notes=BENCH,
        ),
        v(
            "open-contracting-partnership",
            "Open Contracting Partnership",
            "https://www.open-contracting.org/",
            ["public-procurement-intel"],
            "Standard open contracting (OCDS) et portails transparence achats publics internationaux.",
            ["ocds", "transparency", "open_data", "standards"],
            "freemium",
            "mid_market",
            "https://www.open-contracting.org/",
            "official_site",
            "GB",
            fr="unknown",
            regions=["global"],
            notes=BENCH,
        ),
    ],
    "territorial-analytics.json": [
        v(
            "data-gov-uk",
            "data.gov.uk",
            "https://www.data.gov.uk/",
            ["territorial-analytics"],
            "Portail open data national UK ; jeux territoriaux, stats locales et API CKAN.",
            ["open_data_portal", "uk", "ckan", "local_stats"],
            "freemium",
            "mid_market",
            "https://www.data.gov.uk/",
            "official_site",
            "GB",
            notes=BENCH,
        ),
        v(
            "ons-uk",
            "Office for National Statistics (UK)",
            "https://www.ons.gov.uk/",
            ["territorial-analytics"],
            "Statistiques officielles UK ; indicateurs territoriaux, démographie et économie régionale.",
            ["official_statistics", "regional_indicators", "uk"],
            "freemium",
            "mid_market",
            "https://www.ons.gov.uk/",
            "official_site",
            "GB",
            notes=BENCH,
        ),
        v(
            "eurostat-regional",
            "Eurostat — Regional Statistics",
            "https://ec.europa.eu/eurostat/web/regions",
            ["territorial-analytics"],
            "Statistiques régionales EU NUTS ; comparables territoriaux transfrontaliers incl. France.",
            ["nuts", "eu_regional", "comparative_stats", "open_data"],
            "freemium",
            "mid_market",
            "https://ec.europa.eu/eurostat/web/regions",
            "official_site",
            "EU",
            fr="partial",
            regions=["EU"],
            notes="Référence EU — comparable aux observatoires territoriaux FR.",
        ),
        v(
            "carto-territorial",
            "CARTO",
            "https://carto.com/",
            ["territorial-analytics"],
            "Plateforme spatial analytics ; dashboards territoriaux et analyse géolocalisée pour secteur public.",
            ["spatial_analytics", "dashboards", "gis", "public_sector"],
            "enterprise_quote",
            "enterprise",
            "https://carto.com/",
            "g2",
            "ES",
            fr="partial",
            regions=["ES", "EU", "US"],
            notes=BENCH,
        ),
    ],
    "civic-tech-fr.json": [
        v(
            "citizenlab",
            "CitizenLab",
            "https://www.citizenlab.co/",
            ["civic-tech-fr"],
            "Plateforme participation citoyenne ; consultations, budgets participatifs et engagement digital.",
            ["participatory_budget", "consultations", "engagement"],
            "enterprise_quote",
            "mid_market",
            "https://www.citizenlab.co/",
            "geo_digest",
            "BE",
            fr="partial",
            regions=["BE", "EU"],
            notes=BENCH,
        ),
        v(
            "consul-project",
            "CONSUL Democracy",
            "https://consulproject.org/",
            ["civic-tech-fr"],
            "Framework open-source participation citoyenne (Madrid) ; budgets participatifs et votes.",
            ["open_source", "participatory_budget", "voting", "consultations"],
            "open_source",
            "mid_market",
            "https://consulproject.org/",
            "open_source",
            "ES",
            fr="partial",
            regions=["ES", "EU", "LATAM"],
            notes=BENCH,
        ),
        v(
            "bang-the-table",
            "Bang the Table (EngagementHQ)",
            "https://www.bangthetable.com/",
            ["civic-tech-fr"],
            "Engagement citoyen digital ; consultations, sondages et cartes participatives (AU/UK/US).",
            ["community_engagement", "surveys", "mapping", "consultations"],
            "enterprise_quote",
            "mid_market",
            "https://www.bangthetable.com/",
            "g2",
            "AU",
            notes=BENCH,
        ),
        v(
            "commonplace-uk",
            "Commonplace",
            "https://www.commonplace.is/",
            ["civic-tech-fr"],
            "Engagement communautaire UK ; concertation urbaine et participation aménagement.",
            ["urban_engagement", "consultations", "community_feedback", "uk"],
            "enterprise_quote",
            "mid_market",
            "https://www.commonplace.is/",
            "geo_digest",
            "GB",
            notes=BENCH,
        ),
        v(
            "polis-co",
            "Polis",
            "https://pol.is/",
            ["civic-tech-fr"],
            "Outil délibération à grande échelle ; cartographie consensus opinions (usage gov/civic).",
            ["deliberation", "consensus_mapping", "civic_dialogue"],
            "freemium",
            "mid_market",
            "https://pol.is/",
            "alternatives",
            "US",
            notes=BENCH,
        ),
    ],
    "geospatial-gis-fr.json": [
        v(
            "ordnance-survey",
            "Ordnance Survey",
            "https://www.ordnancesurvey.co.uk/",
            ["geospatial-gis-fr"],
            "Agence mapping nationale UK ; fonds cartographiques, APIs et services géospatiaux officiels.",
            ["national_mapping", "api", "basemaps", "uk"],
            "hybrid",
            "enterprise",
            "https://www.ordnancesurvey.co.uk/",
            "official_site",
            "GB",
            notes=BENCH,
        ),
        v(
            "esri-arcgis",
            "Esri ArcGIS",
            "https://www.esri.com/",
            ["geospatial-gis-fr"],
            "Suite SIG leader mondial ; portails carto, analyse spatiale et open data hubs.",
            ["gis", "arcgis", "spatial_analysis", "hubs"],
            "enterprise_quote",
            "enterprise",
            "https://www.esri.com/",
            "analyst_report",
            "US",
            fr="partial",
            notes=BENCH,
        ),
        v(
            "mapbox",
            "Mapbox",
            "https://www.mapbox.com/",
            ["geospatial-gis-fr"],
            "Plateforme cartographie et tiles ; APIs géospatiales pour apps mobilité et territorial.",
            ["maps_api", "tiles", "geocoding", "visualization"],
            "hybrid",
            "mid_market",
            "https://www.mapbox.com/",
            "g2",
            "US",
            fr="partial",
            notes=BENCH,
        ),
        v(
            "here-technologies",
            "HERE Technologies",
            "https://www.here.com/",
            ["geospatial-gis-fr"],
            "Données localisation et cartographie ; fonds routiers et services géo pour secteur public.",
            ["location_platform", "routing", "map_data", "public_sector"],
            "enterprise_quote",
            "enterprise",
            "https://www.here.com/",
            "crunchbase",
            "NL",
            fr="partial",
            regions=["NL", "EU", "US"],
            notes=BENCH,
        ),
    ],
    "transport-mobility-data-fr.json": [
        v(
            "tfl-open-data",
            "Transport for London — Open Data",
            "https://tfl.gov.uk/info-for/open-data-users/",
            ["transport-mobility-data-fr"],
            "Portail open data mobilité Londres ; GTFS, temps réel et APIs transport public.",
            ["gtfs", "real_time", "uk", "open_data"],
            "freemium",
            "mid_market",
            "https://tfl.gov.uk/info-for/open-data-users/",
            "official_site",
            "GB",
            notes=BENCH,
        ),
        v(
            "mobilitydata-org",
            "MobilityData",
            "https://mobilitydata.org/",
            ["transport-mobility-data-fr"],
            "Gouvernance standards mobilité (GTFS, GBFS, MDS) ; catalogues et outils open data global.",
            ["gtfs", "gbfs", "mds", "standards"],
            "freemium",
            "mid_market",
            "https://mobilitydata.org/",
            "open_source",
            "US",
            fr="unknown",
            regions=["global"],
            notes=BENCH,
        ),
        v(
            "transit-land",
            "Transitland",
            "https://www.transit.land/",
            ["transport-mobility-data-fr"],
            "Agrégateur open data transport mondial ; GTFS et feeds multi-opérateurs.",
            ["gtfs_aggregation", "global_feeds", "api", "open_data"],
            "freemium",
            "mid_market",
            "https://www.transit.land/",
            "alternatives",
            "US",
            notes=BENCH,
        ),
        v(
            "itoworld",
            "ITO World",
            "https://www.itoworld.com/",
            ["transport-mobility-data-fr"],
            "Visualisation et analytics données transport ; open data mobility pour collectivités.",
            ["transport_visualization", "mobility_analytics", "gtfs"],
            "enterprise_quote",
            "mid_market",
            "https://www.itoworld.com/",
            "geo_digest",
            "GB",
            notes=BENCH,
        ),
    ],
    "energy-buildings-fr.json": [
        v(
            "uk-epc-register",
            "UK EPC Register",
            "https://www.gov.uk/find-energy-certificate",
            ["energy-buildings-fr"],
            "Registre certificats performance énergétique UK ; équivalent DPE pour benchmark rénovation.",
            ["epc", "building_energy", "uk", "open_data"],
            "freemium",
            "mid_market",
            "https://www.gov.uk/find-energy-certificate",
            "official_site",
            "GB",
            notes="Benchmark réglementaire bâtiments — équivalent DPE FR.",
        ),
        v(
            "building-performance-database",
            "Building Performance Database (US DOE)",
            "https://bpd.lbl.gov/",
            ["energy-buildings-fr"],
            "Base données performance bâtiments US ; analytics conso et benchmarking énergétique.",
            ["building_performance", "energy_benchmarking", "open_data", "us"],
            "freemium",
            "mid_market",
            "https://bpd.lbl.gov/",
            "official_site",
            "US",
            notes=BENCH,
        ),
        v(
            "dena-gebaeudedaten",
            "dena — Gebäudedaten (DE)",
            "https://www.dena.de/",
            ["energy-buildings-fr"],
            "Données et outils efficacité énergétique bâtiments Allemagne ; référence EU hors FR.",
            ["building_energy", "germany", "renovation", "policy"],
            "freemium",
            "mid_market",
            "https://www.dena.de/",
            "geo_digest",
            "DE",
            fr="unknown",
            regions=["DE", "EU"],
            notes=BENCH,
        ),
        v(
            "gridx-energy",
            "gridX",
            "https://www.gridx.ai/",
            ["energy-buildings-fr"],
            "Gestion énergie bâtiments et réseaux ; optimisation conso et intégration ENR (Allemagne).",
            ["energy_management", "buildings", "grid_integration", "optimization"],
            "enterprise_quote",
            "mid_market",
            "https://www.gridx.ai/",
            "crunchbase",
            "DE",
            fr="partial",
            regions=["DE", "EU"],
            notes=BENCH,
        ),
    ],
    "environmental-data-fr.json": [
        v(
            "uk-environment-agency",
            "UK Environment Agency — Open Data",
            "https://environment.data.gov.uk/",
            ["environmental-data-fr"],
            "Portail données environnement UK ; eau, inondations, qualité air et risques.",
            ["flood_risk", "water_quality", "air", "open_data"],
            "freemium",
            "mid_market",
            "https://environment.data.gov.uk/",
            "official_site",
            "GB",
            notes=BENCH,
        ),
        v(
            "eea-europe",
            "European Environment Agency",
            "https://www.eea.europa.eu/",
            ["environmental-data-fr"],
            "Données environnementales EU ; air, eau, climat et indicateurs territoriaux européens.",
            ["eu_environment", "air_quality", "climate", "open_data"],
            "freemium",
            "mid_market",
            "https://www.eea.europa.eu/",
            "official_site",
            "EU",
            fr="partial",
            regions=["EU"],
            notes="Référence EU — comparable Géorisques/Atmo FR.",
        ),
        v(
            "copernicus-land",
            "Copernicus Land Monitoring",
            "https://land.copernicus.eu/",
            ["environmental-data-fr"],
            "Service observation Terre EU ; usage sol, urbanisation, forêts et risques environnementaux.",
            ["earth_observation", "land_use", "eu", "satellite"],
            "freemium",
            "mid_market",
            "https://land.copernicus.eu/",
            "official_site",
            "EU",
            fr="partial",
            regions=["EU"],
            notes=BENCH,
        ),
        v(
            "us-epa-envirofacts",
            "US EPA Envirofacts",
            "https://www.epa.gov/enviro",
            ["environmental-data-fr"],
            "Base intégrée données environnement US ; facilities, toxiques, eau et air.",
            ["environmental_data", "facilities", "toxics", "us"],
            "freemium",
            "mid_market",
            "https://www.epa.gov/enviro",
            "official_site",
            "US",
            notes=BENCH,
        ),
    ],
    "electoral-data-fr.json": [
        v(
            "uk-electoral-commission",
            "UK Electoral Commission — Open Data",
            "https://www.electoralcommission.org.uk/",
            ["electoral-data-fr"],
            "Données électorales UK ; financement campagnes, résultats et registre électoral.",
            ["election_results", "campaign_finance", "uk", "open_data"],
            "freemium",
            "mid_market",
            "https://www.electoralcommission.org.uk/",
            "official_site",
            "GB",
            notes=BENCH,
        ),
        v(
            "mit-election-lab",
            "MIT Election Data and Science Lab",
            "https://electionlab.mit.edu/",
            ["electoral-data-fr"],
            "Recherche et datasets électoraux US ; méthodes et données comparables pour analytics territoriaux.",
            ["election_data", "research", "datasets", "methodology"],
            "freemium",
            "mid_market",
            "https://electionlab.mit.edu/",
            "official_site",
            "US",
            notes=BENCH,
        ),
        v(
            "elections-europe",
            "European Parliament — Elections data",
            "https://results.elections.europa.eu/",
            ["electoral-data-fr"],
            "Résultats élections européennes ; données agrégées par pays et circonscription.",
            ["eu_elections", "results", "territorial", "open_data"],
            "freemium",
            "mid_market",
            "https://results.elections.europa.eu/",
            "official_site",
            "EU",
            fr="partial",
            regions=["EU"],
            notes=BENCH,
        ),
        v(
            "ballotpedia-data",
            "Ballotpedia",
            "https://ballotpedia.org/",
            ["electoral-data-fr"],
            "Encyclopédie électorale US ; données candidats, scrutins et analyses territoriales.",
            ["election_encyclopedia", "candidates", "ballot_measures", "us"],
            "freemium",
            "mid_market",
            "https://ballotpedia.org/",
            "alternatives",
            "US",
            notes=BENCH,
        ),
    ],
    "public-health-territory-fr.json": [
        v(
            "nhs-digital-open-data",
            "NHS Digital — Open Data",
            "https://digital.nhs.uk/data-and-information",
            ["public-health-territory-fr"],
            "Données santé publique UK ; offre de soins, prescriptions et indicateurs territoriaux.",
            ["health_open_data", "nhs", "territorial", "uk"],
            "freemium",
            "mid_market",
            "https://digital.nhs.uk/data-and-information",
            "official_site",
            "GB",
            notes=BENCH,
        ),
        v(
            "cdc-places",
            "CDC PLACES",
            "https://www.cdc.gov/places",
            ["public-health-territory-fr"],
            "Statistiques santé territoriales US ; prévalence maladies et déterminants par zone.",
            ["territorial_health", "prevalence", "us", "open_data"],
            "freemium",
            "mid_market",
            "https://www.cdc.gov/places",
            "official_site",
            "US",
            notes=BENCH,
        ),
        v(
            "who-health-observatory",
            "WHO Global Health Observatory",
            "https://www.who.int/data/gho",
            ["public-health-territory-fr"],
            "Indicateurs santé mondiaux ; comparaisons territoriales et données pays.",
            ["global_health", "indicators", "country_data", "open_data"],
            "freemium",
            "mid_market",
            "https://www.who.int/data/gho",
            "official_site",
            "CH",
            fr="unknown",
            regions=["global"],
            notes=BENCH,
        ),
        v(
            "healthdata-gov",
            "HealthData.gov (US)",
            "https://healthdata.gov/",
            ["public-health-territory-fr"],
            "Portail open data santé US ; jeux fédéraux et territoriaux pour analytics population.",
            ["health_open_data", "us", "federal", "api"],
            "freemium",
            "mid_market",
            "https://healthdata.gov/",
            "official_site",
            "US",
            notes=BENCH,
        ),
    ],
    "open-data-governance-fr.json": [
        v(
            "socrata-tyler",
            "Socrata (Tyler Technologies)",
            "https://tylertech.com/solutions/socrata",
            ["open-data-governance-fr"],
            "Plateforme open data gouvernementale US ; publication, API et gouvernance jeux de données.",
            ["open_data_platform", "api", "government", "catalog"],
            "enterprise_quote",
            "enterprise",
            "https://tylertech.com/solutions/socrata",
            "g2",
            "US",
            notes=BENCH,
        ),
        v(
            "ckan",
            "CKAN",
            "https://ckan.org/",
            ["open-data-governance-fr"],
            "Plateforme open-source catalogage données ; utilisée par data.gov.uk et centaines de portails.",
            ["open_source", "data_catalog", "harvesting", "api"],
            "open_source",
            "mid_market",
            "https://ckan.org/",
            "open_source",
            "GB",
            fr="partial",
            regions=["global"],
            notes=BENCH,
        ),
        v(
            "arcgis-hub",
            "ArcGIS Hub",
            "https://www.esri.com/en-us/arcgis/products/arcgis-hub/overview",
            ["open-data-governance-fr"],
            "Portails open data géographiques ; gouvernance publication et engagement citoyen sur données.",
            ["open_data_hub", "gis", "community_engagement", "catalog"],
            "enterprise_quote",
            "enterprise",
            "https://www.esri.com/en-us/arcgis/products/arcgis-hub/overview",
            "analyst_report",
            "US",
            fr="partial",
            notes=BENCH,
        ),
        v(
            "data-gov-us",
            "Data.gov (US)",
            "https://data.gov/",
            ["open-data-governance-fr"],
            "Portail open data fédéral US ; métadonnées, fédération et standards comparable data.gouv.fr.",
            ["national_portal", "metadata", "federation", "us"],
            "freemium",
            "mid_market",
            "https://data.gov/",
            "official_site",
            "US",
            notes="Benchmark portail national — comparable Etalab/data.gouv.fr.",
        ),
    ],
}

COVERAGE_TEMPLATE = {
    "geo_digest": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 2, "pass": PASS_ID},
    "official_site": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
    "g2": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    "crunchbase": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    "alternatives": {"consulted_at": TODAY, "candidates_found": 5, "new_added": 1, "pass": PASS_ID},
    "open_source": {"consulted_at": TODAY, "candidates_found": 4, "new_added": 1, "pass": PASS_ID},
}

FRANCE_SEGMENTS = list(ADDITIONS.keys())


def merge() -> None:
    all_ids: set[str] = set()
    for path in VENDORS_DIR.glob("*.json"):
        for vendor in json.loads(path.read_text(encoding="utf-8")).get("vendors", []):
            all_ids.add(vendor["id"])

    total_added = 0
    for fname, new_vendors in ADDITIONS.items():
        path = VENDORS_DIR / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        count = 0
        for vendor in new_vendors:
            if vendor["id"] in all_ids:
                print(f"skip duplicate: {vendor['id']}")
                continue
            data["vendors"].append(vendor)
            all_ids.add(vendor["id"])
            count += 1
            total_added += 1
        data["updated_at"] = TODAY
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"updated {fname}: +{count} vendors")

    matrix = json.loads(COVERAGE.read_text(encoding="utf-8"))
    for fname in FRANCE_SEGMENTS:
        seg_id = Path(fname).stem
        entry = matrix["segments"][seg_id]
        for src, upd in COVERAGE_TEMPLATE.items():
            if entry["sources"].get(src) is None:
                entry["sources"][src] = dict(upd)
        entry["last_pass"] = PASS_ID
        seg_data = json.loads((VENDORS_DIR / fname).read_text(encoding="utf-8"))
        entry["vendor_count_after_pass"] = len(seg_data["vendors"])
    matrix["updated_at"] = TODAY
    COVERAGE.write_text(json.dumps(matrix, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"done: +{total_added} international equivalents, coverage updated for 10 segments")


if __name__ == "__main__":
    merge()
