#!/usr/bin/env python3
"""Vague 5l — sécurité, KYC/AML et infra IA (RecordAI KYC lite, L1→L2)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
COVERAGE = ROOT / "catalogue-saas" / "coverage-matrix.json"
TODAY = "2026-06-23"
PASS_ID = "2026-06-v5l-security-kyc-infra"


def v(
    id_: str,
    name: str,
    url: str,
    segments: list[str],
    desc: str,
    caps: list[str],
    pricing: str,
    market: str,
    source: str,
    src_type: str,
    hq: str = "US",
    fr: str = "partial",
    regions: list[str] | None = None,
    geo: str = "global",
    notes: str | None = None,
) -> dict:
    d = {
        "id": id_,
        "name": name,
        "url": url,
        "segments": segments,
        "description": desc,
        "capabilities": caps,
        "pricing_model": pricing,
        "target_market": market,
        "geography": geo,
        "hq_country": hq,
        "france_market": fr,
        "operating_regions": regions or ["US", "EU"],
        "discovery_source": src_type,
        "discovery_pass": PASS_ID,
        "source_url": source,
        "source_consulted_at": TODAY,
        "verification_status": "partial",
    }
    if notes:
        d["notes"] = notes
    return d


ADDITIONS: dict[str, list[dict]] = {
    "kyc-aml.json": [
        v(
            "ubble",
            "Ubble",
            "https://ubble.ai/",
            ["kyc-aml"],
            "Vérification identité vidéo certifiée ANSSI ; KYC lite pour fintech et onboarding digital FR.",
            ["video_identification", "anssi_certified", "kyc_lite", "liveness"],
            "per_usage",
            "mid_market",
            "https://ubble.ai/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
            notes="Concurrent cité idée 0029 RecordAI KYC lite.",
        ),
        v(
            "veriff",
            "Veriff",
            "https://www.veriff.com/",
            ["kyc-aml"],
            "Identity verification AI ; documents, biométrie, liveness et fraud prevention onboarding.",
            ["document_verification", "biometric", "liveness", "fraud_prevention"],
            "per_usage",
            "mid_market",
            "https://www.veriff.com/",
            "g2",
            hq="EE",
            fr="partial",
            geo="global",
            regions=["EE", "EU", "US"],
        ),
        v(
            "idnow",
            "IDnow",
            "https://www.idnow.io/",
            ["kyc-aml"],
            "KYC/KYB européen ; vidéo-identification, eIDAS et conformité AML secteurs régulés.",
            ["video_identification", "eidas", "kyb", "aml"],
            "enterprise_quote",
            "enterprise",
            "https://www.idnow.io/",
            "g2",
            hq="DE",
            fr="partial",
            geo="europe",
            regions=["DE", "EU", "FR"],
        ),
        v(
            "persona",
            "Persona",
            "https://withpersona.com/",
            ["kyc-aml"],
            "Plateforme identity orchestration ; workflows KYC configurables, screening et case management.",
            ["identity_orchestration", "kyc_workflows", "screening", "case_management"],
            "hybrid",
            "mid_market",
            "https://withpersona.com/",
            "g2",
        ),
        v(
            "trulioo",
            "Trulioo",
            "https://www.trulioo.com/",
            ["kyc-aml"],
            "Global identity verification ; couverture 195 pays, KYB et watchlist screening.",
            ["global_kyc", "kyb", "watchlist", "document_verification"],
            "enterprise_quote",
            "enterprise",
            "https://www.trulioo.com/",
            "g2",
            hq="CA",
            fr="partial",
            regions=["CA", "US", "EU"],
        ),
        v(
            "alloy",
            "Alloy",
            "https://www.alloy.com/",
            ["kyc-aml", "regtech"],
            "Identity decisioning fintech ; orchestration KYC/KYB, fraud et compliance onboarding.",
            ["identity_decisioning", "kyc_kyb", "fraud", "workflow"],
            "enterprise_quote",
            "enterprise",
            "https://www.alloy.com/",
            "crunchbase",
        ),
        v(
            "dotfile",
            "Dotfile",
            "https://www.dotfile.com/",
            ["kyc-aml"],
            "KYB/KYC no-code FR ; collecte dossiers, vérifications tierces et portail conformité PME.",
            ["kyb", "kyc", "no_code", "compliance_portal"],
            "hybrid",
            "smb",
            "https://www.dotfile.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "salv",
            "Salv",
            "https://salv.com/",
            ["kyc-aml", "regtech"],
            "AML screening et monitoring transactionnel ; sanctions, PEP et alertes temps réel.",
            ["aml_screening", "transaction_monitoring", "sanctions", "pep"],
            "enterprise_quote",
            "mid_market",
            "https://salv.com/",
            "g2",
            hq="EE",
            fr="partial",
            geo="europe",
            regions=["EE", "EU", "FR"],
        ),
    ],
    "cybersecurity-platforms.json": [
        v(
            "elastic-security",
            "Elastic Security",
            "https://www.elastic.co/security",
            ["cybersecurity-platforms"],
            "SIEM/XDR open ; détection menaces, EDR, SOAR et threat hunting sur stack Elastic.",
            ["siem", "xdr", "edr", "threat_hunting"],
            "hybrid",
            "enterprise",
            "https://www.elastic.co/security",
            "g2",
            hq="US",
            fr="partial",
        ),
        v(
            "arctic-wolf",
            "Arctic Wolf",
            "https://arcticwolf.com/",
            ["cybersecurity-platforms"],
            "MDR/SOC-as-a-service ; monitoring 24/7, détection et réponse incidents managée.",
            ["mdr", "soc_as_service", "incident_response", "managed_detection"],
            "enterprise_quote",
            "mid_market",
            "https://arcticwolf.com/",
            "g2",
        ),
        v(
            "harfanglab",
            "HarfangLab",
            "https://harfanglab.io/",
            ["cybersecurity-platforms"],
            "EDR/XDR souverain FR ; détection comportementale, threat hunting et réponse endpoint.",
            ["edr", "xdr", "threat_hunting", "sovereign"],
            "enterprise_quote",
            "enterprise",
            "https://harfanglab.io/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "sekoia",
            "Sekoia.io",
            "https://www.sekoia.io/",
            ["cybersecurity-platforms"],
            "XDR/SOC platform FR ; CTI intégrée, playbooks SOAR et détection multi-sources.",
            ["xdr", "soc", "cti", "soar"],
            "enterprise_quote",
            "enterprise",
            "https://www.sekoia.io/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "ibm-qradar",
            "IBM QRadar",
            "https://www.ibm.com/qradar",
            ["cybersecurity-platforms"],
            "SIEM enterprise ; corrélation logs, UEBA, SOAR et threat intelligence intégrée.",
            ["siem", "ueba", "soar", "threat_intel"],
            "enterprise_quote",
            "enterprise",
            "https://www.ibm.com/qradar",
            "analyst_report",
        ),
        v(
            "trend-micro-vision-one",
            "Trend Micro Vision One",
            "https://www.trendmicro.com/en_us/business/products/detection-response/vision-one.html",
            ["cybersecurity-platforms"],
            "Plateforme XDR unifiée ; EDR, email security, cloud et attack surface management.",
            ["xdr", "edr", "attack_surface", "soar"],
            "enterprise_quote",
            "enterprise",
            "https://www.trendmicro.com/",
            "g2",
            hq="JP",
            fr="partial",
            regions=["JP", "US", "EU"],
        ),
    ],
    "identity-access-management.json": [
        v(
            "auth0",
            "Auth0 (Okta)",
            "https://auth0.com/",
            ["identity-access-management"],
            "Customer Identity & Access ; SSO, MFA, social login et extensibility développeur.",
            ["ciam", "sso", "mfa", "social_login"],
            "hybrid",
            "mid_market",
            "https://auth0.com/",
            "g2",
        ),
        v(
            "keycloak",
            "Keycloak",
            "https://www.keycloak.org/",
            ["identity-access-management"],
            "IAM open-source ; SSO, fédération, RBAC et self-hosted pour souveraineté identité.",
            ["sso", "federation", "rbac", "self_hosted"],
            "open_source",
            "mid_market",
            "https://www.keycloak.org/",
            "open_source",
            hq="unknown",
            fr="partial",
        ),
        v(
            "wallix",
            "Wallix",
            "https://www.wallix.com/",
            ["identity-access-management"],
            "PAM et bastion FR ; accès privilégiés, session recording et conformité NIS2/ANSSI.",
            ["pam", "bastion", "session_recording", "privileged_access"],
            "enterprise_quote",
            "enterprise",
            "https://www.wallix.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "cyberark",
            "CyberArk",
            "https://www.cyberark.com/",
            ["identity-access-management"],
            "PAM leader ; vault secrets, accès privilégiés et identity security poste-MFA.",
            ["pam", "secrets_vault", "privileged_access", "identity_security"],
            "enterprise_quote",
            "enterprise",
            "https://www.cyberark.com/",
            "g2",
        ),
        v(
            "ping-identity",
            "Ping Identity",
            "https://www.pingidentity.com/",
            ["identity-access-management"],
            "IAM enterprise ; fédération, SSO, CIAM et orchestration identités hybrides.",
            ["federation", "sso", "ciam", "orchestration"],
            "enterprise_quote",
            "enterprise",
            "https://www.pingidentity.com/",
            "g2",
        ),
        v(
            "forgerock",
            "ForgeRock (Ping)",
            "https://www.pingidentity.com/en/platform.html",
            ["identity-access-management"],
            "Identity platform ; CIAM, IAM workforce et consent management pour secteurs régulés.",
            ["ciam", "workforce_iam", "consent", "orchestration"],
            "enterprise_quote",
            "enterprise",
            "https://www.pingidentity.com/",
            "analyst_report",
        ),
    ],
    "cloud-security-cspm.json": [
        v(
            "datadog-cspm",
            "Datadog Cloud Security",
            "https://www.datadoghq.com/product/cloud-security/",
            ["cloud-security-cspm"],
            "CSPM/CWPP Datadog ; posture multi-cloud, détection menaces runtime et compliance.",
            ["cspm", "cwpp", "runtime_detection", "compliance"],
            "hybrid",
            "enterprise",
            "https://www.datadoghq.com/product/cloud-security/",
            "g2",
        ),
        v(
            "sysdig",
            "Sysdig Secure",
            "https://sysdig.com/",
            ["cloud-security-cspm"],
            "CNAPP conteneurs/K8s ; CSPM, runtime protection, Falco et supply chain security.",
            ["cnapp", "cspm", "kubernetes", "falco"],
            "enterprise_quote",
            "enterprise",
            "https://sysdig.com/",
            "g2",
        ),
        v(
            "check-point-cloud",
            "Check Point CloudGuard",
            "https://www.checkpoint.com/cloudguard/",
            ["cloud-security-cspm"],
            "Sécurité cloud multi-hyperviseur ; posture, WAF, CNAPP et IaC scanning.",
            ["cspm", "waf", "cnapp", "iac_scanning"],
            "enterprise_quote",
            "enterprise",
            "https://www.checkpoint.com/cloudguard/",
            "g2",
            hq="IL",
            fr="partial",
            regions=["IL", "US", "EU"],
        ),
        v(
            "netskope",
            "Netskope",
            "https://www.netskope.com/",
            ["cloud-security-cspm"],
            "SSE/CASB ; visibilité SaaS, DLP cloud, SWG et posture applications cloud.",
            ["casb", "sse", "dlp", "saas_security"],
            "enterprise_quote",
            "enterprise",
            "https://www.netskope.com/",
            "analyst_report",
        ),
        v(
            "bridgecrew",
            "Bridgecrew (Prisma Cloud)",
            "https://www.paloaltonetworks.com/prisma/cloud/bridgecrew",
            ["cloud-security-cspm"],
            "IaC security et shift-left ; scan Terraform/CloudFormation, policies-as-code et remédiation.",
            ["iac_security", "shift_left", "policy_as_code", "terraform"],
            "hybrid",
            "mid_market",
            "https://www.paloaltonetworks.com/prisma/cloud/bridgecrew",
            "official_site",
        ),
        v(
            "panoptica",
            "Panoptica (Cisco)",
            "https://panoptica.app/",
            ["cloud-security-cspm"],
            "CNAPP cloud-native ; cartographie attack path, vulnérabilités API et posture K8s.",
            ["cnapp", "attack_path", "api_security", "kubernetes"],
            "enterprise_quote",
            "mid_market",
            "https://panoptica.app/",
            "crunchbase",
        ),
    ],
    "email-security.json": [
        v(
            "vade",
            "Vade (Hornetsecurity)",
            "https://www.vadesecure.com/",
            ["email-security"],
            "Filtrage email IA FR ; anti-phishing, spear phishing et protection Microsoft 365/Google.",
            ["email_filtering", "anti_phishing", "ai_detection", "m365"],
            "hybrid",
            "mid_market",
            "https://www.vadesecure.com/",
            "geo_digest",
            hq="FR",
            fr="strong",
            geo="france",
        ),
        v(
            "tessian",
            "Tessian",
            "https://www.tessian.com/",
            ["email-security"],
            "Email security comportementale ; BEC, data loss prevention et coaching utilisateurs.",
            ["bec_protection", "dlp", "behavioral_ai", "user_coaching"],
            "enterprise_quote",
            "enterprise",
            "https://www.tessian.com/",
            "g2",
            hq="GB",
            fr="partial",
            regions=["GB", "EU", "US"],
        ),
        v(
            "ironscales",
            "IRONSCALES",
            "https://ironscales.com/",
            ["email-security"],
            "Email security crowdsourced ; phishing, BEC et remédiation automatisée boîtes utilisateurs.",
            ["phishing", "bec", "crowdsourced_intel", "remediation"],
            "hybrid",
            "mid_market",
            "https://ironscales.com/",
            "g2",
            hq="IL",
            fr="partial",
            regions=["IL", "US", "EU"],
        ),
        v(
            "cofense",
            "Cofense",
            "https://cofense.com/",
            ["email-security"],
            "Phishing defense ; simulation, reporting utilisateurs et triage analyste threats email.",
            ["phishing_simulation", "user_reporting", "triage", "awareness"],
            "enterprise_quote",
            "enterprise",
            "https://cofense.com/",
            "g2",
        ),
        v(
            "area1-security",
            "Area 1 Security (Cloudflare)",
            "https://www.cloudflare.com/zero-trust/products/email-security/",
            ["email-security"],
            "Email security preemptive ; détection phishing zero-day et intégration Cloudflare Zero Trust.",
            ["preemptive_phishing", "zero_day", "zero_trust", "bec"],
            "hybrid",
            "enterprise",
            "https://www.cloudflare.com/zero-trust/products/email-security/",
            "official_site",
        ),
        v(
            "cloudflare-email-security",
            "Cloudflare Email Security",
            "https://www.cloudflare.com/email-security/",
            ["email-security"],
            "Protection email cloud ; anti-phishing, impersonation et isolation navigateur liens.",
            ["anti_phishing", "impersonation", "link_isolation", "cloud_native"],
            "hybrid",
            "mid_market",
            "https://www.cloudflare.com/email-security/",
            "official_site",
        ),
    ],
    "vulnerability-management.json": [
        v(
            "greenbone",
            "Greenbone (OpenVAS)",
            "https://www.greenbone.net/",
            ["vulnerability-management"],
            "Scan vulnérabilités open-source ; OpenVAS, GVM et gestion compliance réseau/infra.",
            ["vulnerability_scanning", "openvas", "compliance", "network_scan"],
            "hybrid",
            "mid_market",
            "https://www.greenbone.net/",
            "open_source",
            hq="DE",
            fr="partial",
            geo="europe",
            regions=["DE", "EU", "FR"],
        ),
        v(
            "intruder",
            "Intruder",
            "https://www.intruder.io/",
            ["vulnerability-management"],
            "Attack surface management ; scan continu externe, prioritisation CVE et reporting.",
            ["asm", "external_scanning", "cve_prioritization", "continuous_monitoring"],
            "hybrid",
            "mid_market",
            "https://www.intruder.io/",
            "g2",
            hq="GB",
            fr="partial",
            regions=["GB", "EU", "US"],
        ),
        v(
            "runzero",
            "runZero",
            "https://www.runzero.com/",
            ["vulnerability-management"],
            "Asset discovery et exposure ; cartographie réseau, fingerprinting et vuln scan intégré.",
            ["asset_discovery", "network_mapping", "exposure", "fingerprinting"],
            "hybrid",
            "mid_market",
            "https://www.runzero.com/",
            "g2",
        ),
        v(
            "hadrian",
            "Hadrian",
            "https://hadrian.io/",
            ["vulnerability-management"],
            "Offensive security automatisée ; ASM externe, pentest continu et priorisation risques.",
            ["offensive_security", "asm", "continuous_pentest", "risk_prioritization"],
            "enterprise_quote",
            "mid_market",
            "https://hadrian.io/",
            "crunchbase",
            hq="NL",
            fr="partial",
            geo="europe",
            regions=["NL", "EU", "US"],
        ),
        v(
            "securityscorecard",
            "SecurityScorecard",
            "https://securityscorecard.com/",
            ["vulnerability-management"],
            "Security ratings et TPRM ; scoring externe, monitoring tiers et remediation guidance.",
            ["security_ratings", "tprm", "third_party_risk", "continuous_monitoring"],
            "enterprise_quote",
            "enterprise",
            "https://securityscorecard.com/",
            "analyst_report",
        ),
        v(
            "cyber-resilience",
            "CyberResilience (Rubrik)",
            "https://www.rubrik.com/",
            ["vulnerability-management"],
            "Cyber resilience et recovery ; backup immuable, threat detection et posture recovery.",
            ["cyber_resilience", "immutable_backup", "recovery", "threat_detection"],
            "enterprise_quote",
            "enterprise",
            "https://www.rubrik.com/",
            "analyst_report",
        ),
    ],
    "llm-api-providers.json": [
        v(
            "aleph-alpha",
            "Aleph Alpha",
            "https://aleph-alpha.com/",
            ["llm-api-providers"],
            "LLM européen souverain ; modèles Luminous, API enterprise et déploiement on-prem EU.",
            ["european_llm", "luminous", "sovereign_deployment", "api"],
            "per_usage",
            "enterprise",
            "https://aleph-alpha.com/",
            "geo_digest",
            hq="DE",
            fr="partial",
            geo="europe",
            regions=["DE", "EU", "FR"],
        ),
        v(
            "ai21-labs",
            "AI21 Labs",
            "https://www.ai21.com/",
            ["llm-api-providers"],
            "Jurassic models API ; génération, summarization et RAG toolkit enterprise.",
            ["jurassic_models", "generation", "summarization", "rag"],
            "per_usage",
            "mid_market",
            "https://www.ai21.com/",
            "g2",
            hq="IL",
            fr="partial",
            regions=["IL", "US", "EU"],
        ),
        v(
            "meta-llama-api",
            "Meta Llama API",
            "https://llama.meta.com/",
            ["llm-api-providers"],
            "Modèles Llama open via API ; inference managée Meta et partenaires cloud.",
            ["llama_models", "open_weights", "managed_inference", "fine_tuning"],
            "per_usage",
            "mid_market",
            "https://llama.meta.com/",
            "official_site",
        ),
        v(
            "deepseek-api",
            "DeepSeek API",
            "https://platform.deepseek.com/",
            ["llm-api-providers"],
            "API modèles DeepSeek ; reasoning, code et pricing compétitif pour workloads batch.",
            ["reasoning_models", "code_generation", "batch_inference", "api"],
            "per_usage",
            "mid_market",
            "https://platform.deepseek.com/",
            "crunchbase",
            hq="CN",
            fr="partial",
            geo="global",
            regions=["CN", "US", "EU"],
        ),
        v(
            "fireworks-ai",
            "Fireworks AI",
            "https://fireworks.ai/",
            ["llm-api-providers", "model-inference-hosting"],
            "Inference API modèles open ; latence optimisée, fine-tuning et function calling.",
            ["fast_inference", "open_models", "fine_tuning", "function_calling"],
            "per_usage",
            "mid_market",
            "https://fireworks.ai/",
            "crunchbase",
        ),
        v(
            "groq",
            "Groq",
            "https://groq.com/",
            ["llm-api-providers", "model-inference-hosting"],
            "Inference ultra-rapide LPU ; API Llama/Mixtral et latence prévisible production.",
            ["lpu_inference", "low_latency", "llama_api", "production"],
            "per_usage",
            "mid_market",
            "https://groq.com/",
            "crunchbase",
        ),
    ],
    "model-inference-hosting.json": [
        v(
            "baseten",
            "Baseten",
            "https://www.baseten.co/",
            ["model-inference-hosting"],
            "ML inference platform ; déploiement modèles custom, autoscaling GPU et observabilité.",
            ["model_deployment", "gpu_autoscaling", "custom_models", "observability"],
            "per_usage",
            "mid_market",
            "https://www.baseten.co/",
            "crunchbase",
        ),
        v(
            "anyscale",
            "Anyscale (Ray)",
            "https://www.anyscale.com/",
            ["model-inference-hosting"],
            "Ray platform managée ; training, inference distribuée et serving LLM à l'échelle.",
            ["ray", "distributed_inference", "llm_serving", "training"],
            "hybrid",
            "enterprise",
            "https://www.anyscale.com/",
            "crunchbase",
        ),
        v(
            "runpod",
            "RunPod",
            "https://www.runpod.io/",
            ["model-inference-hosting"],
            "GPU cloud serverless ; pods, serverless endpoints et fine-tuning modèles open.",
            ["gpu_cloud", "serverless", "fine_tuning", "endpoints"],
            "per_usage",
            "self_serve",
            "https://www.runpod.io/",
            "open_source",
        ),
        v(
            "fal-ai",
            "fal.ai",
            "https://fal.ai/",
            ["model-inference-hosting"],
            "Inference serverless GenAI ; modèles image/vidéo/LLM via API et workflows GPU.",
            ["serverless_inference", "genai", "media_models", "api"],
            "per_usage",
            "self_serve",
            "https://fal.ai/",
            "crunchbase",
        ),
        v(
            "lepton-ai",
            "Lepton AI",
            "https://www.lepton.ai/",
            ["model-inference-hosting"],
            "Cloud inference simplifié ; déploiement one-click modèles Hugging Face et scaling auto.",
            ["one_click_deploy", "huggingface", "autoscaling", "inference"],
            "per_usage",
            "mid_market",
            "https://www.lepton.ai/",
            "crunchbase",
        ),
        v(
            "scaleway-generative-api",
            "Scaleway Generative APIs",
            "https://www.scaleway.com/en/generative-apis/",
            ["model-inference-hosting", "llm-api-providers"],
            "API LLM souveraine FR ; Mistral, Llama et embeddings hébergés datacenters européens.",
            ["sovereign_hosting", "mistral", "llama", "european_dc"],
            "per_usage",
            "mid_market",
            "https://www.scaleway.com/en/generative-apis/",
            "official_site",
            hq="FR",
            fr="strong",
            geo="france",
        ),
    ],
    "vector-databases.json": [
        v(
            "pgvector",
            "pgvector",
            "https://github.com/pgvector/pgvector",
            ["vector-databases"],
            "Extension PostgreSQL vectors ; recherche similarité, HNSW/IVFFlat et stack SQL familière.",
            ["postgres_extension", "similarity_search", "hnsw", "sql"],
            "open_source",
            "self_serve",
            "https://github.com/pgvector/pgvector",
            "open_source",
        ),
        v(
            "redis-vector-search",
            "Redis Vector Search",
            "https://redis.io/docs/latest/develop/interact/search-and-query/vectors/",
            ["vector-databases"],
            "Recherche vectorielle Redis ; indexing HNSW, hybrid search et cache embeddings temps réel.",
            ["vector_index", "hybrid_search", "hnsw", "real_time"],
            "hybrid",
            "mid_market",
            "https://redis.io/",
            "official_site",
        ),
        v(
            "mongodb-atlas-vector",
            "MongoDB Atlas Vector Search",
            "https://www.mongodb.com/products/platform/atlas-vector-search",
            ["vector-databases"],
            "Vector search natif Atlas ; filtres metadata, RAG et intégration documents JSON.",
            ["vector_search", "metadata_filter", "rag", "document_store"],
            "hybrid",
            "mid_market",
            "https://www.mongodb.com/products/platform/atlas-vector-search",
            "official_site",
        ),
        v(
            "turbopuffer",
            "Turbopuffer",
            "https://turbopuffer.com/",
            ["vector-databases"],
            "Vector DB serverless ; stockage objet + ANN, latence faible et pricing usage-based.",
            ["serverless", "ann", "object_storage", "low_latency"],
            "per_usage",
            "mid_market",
            "https://turbopuffer.com/",
            "crunchbase",
        ),
        v(
            "marqo",
            "Marqo",
            "https://www.marqo.ai/",
            ["vector-databases"],
            "Vector search end-to-end ; embeddings intégrés, multimodal et API RAG simplifiée.",
            ["embedded_models", "multimodal", "rag_api", "hybrid_search"],
            "hybrid",
            "mid_market",
            "https://www.marqo.ai/",
            "crunchbase",
            hq="AU",
            fr="partial",
            regions=["AU", "US", "EU"],
        ),
    ],
    "ai-evals-testing.json": [
        v(
            "arize-phoenix",
            "Arize Phoenix",
            "https://phoenix.arize.com/",
            ["ai-evals-testing"],
            "Observabilité LLM open-source ; tracing, evals, drift detection et datasets.",
            ["llm_tracing", "evals", "drift_detection", "datasets"],
            "open_source",
            "mid_market",
            "https://phoenix.arize.com/",
            "open_source",
        ),
        v(
            "helicone",
            "Helicone",
            "https://www.helicone.ai/",
            ["ai-evals-testing"],
            "LLM observability ; logging proxy, coûts, latence et evals intégrées production.",
            ["llm_logging", "cost_tracking", "latency", "evals"],
            "hybrid",
            "mid_market",
            "https://www.helicone.ai/",
            "open_source",
        ),
        v(
            "confident-ai",
            "Confident AI (DeepEval)",
            "https://www.confident-ai.com/",
            ["ai-evals-testing"],
            "Evals LLM unitaires ; métriques RAG, hallucination, CI/CD et regression testing.",
            ["unit_evals", "rag_metrics", "hallucination", "ci_cd"],
            "hybrid",
            "mid_market",
            "https://www.confident-ai.com/",
            "open_source",
        ),
        v(
            "deepeval",
            "DeepEval",
            "https://github.com/confident-ai/deepeval",
            ["ai-evals-testing"],
            "Framework evals Python open-source ; métriques G-Eval, RAG et red teaming.",
            ["python_evals", "g_eval", "rag_metrics", "red_teaming"],
            "open_source",
            "self_serve",
            "https://github.com/confident-ai/deepeval",
            "open_source",
        ),
        v(
            "ragas",
            "Ragas",
            "https://docs.ragas.io/",
            ["ai-evals-testing"],
            "Framework evals RAG ; faithfulness, answer relevance et synthetic test generation.",
            ["rag_evals", "faithfulness", "synthetic_data", "metrics"],
            "open_source",
            "self_serve",
            "https://docs.ragas.io/",
            "open_source",
        ),
        v(
            "wandb-weave",
            "Weights & Biases Weave",
            "https://wandb.ai/site/weave",
            ["ai-evals-testing"],
            "Tracing et evals GenAI ; expériences LLM, datasets et comparaison modèles.",
            ["genai_tracing", "experiments", "model_comparison", "datasets"],
            "hybrid",
            "mid_market",
            "https://wandb.ai/site/weave",
            "crunchbase",
        ),
    ],
    "agent-frameworks-platforms.json": [
        v(
            "dify",
            "Dify",
            "https://dify.ai/",
            ["agent-frameworks-platforms"],
            "Plateforme LLM ops open-source ; agents, workflows visuels, RAG et API production.",
            ["agent_workflows", "visual_builder", "rag", "api_deploy"],
            "hybrid",
            "mid_market",
            "https://dify.ai/",
            "open_source",
        ),
        v(
            "flowise",
            "Flowise",
            "https://flowiseai.com/",
            ["agent-frameworks-platforms"],
            "Builder agents visuel open-source ; LangChain nodes, chatflows et self-hosted.",
            ["visual_builder", "langchain_nodes", "chatflows", "self_hosted"],
            "open_source",
            "self_serve",
            "https://flowiseai.com/",
            "open_source",
        ),
        v(
            "agno",
            "Agno",
            "https://www.agno.com/",
            ["agent-frameworks-platforms"],
            "Framework agents Python ; multi-agent, mémoire, tool use et déploiement production.",
            ["multi_agent", "memory", "tool_use", "production_deploy"],
            "open_source",
            "mid_market",
            "https://www.agno.com/",
            "open_source",
        ),
        v(
            "superagent",
            "Superagent",
            "https://www.superagent.sh/",
            ["agent-frameworks-platforms"],
            "Framework agents TypeScript ; guardrails, tool calling et déploiement serverless.",
            ["typescript_agents", "guardrails", "tool_calling", "serverless"],
            "open_source",
            "self_serve",
            "https://www.superagent.sh/",
            "open_source",
        ),
        v(
            "agentops",
            "AgentOps",
            "https://www.agentops.ai/",
            ["agent-frameworks-platforms", "ai-evals-testing"],
            "Observabilité agents ; session replay, coûts, debugging et evals runtime.",
            ["agent_observability", "session_replay", "cost_tracking", "debugging"],
            "hybrid",
            "mid_market",
            "https://www.agentops.ai/",
            "crunchbase",
        ),
        v(
            "langflow",
            "Langflow",
            "https://www.langflow.org/",
            ["agent-frameworks-platforms"],
            "UI low-code LangChain ; flows agents, composants custom et export Python/API.",
            ["low_code", "langchain", "custom_components", "api_export"],
            "open_source",
            "mid_market",
            "https://www.langflow.org/",
            "open_source",
        ),
    ],
}

SEGMENT_PATCHES: dict[str, list[str]] = {
    "wiz": ["cybersecurity-platforms"],
    "mistral-ai": ["model-inference-hosting"],
    "dust": ["agent-frameworks-platforms"],
    "n8n": ["agent-frameworks-platforms"],
    "snyk": ["cloud-security-cspm", "vulnerability-management"],
}

COVERAGE_UPDATES: dict[str, dict[str, dict]] = {
    "kyc-aml": {
        "g2": {"consulted_at": TODAY, "candidates_found": 18, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 3, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "cybersecurity-platforms": {
        "g2": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 3, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "identity-access-management": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "open_source": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "cloud-security-cspm": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 3, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "email-security": {
        "g2": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 4, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "vulnerability-management": {
        "g2": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 3, "pass": PASS_ID},
        "open_source": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "analyst_report": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 2, "pass": PASS_ID},
    },
    "llm-api-providers": {
        "g2": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 2, "pass": PASS_ID},
        "geo_digest": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 1, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 2, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "model-inference-hosting": {
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 12, "new_added": 4, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
        "open_source": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "vector-databases": {
        "open_source": {"consulted_at": TODAY, "candidates_found": 10, "new_added": 2, "pass": PASS_ID},
        "official_site": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 2, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 6, "new_added": 1, "pass": PASS_ID},
    },
    "ai-evals-testing": {
        "open_source": {"consulted_at": TODAY, "candidates_found": 14, "new_added": 4, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
    "agent-frameworks-platforms": {
        "open_source": {"consulted_at": TODAY, "candidates_found": 16, "new_added": 5, "pass": PASS_ID},
        "crunchbase": {"consulted_at": TODAY, "candidates_found": 8, "new_added": 1, "pass": PASS_ID},
    },
}


def merge() -> None:
    all_ids: set[str] = set()
    for path in VENDORS_DIR.glob("*.json"):
        for vendor in json.loads(path.read_text(encoding="utf-8")).get("vendors", []):
            all_ids.add(vendor["id"])

    total = 0
    per_file: dict[str, int] = {}
    for fname, vendors in ADDITIONS.items():
        path = VENDORS_DIR / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        count = 0
        for vendor in vendors:
            if vendor["id"] in all_ids:
                print(f"skip duplicate: {vendor['id']}")
                continue
            data["vendors"].append(vendor)
            all_ids.add(vendor["id"])
            count += 1
            total += 1
        data["updated_at"] = TODAY
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        per_file[fname] = count
        print(f"updated {fname}: +{count}")

    patched = 0
    for vpath in sorted(VENDORS_DIR.glob("*.json")):
        vdata = json.loads(vpath.read_text(encoding="utf-8"))
        changed = False
        for vendor in vdata.get("vendors", []):
            for seg in SEGMENT_PATCHES.get(vendor["id"], []):
                if seg not in vendor["segments"]:
                    vendor["segments"].append(seg)
                    changed = True
                    patched += 1
        if changed:
            vdata["updated_at"] = TODAY
            vpath.write_text(json.dumps(vdata, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            print(f"patched {vpath.name}")

    matrix = json.loads(COVERAGE.read_text(encoding="utf-8"))
    for seg_id, sources in COVERAGE_UPDATES.items():
        entry = matrix["segments"][seg_id]
        for src, upd in sources.items():
            prev = entry["sources"].get(src) or {}
            entry["sources"][src] = {
                **upd,
                "cumulative_new": prev.get("cumulative_new", prev.get("new_added", 0)) + upd["new_added"],
            }
        entry["last_pass"] = PASS_ID
        entry["vendor_count_after_pass"] = len(
            json.loads((VENDORS_DIR / f"{seg_id}.json").read_text(encoding="utf-8"))["vendors"]
        )
    matrix["updated_at"] = TODAY
    COVERAGE.write_text(json.dumps(matrix, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"done: +{total} vendors, {patched} patches")
    for fname, n in per_file.items():
        print(f"  {fname}: +{n}")


if __name__ == "__main__":
    merge()
