#!/usr/bin/env python3
"""Vague 2 — enrichissement de tous les segments du catalogue SaaS."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
TODAY = "2026-06-22"

# Nouveaux vendeurs par fichier segment (clé = nom de fichier)
ADDITIONS: dict[str, list[dict]] = {
    "compliance-to-spec.json": [
        {
            "id": "compliance-to-architecture",
            "name": "Compliance-to-Architecture (CtA)",
            "url": "https://compliancetoarchitecture.com/",
            "segments": ["compliance-to-spec", "grc-security"],
            "description": "Framework open-source mappant réglementations (EU AI Act, ISO, SOC2…) vers obligations, contrôles, policies et schémas d'evidence machine-readable.",
            "capabilities": ["obligation_graph", "control_library", "evidence_schema", "architecture_patterns"],
            "pricing_model": "open_source",
            "pricing_notes": "Apache-2.0 ; spec + implémentation de référence.",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://compliancetoarchitecture.com/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "aispecify",
            "name": "AiSpecify",
            "url": "https://everest-systems.com/aispecify/",
            "segments": ["compliance-to-spec"],
            "description": "Plateforme spec-driven : exigences et garde-fous réglementaires encodés avant génération de code, avec traçabilité audit.",
            "capabilities": ["requirements_generation", "custom_specs", "governance_gates", "release_traceability"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://everest-systems.com/aispecify/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "open-policy-agent",
            "name": "Open Policy Agent (OPA)",
            "url": "https://www.openpolicyagent.org/",
            "segments": ["compliance-to-spec"],
            "description": "Moteur de policies-as-code (Rego) pour encoder exigences compliance dans CI/CD et infrastructure.",
            "capabilities": ["policy_as_code", "rego", "ci_cd_gates", "kubernetes_admission"],
            "pricing_model": "open_source",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://rutagon.com/insights/compliance-as-code-opa-rego-federal/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "hyperproof",
            "name": "Hyperproof",
            "url": "https://hyperproof.io/",
            "segments": ["compliance-to-spec", "grc-security"],
            "description": "GRC continu : mappe frameworks vers contrôles opérationnels et collecte de preuves pour audits.",
            "capabilities": ["control_operations", "evidence_collection", "framework_mapping", "audit_readiness"],
            "pricing_model": "enterprise_quote",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://riskpublishing.com/best-compliance-management-software-compared/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "onspring",
            "name": "Onspring",
            "url": "https://onspring.com/",
            "segments": ["compliance-to-spec", "grc-security"],
            "description": "GRC no-code configurable ; mapping réglementaire vers workflows et contrôles pour équipes compliance.",
            "capabilities": ["no_code_grc", "policy_workflows", "control_testing"],
            "pricing_model": "enterprise_quote",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://riskpublishing.com/best-compliance-management-software-compared/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "secureframe",
            "name": "Secureframe",
            "url": "https://secureframe.com/",
            "segments": ["compliance-to-spec", "grc-security"],
            "description": "Automatisation SOC2/ISO/HIPAA avec mapping contrôles et collecte preuves intégrée aux outils dev.",
            "capabilities": ["soc2", "iso27001", "automated_evidence", "integrations"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.v-comply.com/blog/top-grc-software/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "snyk",
            "name": "Snyk",
            "url": "https://snyk.io/",
            "segments": ["compliance-to-spec"],
            "description": "Sécurité dev avec policies-as-code dans le pipeline ; encode exigences dans le flux de livraison logicielle.",
            "capabilities": ["iac_policy", "dependency_scan", "ci_cd_integration", "compliance_reporting"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://developertoolkit.ai/en/shared-workflows/deployment-operations/compliance-automation/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "automation-platforms.json": [
        {
            "id": "workato",
            "name": "Workato",
            "url": "https://www.workato.com/",
            "segments": ["automation-platforms"],
            "description": "iPaaS enterprise : recipes, connecteurs 1000+, agent on-prem pour systèmes internes.",
            "capabilities": ["enterprise_ipaas", "recipes", "on_prem_agent", "ai_workflows"],
            "pricing_model": "enterprise_quote",
            "pricing_notes": "Usage-based ; entrée souvent ~$10K/an (sources marché 2026).",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://docs.workato.com/en/pricing",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "tray-io",
            "name": "Tray.io",
            "url": "https://tray.io/",
            "segments": ["automation-platforms"],
            "description": "iPaaS enterprise JS-first avec Merlin AI pour génération de workflows.",
            "capabilities": ["javascript_mapping", "merlin_ai", "enterprise_connectors"],
            "pricing_model": "enterprise_quote",
            "pricing_notes": "Sur devis ; Pro cité ~$595/mo dans comparatifs.",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://plugjunction.com/compare/tray.io-vs-pipedream/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "pipedream",
            "name": "Pipedream",
            "url": "https://pipedream.com/",
            "segments": ["automation-platforms"],
            "description": "Workflows code-first (Node/Python) ; pricing crédits sur temps de compute.",
            "capabilities": ["code_steps", "connect", "workflows", "ai_agents"],
            "pricing_model": "hybrid",
            "pricing_notes": "Free tier ; paid dès ~$29/mo.",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://pipedream.com/docs/pricing",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "activepieces",
            "name": "Activepieces",
            "url": "https://www.activepieces.com/",
            "segments": ["automation-platforms"],
            "description": "Automation open-source (MIT) + cloud ; alternative self-host à Zapier/n8n.",
            "capabilities": ["open_source", "self_hosted", "pieces", "ai_flows"],
            "pricing_model": "hybrid",
            "pricing_notes": "Cloud Pro ~$25/mo ; OSS gratuit self-hosted.",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://propicked.com/blog/best-workflow-automation-2026-zapier-make-n8n-workato-tray",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "microsoft-power-automate",
            "name": "Microsoft Power Automate",
            "url": "https://www.microsoft.com/en-us/power-platform/products/power-automate",
            "segments": ["automation-platforms"],
            "description": "Automatisation intégrée écosystème Microsoft 365 / Dynamics / Azure.",
            "capabilities": ["rpa", "cloud_flows", "desktop_flows", "m365_integration"],
            "pricing_model": "hybrid",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.youngju.dev/blog/culture/2026-05-16-zapier-n8n-make-activepieces-pipedream-workato-tines-power-automate-2026-deep-dive.en",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "tines",
            "name": "Tines",
            "url": "https://www.tines.com/",
            "segments": ["automation-platforms"],
            "description": "Automation orientée sécurité/opérations ; stories no-code pour équipes SecOps.",
            "capabilities": ["secops_automation", "stories", "case_management"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.youngju.dev/blog/culture/2026-05-16-zapier-n8n-make-activepieces-pipedream-workato-tines-power-automate-2026-deep-dive.en",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "parsing-inbox.json": [
        {
            "id": "mailgun-inbound",
            "name": "Mailgun Inbound Routes",
            "url": "https://www.mailgun.com/products/send/inbound-routing/",
            "segments": ["parsing-inbox"],
            "description": "Routage email entrant vers webhooks ; base infra pour pipelines parsing custom.",
            "capabilities": ["inbound_email", "webhooks", "routing"],
            "pricing_model": "per_usage",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.mailgun.com/products/send/inbound-routing/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "postmark-inbound",
            "name": "Postmark Inbound",
            "url": "https://postmarkapp.com/developer/user-guide/inbound",
            "segments": ["parsing-inbox"],
            "description": "Réception emails entrants en JSON via webhook pour parsing applicatif.",
            "capabilities": ["inbound_parse", "webhooks", "json_payload"],
            "pricing_model": "per_usage",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://postmarkapp.com/developer/user-guide/inbound",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "extracta-ai",
            "name": "Extracta.ai",
            "url": "https://extracta.ai/",
            "segments": ["parsing-inbox", "document-idp"],
            "description": "Extraction IA depuis emails et documents sans templates préalables.",
            "capabilities": ["email_extraction", "document_extraction", "api"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://parsio.io/blog/top-document-extraction-tools/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "regtech.json": [
        {
            "id": "diligent",
            "name": "Diligent",
            "url": "https://www.diligent.com/",
            "segments": ["regtech", "grc-security"],
            "description": "Suite GRC enterprise incluant veille réglementaire et gestion policies pour boards et compliance.",
            "capabilities": ["regulatory_intelligence", "policy_management", "board_governance"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://riskpublishing.com/best-compliance-management-software-compared/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "metricstream-reg",
            "name": "MetricStream Regulatory Management",
            "url": "https://www.metricstream.com/",
            "segments": ["regtech", "grc-security"],
            "description": "GRC enterprise avec change management réglementaire sur 750+ régulateurs.",
            "capabilities": ["regulatory_change", "obligation_tracking", "ai_monitoring"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://riskpublishing.com/best-compliance-management-software-compared/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "vixio",
            "name": "Vixio",
            "url": "https://www.vixio.com/",
            "segments": ["regtech"],
            "description": "Regulatory intelligence spécialisée gambling/payments/finance.",
            "capabilities": ["regulatory_monitoring", "horizon_scanning", "expert_analysis"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.cbinsights.com/company/ascent-technologies",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "steel-eye",
            "name": "SteelEye",
            "url": "https://www.steeleye.com/",
            "segments": ["regtech"],
            "description": "Compliance communications & trade surveillance pour services financiers.",
            "capabilities": ["comms_surveillance", "trade_surveillance", "regulatory_reporting"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://dataintelo.com/report/regulatory-intelligence-platform-market",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "grc-security.json": [
        {
            "id": "navex",
            "name": "NAVEX One",
            "url": "https://www.navex.com/",
            "segments": ["grc-security"],
            "description": "Suite ethics & compliance : hotline, policies, formation, case management.",
            "capabilities": ["ethicspoint", "policy_management", "training", "case_management"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://riskpublishing.com/best-compliance-management-software-compared/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "vcomply",
            "name": "VComply",
            "url": "https://www.v-comply.com/",
            "segments": ["grc-security"],
            "description": "GRC cloud no-code : policies, risques, contrôles et suivi compliance temps réel.",
            "capabilities": ["policyops", "risk_matrix", "workflow_automation", "audit_ready"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://www.v-comply.com/blog/navex-alternatives-risk-management/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "auditboard",
            "name": "AuditBoard",
            "url": "https://www.auditboard.com/",
            "segments": ["grc-security"],
            "description": "Plateforme audit, risque et compliance ; leader mid-market audit-centric.",
            "capabilities": ["internal_audit", "sox", "risk_management", "compliance"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://techvendorindex.com/software/grc-compliance/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "rsa-archer",
            "name": "RSA Archer",
            "url": "https://www.archerirm.com/",
            "segments": ["grc-security"],
            "description": "IRM/GRC enterprise historique ; grands déploiements multi-frameworks.",
            "capabilities": ["integrated_risk", "grc", "vendor_risk", "business_resiliency"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://techvendorindex.com/software/grc-compliance/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "collibra",
            "name": "Collibra",
            "url": "https://www.collibra.com/",
            "segments": ["grc-security", "ai-governance"],
            "description": "Data governance enterprise ; extension vers gouvernance IA et catalogage.",
            "capabilities": ["data_catalog", "data_governance", "policy_management"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.modulos.ai/best-ai-governance-platforms/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "ai-governance.json": [
        {
            "id": "ibm-watsonx-governance",
            "name": "IBM watsonx.governance",
            "url": "https://www.ibm.com/products/watsonx-governance",
            "segments": ["ai-governance"],
            "description": "Gouvernance modèles et IA enterprise dans l'écosystème IBM watsonx.",
            "capabilities": ["model_governance", "risk_management", "compliance_tracking"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.modulos.ai/best-ai-governance-platforms/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "langsmith",
            "name": "LangSmith",
            "url": "https://www.langchain.com/langsmith",
            "segments": ["ai-governance"],
            "description": "Observabilité et évaluation apps LLM ; traçage pour audit technique des agents.",
            "capabilities": ["llm_tracing", "evaluations", "monitoring", "datasets"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://kla.digital/blog/best-eu-ai-act-compliance-software-2026",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "arthur-ai",
            "name": "Arthur AI",
            "url": "https://www.arthur.ai/",
            "segments": ["ai-governance"],
            "description": "Monitoring modèles ML/LLM : performance, bias, drift en production.",
            "capabilities": ["model_monitoring", "bias_detection", "drift"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://dancumberlandlabs.com/blog/ai-governance-tools/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "modelop",
            "name": "ModelOp",
            "url": "https://www.modelop.com/",
            "segments": ["ai-governance"],
            "description": "Gouvernance cycle de vie modèles IA pour enterprises régulées.",
            "capabilities": ["model_lifecycle", "ai_governance", "regulatory_alignment"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://dancumberlandlabs.com/blog/ai-governance-tools/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "atlan",
            "name": "Atlan",
            "url": "https://atlan.com/",
            "segments": ["ai-governance"],
            "description": "Metadata/active governance pour données et actifs IA dans les pipelines analytics.",
            "capabilities": ["data_catalog", "ai_asset_governance", "lineage"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://dancumberlandlabs.com/blog/ai-governance-tools/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "document-idp.json": [
        {
            "id": "reducto",
            "name": "Reducto",
            "url": "https://reducto.ai/",
            "segments": ["document-idp"],
            "description": "Plateforme agentic document : Parse, Extract, Split, Edit avec citations par champ.",
            "capabilities": ["agentic_ocr", "schema_extract", "split", "edit", "citations"],
            "pricing_model": "per_usage",
            "pricing_notes": "Pay-as-you-go ; 15k crédits gratuits.",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://reducto.ai/compare/reducto-vs-llamaparse",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "llamaparse",
            "name": "LlamaParse (LlamaCloud)",
            "url": "https://www.llamaindex.ai/llamaparse",
            "segments": ["document-idp"],
            "description": "Parser document pour pipelines RAG LlamaIndex ; modes agentic et reconstruction sémantique.",
            "capabilities": ["rag_parsing", "markdown_output", "agentic_modes", "tables"],
            "pricing_model": "hybrid",
            "pricing_notes": "Crédits ; Starter ~$50/mo pour 40K crédits.",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://reducto.ai/compare/reducto-vs-llamaparse",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "unstructured",
            "name": "Unstructured",
            "url": "https://unstructured.io/",
            "segments": ["document-idp"],
            "description": "ETL documents pour LLM : partition, chunking, extraction ; API et open-source.",
            "capabilities": ["partition", "chunking", "api", "connectors"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://llms.reducto.ai/document-parser-comparison",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "uipath-document-understanding",
            "name": "UiPath Document Understanding",
            "url": "https://www.uipath.com/platform/agentic-automation/document-understanding",
            "segments": ["document-idp", "automation-platforms"],
            "description": "IDP intégré à la plateforme RPA UiPath ; extraction et classification documents.",
            "capabilities": ["idp", "rpa_integration", "classification", "extraction"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://automationtoday.net/news/idc-names-leaders-in-idp-market-assessment/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "opentext-idp",
            "name": "OpenText Intelligent Document Processing",
            "url": "https://www.opentext.com/products/intelligent-document-processing",
            "segments": ["document-idp"],
            "description": "IDP enterprise leader IDC ; workflows capture-to-insight intégrés content services.",
            "capabilities": ["capture", "classification", "extraction", "workflow"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.opentext.com/resources/intelligent-document-processing",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "hyland-idp",
            "name": "Hyland IDP",
            "url": "https://www.hyland.com/en/platform/intelligent-document-processing",
            "segments": ["document-idp"],
            "description": "IDP agentic sur Content Innovation Cloud ; leader IDC MarketScape 2025-2026.",
            "capabilities": ["capture", "classification", "agentic_workflows", "content_services"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.prnewswire.com/news-releases/hyland-named-a-leader-in-idc-marketscape-for-worldwide-intelligent-document-processing-software-2025-2026-vendor-assessment-302642995.html",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
    ],
    "ai-copilot-dev.json": [
        {
            "id": "devin",
            "name": "Devin (Cognition)",
            "url": "https://devin.ai/",
            "segments": ["ai-copilot-dev"],
            "description": "Agent logiciel cloud + Devin Desktop ; plans quota Free/Pro/Max/Teams.",
            "capabilities": ["cloud_agent", "desktop_ide", "cli", "code_review"],
            "pricing_model": "hybrid",
            "pricing_notes": "Pro $20/mo ; Max $200/mo ; Teams $80/mo + $40/siège.",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://devin.ai/pricing/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "claude-code",
            "name": "Claude Code",
            "url": "https://www.anthropic.com/claude-code",
            "segments": ["ai-copilot-dev"],
            "description": "Agent coding Anthropic en terminal/IDE ; plans Pro/Max/Team.",
            "capabilities": ["terminal_agent", "codebase_edits", "team_seats"],
            "pricing_model": "hybrid",
            "pricing_notes": "Team ~$20-25/siège ; Max ~$100/mo.",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://zylos.ai/research/2026-03-29-ai-agent-platform-economics-pricing-unit-economics",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "amazon-q-developer",
            "name": "Amazon Q Developer",
            "url": "https://aws.amazon.com/q/developer/",
            "segments": ["ai-copilot-dev"],
            "description": "Copilot AWS intégré IDE et services cloud ; tier gratuit et Pro.",
            "capabilities": ["code_completion", "agent", "aws_integration"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://aws.amazon.com/q/developer/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "jetbrains-ai",
            "name": "JetBrains AI",
            "url": "https://www.jetbrains.com/ai/",
            "segments": ["ai-copilot-dev"],
            "description": "Assistant IA intégré aux IDE JetBrains (completion, chat, agents).",
            "capabilities": ["ide_integration", "completion", "chat"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.jetbrains.com/ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "tabnine",
            "name": "Tabnine",
            "url": "https://www.tabnine.com/",
            "segments": ["ai-copilot-dev"],
            "description": "Copilot code avec options enterprise, on-prem et politiques privacy.",
            "capabilities": ["code_completion", "on_prem", "enterprise_policies"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://www.tabnine.com/pricing",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "support-sales-agents.json": [
        {
            "id": "ada",
            "name": "Ada",
            "url": "https://www.ada.cx/",
            "segments": ["support-sales-agents"],
            "description": "Plateforme automation support IA ; résolution et orchestration conversations.",
            "capabilities": ["ai_agent", "multichannel", "analytics"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.intercom.com/pricing",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
            "notes": "Concurrent helpdesk AI ; pricing non public."
        },
        {
            "id": "forethought",
            "name": "Forethought",
            "url": "https://forethought.ai/",
            "segments": ["support-sales-agents"],
            "description": "Agents IA support : tri, résolution et assistance agents humains.",
            "capabilities": ["ticket_deflection", "agent_assist", "workflow_automation"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://helply.com/blog/per-seat-saas-pricing-dying",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "decagon",
            "name": "Decagon",
            "url": "https://decagon.ai/",
            "segments": ["support-sales-agents"],
            "description": "Agents conversationnels enterprise pour support client automatisé.",
            "capabilities": ["conversational_agents", "enterprise_support", "integrations"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://pickaxe.co/post/ai-agent-pricing-models",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "hubspot-breeze",
            "name": "HubSpot Breeze AI",
            "url": "https://www.hubspot.com/products/artificial-intelligence",
            "segments": ["support-sales-agents"],
            "description": "Couche IA HubSpot CRM ; agents et résolutions facturées en hybrid seat + crédits.",
            "capabilities": ["crm_ai", "customer_agent", "sales_ai", "credits"],
            "pricing_model": "hybrid",
            "pricing_notes": "Crédits IA + composantes par résolution (marché 2026).",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://helply.com/blog/per-seat-saas-pricing-dying",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "freshworks-freddy",
            "name": "Freshworks Freddy AI",
            "url": "https://www.freshworks.com/freddy-ai/",
            "segments": ["support-sales-agents"],
            "description": "IA intégrée suite Freshdesk/Freshsales ; copilot et automation support.",
            "capabilities": ["support_ai", "sales_ai", "copilot"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.freshworks.com/freddy-ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
}

# Enrichir segments sur vendeurs existants (sans dupliquer id)
SEGMENT_PATCHES: dict[str, list[str]] = {
    "modulos": ["compliance-to-spec"],
    "sia-regai": ["compliance-to-spec"],
    "regology": ["compliance-to-spec"],
}


def merge() -> None:
    all_ids: set[str] = set()

    for path in sorted(VENDORS_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        for v in data.get("vendors", []):
            all_ids.add(v["id"])

    for fname, new_vendors in ADDITIONS.items():
        path = VENDORS_DIR / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        for v in new_vendors:
            if v["id"] in all_ids:
                print(f"skip duplicate: {v['id']}")
                continue
            data["vendors"].append(v)
            all_ids.add(v["id"])
        data["updated_at"] = TODAY
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"updated {fname}: +{len(new_vendors)} candidates")

    for path in sorted(VENDORS_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        changed = False
        for v in data.get("vendors", []):
            extra = SEGMENT_PATCHES.get(v["id"], [])
            for seg in extra:
                if seg not in v["segments"]:
                    v["segments"].append(seg)
                    changed = True
        if changed:
            data["updated_at"] = TODAY
            path.write_text(
                json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            print(f"patched segments in {path.name}")


if __name__ == "__main__":
    merge()
