#!/usr/bin/env python3
"""Vague 3 — nouveaux segments + graines vendeurs."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDORS_DIR = ROOT / "catalogue-saas" / "vendors"
TODAY = "2026-06-22"

NEW_SEGMENT_FILES: dict[str, list[dict]] = {
    "regulatory-reporting-eu.json": [
        {
            "id": "sovos",
            "name": "Sovos",
            "url": "https://sovos.com/",
            "segments": ["regulatory-reporting-eu"],
            "description": "Tax compliance et e-invoicing globale ; conformité facturation électronique multi-pays.",
            "capabilities": ["e_invoicing", "vat_reporting", "statutory_reporting"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://sovos.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "pagero",
            "name": "Pagero",
            "url": "https://www.pagero.com/",
            "segments": ["regulatory-reporting-eu"],
            "description": "Réseau e-invoicing et conformité documentaire B2B/B2G en Europe.",
            "capabilities": ["peppol", "e_invoicing", "order_to_cash"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "europe",
            "source_url": "https://www.pagero.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "chorus-pro",
            "name": "Chorus Pro",
            "url": "https://chorus-pro.gouv.fr/",
            "segments": ["regulatory-reporting-eu"],
            "description": "Plateforme publique française de facturation électronique secteur public.",
            "capabilities": ["e_invoicing_public", "b2g", "france"],
            "pricing_model": "freemium",
            "pricing_notes": "Service public ; gratuit pour utilisateurs éligibles.",
            "target_market": "enterprise",
            "geography": "france",
            "source_url": "https://chorus-pro.gouv.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "stripe-tax",
            "name": "Stripe Tax",
            "url": "https://stripe.com/tax",
            "segments": ["regulatory-reporting-eu"],
            "description": "Calcul et collecte taxes automatiques pour SaaS et e-commerce.",
            "capabilities": ["tax_calculation", "vat", "reporting"],
            "pricing_model": "per_usage",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://stripe.com/tax",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "privacy-consent.json": [
        {
            "id": "didomi",
            "name": "Didomi",
            "url": "https://www.didomi.io/",
            "segments": ["privacy-consent"],
            "description": "CMP et gestion consentement RGPD ; SDK web/mobile et préférences privacy.",
            "capabilities": ["cmp", "consent", "preference_center", "gdpr"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "europe",
            "source_url": "https://www.didomi.io/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "onetrust-privacy",
            "name": "OneTrust Privacy",
            "url": "https://www.onetrust.com/products/privacy-management/",
            "segments": ["privacy-consent", "grc-security"],
            "description": "Gestion privacy : DPIA, registres, droits des personnes, cookies.",
            "capabilities": ["dpia", "ropa", "dsar", "cookie_consent"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.onetrust.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "osano",
            "name": "Osano",
            "url": "https://www.osano.com/",
            "segments": ["privacy-consent"],
            "description": "Data privacy platform : consent, vendor monitoring, DSAR.",
            "capabilities": ["consent_management", "vendor_monitoring", "dsar"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.osano.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "axeptio",
            "name": "Axeptio",
            "url": "https://www.axeptio.eu/",
            "segments": ["privacy-consent"],
            "description": "CMP française RGPD/ePrivacy pour sites et apps.",
            "capabilities": ["cmp", "consent", "france", "gdpr"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "france",
            "source_url": "https://www.axeptio.eu/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "accessibility-compliance.json": [
        {
            "id": "accessibility-checker",
            "name": "Accessibility Checker",
            "url": "https://www.accessibilitychecker.org/",
            "segments": ["accessibility-compliance"],
            "description": "Audit automatisé WCAG pour sites web avec rapports de conformité.",
            "capabilities": ["wcag_scan", "reports", "monitoring"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.accessibilitychecker.org/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "deque-axe",
            "name": "Deque axe DevTools",
            "url": "https://www.deque.com/axe/",
            "segments": ["accessibility-compliance"],
            "description": "Moteur de tests accessibilité (axe) intégré dev/CI pour WCAG.",
            "capabilities": ["automated_testing", "ci_integration", "wcag"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://www.deque.com/axe/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "userway",
            "name": "UserWay",
            "url": "https://userway.org/",
            "segments": ["accessibility-compliance"],
            "description": "Widget et audit accessibilité pour sites ; conformité ADA/WCAG.",
            "capabilities": ["accessibility_widget", "audits", "remediation"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://userway.org/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "acceslibre",
            "name": "Accès Libé (data.gouv.fr)",
            "url": "https://acceslibre.beta.gouv.fr/",
            "segments": ["accessibility-compliance", "territorial-analytics"],
            "description": "Service public cartographiant l'accessibilité des ERP en France (open data).",
            "capabilities": ["erp_accessibility", "open_data", "france"],
            "pricing_model": "freemium",
            "pricing_notes": "Service public gratuit.",
            "target_market": "self_serve",
            "geography": "france",
            "source_url": "https://acceslibre.beta.gouv.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
    ],
    "finance-accounting-ai.json": [
        {
            "id": "vic-ai",
            "name": "Vic.ai",
            "url": "https://www.vic.ai/",
            "segments": ["finance-accounting-ai"],
            "description": "AP automation IA : traitement factures, codage comptable, approbations.",
            "capabilities": ["invoice_processing", "ap_automation", "gl_coding"],
            "pricing_model": "enterprise_quote",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://www.vic.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "bill-com",
            "name": "BILL",
            "url": "https://www.bill.com/",
            "segments": ["finance-accounting-ai"],
            "description": "AP/AR et paiements PME avec automatisation factures et workflows.",
            "capabilities": ["ap_ar", "payments", "invoice_workflows"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "us",
            "source_url": "https://www.bill.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "ramp",
            "name": "Ramp",
            "url": "https://ramp.com/",
            "segments": ["finance-accounting-ai"],
            "description": "Cartes dépenses + automatisation compta et détection anomalies.",
            "capabilities": ["expense_management", "accounting_automation", "cards"],
            "pricing_model": "freemium",
            "target_market": "smb",
            "geography": "us",
            "source_url": "https://ramp.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "pennylane",
            "name": "Pennylane",
            "url": "https://www.pennylane.com/",
            "segments": ["finance-accounting-ai"],
            "description": "Compta/finance PME française avec automatisation et cabinet comptable intégré.",
            "capabilities": ["accounting", "invoicing", "france", "ai_assist"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "france",
            "source_url": "https://www.pennylane.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "legal-contract-ai.json": [
        {
            "id": "harvey-ai",
            "name": "Harvey",
            "url": "https://www.harvey.ai/",
            "segments": ["legal-contract-ai"],
            "description": "IA juridique enterprise : recherche, rédaction, workflows cabinets et legal ops.",
            "capabilities": ["legal_research", "drafting", "enterprise_legal"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.harvey.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "ironclad",
            "name": "Ironclad",
            "url": "https://ironcladapp.com/",
            "segments": ["legal-contract-ai"],
            "description": "CLM : création, négociation, signature et analyse contractuelle.",
            "capabilities": ["clm", "contract_workflow", "ai_review"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://ironcladapp.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "luminance",
            "name": "Luminance",
            "url": "https://www.luminance.com/",
            "segments": ["legal-contract-ai"],
            "description": "Due diligence et revue contractuelle IA pour legal teams.",
            "capabilities": ["contract_review", "due_diligence", "anomaly_detection"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.luminance.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "spellbook",
            "name": "Spellbook",
            "url": "https://www.spellbook.legal/",
            "segments": ["legal-contract-ai"],
            "description": "Copilot rédaction contractuelle dans Microsoft Word pour avocats.",
            "capabilities": ["contract_drafting", "word_plugin", "clause_library"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.spellbook.legal/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "ai-productivity.json": [
        {
            "id": "notion-ai",
            "name": "Notion AI",
            "url": "https://www.notion.so/product/ai",
            "segments": ["ai-productivity"],
            "description": "IA intégrée workspace Notion : rédaction, synthèse, Q&A sur notes.",
            "capabilities": ["writing", "summarization", "workspace_qa"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.notion.so/product/ai",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "jasper",
            "name": "Jasper",
            "url": "https://www.jasper.ai/",
            "segments": ["ai-productivity"],
            "description": "Plateforme contenu marketing IA pour équipes brand.",
            "capabilities": ["marketing_copy", "brand_voice", "campaigns"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.jasper.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "gamma",
            "name": "Gamma",
            "url": "https://gamma.app/",
            "segments": ["ai-productivity"],
            "description": "Génération présentations et documents IA à partir de prompts.",
            "capabilities": ["presentations", "documents", "ai_generation"],
            "pricing_model": "freemium",
            "target_market": "self_serve",
            "geography": "global",
            "source_url": "https://gamma.app/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "otter-ai",
            "name": "Otter.ai",
            "url": "https://otter.ai/",
            "segments": ["ai-productivity", "voice-speech-ai"],
            "description": "Transcription et notes de réunion automatiques.",
            "capabilities": ["meeting_transcription", "summaries", "collaboration"],
            "pricing_model": "freemium",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://otter.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "rag-knowledge.json": [
        {
            "id": "glean",
            "name": "Glean",
            "url": "https://www.glean.com/",
            "segments": ["rag-knowledge"],
            "description": "Recherche enterprise IA sur apps internes ; index unifié et permissions.",
            "capabilities": ["enterprise_search", "permissions", "connectors"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.glean.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "dust",
            "name": "Dust",
            "url": "https://dust.tt/",
            "segments": ["rag-knowledge"],
            "description": "Assistants IA sur données d'équipe avec connecteurs et agents.",
            "capabilities": ["team_assistants", "connectors", "agents"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "europe",
            "source_url": "https://dust.tt/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "coveo",
            "name": "Coveo",
            "url": "https://www.coveo.com/",
            "segments": ["rag-knowledge"],
            "description": "Relevance platform : search IA et recommandations pour enterprise.",
            "capabilities": ["semantic_search", "recommendations", "analytics"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.coveo.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "contextual-ai",
            "name": "Contextual AI",
            "url": "https://contextual.ai/",
            "segments": ["rag-knowledge"],
            "description": "Plateforme RAG enterprise avec grounding et réduction hallucinations.",
            "capabilities": ["grounded_rag", "enterprise", "api"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://contextual.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "voice-speech-ai.json": [
        {
            "id": "deepgram",
            "name": "Deepgram",
            "url": "https://deepgram.com/",
            "segments": ["voice-speech-ai"],
            "description": "API speech-to-text et text-to-speech temps réel.",
            "capabilities": ["stt", "tts", "api", "realtime"],
            "pricing_model": "per_usage",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://deepgram.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "assemblyai",
            "name": "AssemblyAI",
            "url": "https://www.assemblyai.com/",
            "segments": ["voice-speech-ai"],
            "description": "API transcription et compréhension audio pour développeurs.",
            "capabilities": ["transcription", "audio_intelligence", "api"],
            "pricing_model": "per_usage",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://www.assemblyai.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "elevenlabs",
            "name": "ElevenLabs",
            "url": "https://elevenlabs.io/",
            "segments": ["voice-speech-ai"],
            "description": "Synthèse vocale IA et agents conversationnels audio.",
            "capabilities": ["tts", "voice_cloning", "conversational_ai"],
            "pricing_model": "hybrid",
            "target_market": "self_serve",
            "geography": "global",
            "source_url": "https://elevenlabs.io/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "retell-ai",
            "name": "Retell AI",
            "url": "https://www.retellai.com/",
            "segments": ["voice-speech-ai", "support-sales-agents"],
            "description": "API agents vocaux temps réel pour support et sales.",
            "capabilities": ["voice_agents", "phone", "api"],
            "pricing_model": "per_usage",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.retellai.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "hr-talent-ai.json": [
        {
            "id": "paradox-olivia",
            "name": "Paradox (Olivia)",
            "url": "https://www.paradox.ai/",
            "segments": ["hr-talent-ai"],
            "description": "Agent IA recrutement : screening, scheduling, onboarding candidats.",
            "capabilities": ["recruiting_agent", "scheduling", "high_volume_hiring"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.paradox.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "eightfold",
            "name": "Eightfold AI",
            "url": "https://eightfold.ai/",
            "segments": ["hr-talent-ai"],
            "description": "Talent intelligence : matching candidats, upskilling, workforce planning.",
            "capabilities": ["talent_matching", "workforce_planning", "ai_screening"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://eightfold.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "hirevue",
            "name": "HireVue",
            "url": "https://www.hirevue.com/",
            "segments": ["hr-talent-ai"],
            "description": "Entretiens vidéo et assessments IA pour recrutement.",
            "capabilities": ["video_interviews", "assessments", "ai_scoring"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.hirevue.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "textio",
            "name": "Textio",
            "url": "https://textio.com/",
            "segments": ["hr-talent-ai", "ai-productivity"],
            "description": "Optimisation offres d'emploi et communications RH inclusive (IA linguistique).",
            "capabilities": ["job_posts", "inclusive_language", "analytics"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://textio.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "data-enrichment-b2b.json": [
        {
            "id": "apollo-io",
            "name": "Apollo.io",
            "url": "https://www.apollo.io/",
            "segments": ["data-enrichment-b2b"],
            "description": "Base contacts B2B + enrichissement emails et firmographics pour sales.",
            "capabilities": ["contact_data", "enrichment", "sequences"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "global",
            "source_url": "https://www.apollo.io/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "clearbit",
            "name": "Clearbit (HubSpot)",
            "url": "https://clearbit.com/",
            "segments": ["data-enrichment-b2b"],
            "description": "Enrichissement données entreprises et personnes via API.",
            "capabilities": ["firmographics", "api_enrichment", "reveal"],
            "pricing_model": "hybrid",
            "target_market": "mid_market",
            "geography": "global",
            "source_url": "https://clearbit.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "pappers",
            "name": "Pappers",
            "url": "https://www.pappers.fr/",
            "segments": ["data-enrichment-b2b", "territorial-analytics"],
            "description": "Données entreprises françaises (SIRENE, bilans) ; API et veille.",
            "capabilities": ["france_companies", "api", "beneficial_owners"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "france",
            "source_url": "https://www.pappers.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
        {
            "id": "zoominfo",
            "name": "ZoomInfo",
            "url": "https://www.zoominfo.com/",
            "segments": ["data-enrichment-b2b"],
            "description": "Intelligence commerciale B2B : contacts, intent, firmographics.",
            "capabilities": ["b2b_data", "intent_signals", "sales_intelligence"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "global",
            "source_url": "https://www.zoominfo.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "public-procurement-intel.json": [
        {
            "id": "marchespublics-ai",
            "name": "marchespublics.ai",
            "url": "https://marchespublics.ai/",
            "segments": ["public-procurement-intel"],
            "description": "Veille et analyse marchés publics français assistée IA.",
            "capabilities": ["ao_monitoring", "france", "ai_analysis"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "france",
            "source_url": "https://marchespublics.ai/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
            "notes": "Concurrent cité dans revue idée 0001 du dépôt."
        },
        {
            "id": "maitre-ao",
            "name": "Maître AO",
            "url": "https://www.maitre-ao.fr/",
            "segments": ["public-procurement-intel"],
            "description": "Plateforme veille appels d'offres publics France.",
            "capabilities": ["ao_alerts", "france", "tenders"],
            "pricing_model": "hybrid",
            "target_market": "smb",
            "geography": "france",
            "source_url": "https://www.maitre-ao.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
            "notes": "Concurrent cité dans revue idée 0001."
        },
        {
            "id": "aws-boamp",
            "name": "BOAMP (open data)",
            "url": "https://www.boamp.fr/",
            "segments": ["public-procurement-intel"],
            "description": "Bulletin officiel annonces marchés publics ; flux open data via data.gouv.fr.",
            "capabilities": ["official_tenders", "open_data", "france"],
            "pricing_model": "freemium",
            "pricing_notes": "Source publique gratuite.",
            "target_market": "self_serve",
            "geography": "france",
            "source_url": "https://www.data.gouv.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "achatpublic",
            "name": "PLACE (achatpublic.com)",
            "url": "https://www.achatpublic.com/",
            "segments": ["public-procurement-intel"],
            "description": "Plateforme dématérialisation marchés publics côté acheteurs.",
            "capabilities": ["e_procurement", "france", "public_buyers"],
            "pricing_model": "enterprise_quote",
            "target_market": "enterprise",
            "geography": "france",
            "source_url": "https://www.achatpublic.com/",
            "source_consulted_at": TODAY,
            "verification_status": "partial",
        },
    ],
    "territorial-analytics.json": [
        {
            "id": "datagouv",
            "name": "data.gouv.fr",
            "url": "https://www.data.gouv.fr/",
            "segments": ["territorial-analytics"],
            "description": "Portail open data France ; base pour observatoires et réutilisations territoriales.",
            "capabilities": ["open_data", "api", "france", "datasets"],
            "pricing_model": "freemium",
            "target_market": "self_serve",
            "geography": "france",
            "source_url": "https://www.data.gouv.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "georisques",
            "name": "Géorisques",
            "url": "https://www.georisques.gouv.fr/",
            "segments": ["territorial-analytics"],
            "description": "Portail public risques environnementaux par adresse/territoire.",
            "capabilities": ["environmental_risks", "open_data", "france"],
            "pricing_model": "freemium",
            "target_market": "self_serve",
            "geography": "france",
            "source_url": "https://www.georisques.gouv.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
        {
            "id": "ofgl",
            "name": "OFGL Observatoire",
            "url": "https://www.ofgl.fr/",
            "segments": ["territorial-analytics"],
            "description": "Observatoire finances locales des collectivités françaises.",
            "capabilities": ["local_finance", "benchmark", "france"],
            "pricing_model": "freemium",
            "target_market": "self_serve",
            "geography": "france",
            "source_url": "https://www.ofgl.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
            "notes": "Concurrent/service public cité idée 0020."
        },
        {
            "id": "cartes-gouv",
            "name": "Géoportail / cartes.gouv.fr",
            "url": "https://cartes.gouv.fr/",
            "segments": ["territorial-analytics"],
            "description": "Infrastructure cartographique publique française (IGN).",
            "capabilities": ["maps", "geodata", "france", "open_data"],
            "pricing_model": "freemium",
            "target_market": "self_serve",
            "geography": "france",
            "source_url": "https://cartes.gouv.fr/",
            "source_consulted_at": TODAY,
            "verification_status": "verified",
        },
    ],
}


def main() -> None:
    existing_ids: set[str] = set()
    for path in VENDORS_DIR.glob("*.json"):
        data = json.loads(path.read_text(encoding="utf-8"))
        for v in data.get("vendors", []):
            existing_ids.add(v["id"])

    added = 0
    for fname, vendors in NEW_SEGMENT_FILES.items():
        path = VENDORS_DIR / fname
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
        else:
            data = {
                "segment": fname.replace(".json", ""),
                "updated_at": TODAY,
                "vendors": [],
            }

        for v in vendors:
            if v["id"] in existing_ids:
                print(f"skip duplicate id: {v['id']}")
                continue
            data["vendors"].append(v)
            existing_ids.add(v["id"])
            added += 1

        data["updated_at"] = TODAY
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"wrote {fname} ({len(data['vendors'])} vendors)")

    print(f"added {added} new vendors")


if __name__ == "__main__":
    main()
